import { useEffect, useMemo, useState } from "react";
import { apiFetch, apiUrl } from "./api.js";
import { usePanelDialog } from "./panel-dialog.js";
import "./commercial-admin.css";

type Tab="dashboard"|"leads"|"advertisers"|"orders"|"payments"|"cash"|"campaigns"|"plans"|"settings";
const tabs:Array<{id:Tab;label:string}>=[
  {id:"dashboard",label:"Resumen"},{id:"leads",label:"Prospectos"},{id:"advertisers",label:"Comercios"},
  {id:"orders",label:"Ventas y órdenes"},{id:"payments",label:"Pagos"},{id:"cash",label:"Caja y conciliación"},{id:"campaigns",label:"Campañas"},{id:"plans",label:"Planes y tarifas"},{id:"settings",label:"Configuración"}
];
const tabPermission:Record<Tab,string>={dashboard:"commercial:dashboard",leads:"commercial:leads:view",advertisers:"commercial:advertisers:view",orders:"commercial:orders:view",payments:"commercial:payments:view",cash:"commercial:payments:view",campaigns:"commercial:campaigns:view",plans:"commercial:campaigns:view",settings:"commercial:plans:manage"};
const statusLabel:Record<string,string>={NEW:"Nuevo",IN_PROGRESS:"En gestión",QUALIFIED:"Interesado calificado",REQUIRES_CONTACT:"Solicita asesor",CONVERTED:"Cliente convertido",LOST:"No concretado",DRAFT:"Borrador",PENDING_PAYMENT:"Pendiente de pago",PAYMENT_REVIEW:"Pago recibido · pendiente de conciliación",PAID:"Pagada",PENDING_REVIEW:"Contenido en revisión",APPROVED:"Aprobada",SCHEDULED:"Programada",ACTIVE:"Activa",PAUSED:"Pausada",REJECTED:"Rechazada",EXPIRED:"Finalizada",CANCELLED:"Cancelada",PENDING:"Pendiente",RECEIVED:"Pago recibido",UNDER_REVIEW:"Pendiente de conciliación",APPROVED_PAYMENT:"Pago aprobado",REFUNDED:"Reembolsado",PROSPECT:"Prospecto",INACTIVE:"Inactivo",BLOCKED:"Bloqueado",NOT_RECEIVED:"No recibido",PENDING_CLOSURE:"Pendiente de cierre",PENDING_RECONCILIATION:"Pendiente de conciliación",RECONCILED:"Conciliado"};
const sourceLabel:Record<string,string>={INSTAGRAM:"Instagram",FACEBOOK:"Facebook",WHATSAPP:"WhatsApp",WEB:"Sitio web",COMMERCIAL:"Comercial",ADMIN:"Administración",OTHER:"Otro"};
const money=(value:unknown,currency="USD")=>new Intl.NumberFormat("es-EC",{style:"currency",currency}).format(Number(value??0));
const date=(value:unknown)=>value?new Date(String(value)).toLocaleString("es-EC"):"—";
function Badge({value}:{value:string}){return <span className={`commercial-badge ${value.toLowerCase()}`}>{statusLabel[value]??value.replaceAll("_"," ")}</span>}
function Empty({children}:{children:string}){return <div className="commercial-empty"><strong>Sin información</strong><span>{children}</span></div>}
function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <div className="commercial-table"><table><thead><tr>{headers.map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex} data-label={headers[cellIndex]}>{cell}</td>)}</tr>)}</tbody></table></div>}
const fileAsBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result??""));reader.onerror=()=>reject(new Error("No se pudo leer el comprobante."));reader.readAsDataURL(file)});

export function CommercialAdmin({token,permissions}:{token:string;permissions:string[]}){
  const [tab,setTab]=useState<Tab>(()=>tabs.find(item=>permissions.includes(tabPermission[item.id]))?.id??"dashboard"),[data,setData]=useState<any>(),[error,setError]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("ALL"),[search,setSearch]=useState(""),[paymentOrder,setPaymentOrder]=useState<any|null>(null),[paymentMethod,setPaymentMethod]=useState<"CASH"|"BANK_TRANSFER">("CASH"),[paymentReference,setPaymentReference]=useState(""),[paymentProof,setPaymentProof]=useState<File|null>(null);
  const dialog=usePanelDialog();
  const can=(permission:string)=>permissions.includes(permission);
  const endpoint=useMemo(()=>({dashboard:"/v1/admin/commercial/dashboard",leads:"/v1/admin/commercial/leads",advertisers:"/v1/admin/commercial/advertisers",orders:"/v1/admin/commercial/orders",payments:"/v1/admin/commercial/payments",cash:"/v1/admin/commercial/cash-closures",campaigns:"/v1/admin/commercial/campaigns",plans:"/v1/admin/commercial/plans",settings:"/v1/admin/commercial/settings"}[tab]),[tab]);
  async function load(){setBusy(true);try{const params=new URLSearchParams();if(filter!=="ALL"&&tab!=="dashboard"&&tab!=="plans")params.set("status",filter);if(search.trim()&&["leads","advertisers"].includes(tab))params.set("search",search.trim());setData(await apiFetch<any>(`${endpoint}${params.size?`?${params}`:""}`,token));setError("");}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo cargar el módulo comercial.");}finally{setBusy(false)}}
  useEffect(()=>{setFilter("ALL");setSearch("");void load();},[tab,endpoint,token]);
  async function createLead(){const values=await dialog.open({eyebrow:"NUEVO PROSPECTO",title:"Registrar oportunidad comercial",description:"La invitación segura se genera después desde la lista de prospectos.",confirmLabel:"Crear prospecto",fields:[{name:"businessName",label:"Negocio",required:true,minLength:2},{name:"businessType",label:"Tipo de negocio",required:true,minLength:2},{name:"contactName",label:"Contacto",required:true,minLength:2},{name:"phone",label:"Teléfono",required:true,minLength:8},{name:"email",label:"Correo",required:true},{name:"city",label:"Ciudad",required:true,minLength:2},{name:"interest",label:"Interés o necesidad",type:"textarea",required:true,minLength:2}]});if(!values)return;await action("/v1/admin/commercial/leads","POST",{...values,source:"COMMERCIAL",requiresContact:false,conversationState:{createdFrom:"ADMIN_PANEL"}},"Prospecto creado. Ya puedes generar su invitación segura.")}
  async function invite(lead:any){const values=await dialog.open({eyebrow:"INVITACIÓN SEGURA",title:`Invitar a ${lead.businessName}`,description:"El enlace anterior quedará revocado. El comercio recibirá el nuevo enlace por correo.",confirmLabel:"Generar invitación",fields:[{name:"purpose",label:"Tipo",type:"select",initialValue:"APPLICATION",options:[{value:"APPLICATION",label:"Completar solicitud"}]}]});if(!values)return;setBusy(true);try{const result=await apiFetch<any>("/v1/admin/commercial/invitations",token,{method:"POST",body:JSON.stringify({leadId:lead.id,purpose:"APPLICATION",correctionFields:[]})});await navigator.clipboard?.writeText(result.url);setSuccess("Invitación creada, enviada por correo y copiada al portapapeles.");}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo generar la invitación.");}finally{setBusy(false)}}
  async function updateLead(lead:any){
    const editableStatuses=["NEW","IN_PROGRESS","QUALIFIED","REQUIRES_CONTACT","LOST"];
    const converted=lead.status==="CONVERTED";
    const fields:any[]=converted?[]:[{name:"status",label:"Estado",type:"select",initialValue:lead.status,options:editableStatuses.map(value=>({value,label:statusLabel[value]??value}))}];
    fields.push({name:"note",label:"Nota de seguimiento",type:"textarea",required:true,minLength:3});
    const values=await dialog.open({title:`Actualizar ${lead.code}`,description:converted?"Este cliente se convirtió automáticamente al aprobar su primer pago. El estado queda protegido, pero puedes agregar una nota a su historial.":"Registra el avance sin perder el historial comercial. Cliente convertido se asigna automáticamente al aprobar el primer pago.",confirmLabel:"Guardar seguimiento",fields});
    if(!values)return;
    await action(`/v1/admin/commercial/leads/${lead.id}`,"PATCH",values,"Seguimiento actualizado.")
  }
  function openPayment(order:any){setPaymentOrder(order);setPaymentMethod("CASH");setPaymentReference("");setPaymentProof(null);setError("")}
  async function registerPayment(){
    if(!paymentOrder)return;
    if(paymentMethod==="BANK_TRANSFER"&&(!paymentReference.trim()||!paymentProof)){setError("La transferencia requiere referencia y comprobante.");return;}
    if(paymentProof&&(!["image/jpeg","image/png","image/webp","application/pdf"].includes(paymentProof.type)||paymentProof.size>5_000_000)){setError("El comprobante debe ser JPG, PNG, WEBP o PDF y pesar máximo 5 MB.");return;}
    setBusy(true);
    try{
      const proof=paymentProof?{fileBase64:await fileAsBase64(paymentProof),fileMime:paymentProof.type}:undefined;
      await apiFetch(`/v1/admin/commercial/orders/${paymentOrder.id}/payments`,token,{method:"POST",body:JSON.stringify({method:paymentMethod,amount:Number(paymentOrder.amount),reference:paymentReference.trim(),proof,idempotencyKey:crypto.randomUUID()})});
      setPaymentOrder(null);setPaymentProof(null);setSuccess("Pago recibido. Quedó pendiente de conciliación financiera.");setError("");await load();
    }catch(reason){setError(reason instanceof Error?reason.message:"No se pudo registrar el cobro.");}finally{setBusy(false)}
  }
  async function closeCash(item:any){const values=await dialog.open({eyebrow:"CIERRE DIARIO",title:`Cerrar caja del ${new Date(`${item.businessDate}T12:00:00`).toLocaleDateString("es-EC")}`,description:`${item.paymentCount} cobro(s) en efectivo · ${money(item.total)}`,confirmLabel:"Cerrar caja",fields:[{name:"notes",label:"Observación",type:"textarea",initialValue:""}]});if(!values)return;await action("/v1/admin/commercial/cash-closures","POST",{businessDate:item.businessDate,notes:values.notes??""},"Caja cerrada. Finanzas ya puede conciliarla.")}
  async function reviewClosure(item:any,decision:"RECONCILE"|"REJECT"){const values=await dialog.open({eyebrow:"CONCILIACIÓN FINANCIERA",title:decision==="RECONCILE"?"Conciliar cierre":"Rechazar cierre",description:`${item.commercial} · ${money(item.total,item.currency)}`,confirmLabel:decision==="RECONCILE"?"Confirmar conciliación":"Rechazar cierre",dangerous:decision==="REJECT",fields:[{name:"reference",label:"Referencia de liquidación",required:decision==="RECONCILE",minLength:decision==="RECONCILE"?3:undefined},{name:"note",label:decision==="REJECT"?"Motivo obligatorio":"Observación",type:"textarea",required:decision==="REJECT",minLength:decision==="REJECT"?5:undefined}]});if(!values)return;await action(`/v1/admin/commercial/cash-closures/${item.id}/review`,"POST",{decision,reference:values.reference??"",note:values.note??""},decision==="RECONCILE"?"Caja conciliada; las órdenes pasaron a Pagada y las campañas a revisión.":"Cierre rechazado para revisión.")}
  async function reviewPayment(payment:any,decision:"APPROVE"|"REJECT"){const values=await dialog.open({eyebrow:"VALIDACIÓN FINANCIERA",title:decision==="APPROVE"?"Aprobar comprobante":"Rechazar comprobante",description:`Orden ${payment.orderCode} · ${money(payment.amount,payment.currency)}`,confirmLabel:decision==="APPROVE"?"Aprobar pago":"Rechazar pago",dangerous:decision==="REJECT",fields:[{name:"reason",label:decision==="APPROVE"?"Referencia u observación":"Motivo obligatorio",type:"textarea",required:decision==="REJECT",minLength:decision==="REJECT"?5:undefined}]});if(!values)return;await action(`/v1/admin/commercial/payments/${payment.id}/review`,"POST",{decision,reason:values.reason},decision==="APPROVE"?"Pago aprobado; la campaña pasó a revisión de contenido.":"Pago rechazado y devuelto para corrección.")}
  async function campaignAction(campaign:any,actionName:string){const labels:Record<string,string>={APPROVE:"Aprobar y programar",REJECT:"Rechazar campaña",REQUEST_CORRECTION:"Solicitar corrección",PAUSE:"Pausar campaña",RESUME:"Reanudar campaña",CANCEL:"Cancelar campaña"};const needs=["REJECT","REQUEST_CORRECTION"].includes(actionName);const actionLabel=labels[actionName]??"Actualizar campaña";const values=await dialog.open({eyebrow:"CONTROL DE CONTENIDO",title:actionLabel,description:`${campaign.title} · ${campaign.advertiserName}`,confirmLabel:actionLabel,dangerous:["REJECT","CANCEL"].includes(actionName),fields:[{name:"note",label:needs?"Motivo obligatorio":"Observación",type:"textarea",required:needs,minLength:needs?5:0}]});if(!values)return;await action(`/v1/admin/commercial/campaigns/${campaign.id}/action`,"POST",{action:actionName,note:values.note},"Estado de campaña actualizado.")}
  async function createPlan(){const values=await dialog.open({eyebrow:"NUEVO PRODUCTO",title:"Crear plan publicitario",description:"Se crea inactivo para revisar precio, duración y ubicación antes de ofrecerlo.",confirmLabel:"Crear plan",fields:[{name:"code",label:"Código",required:true,minLength:2,placeholder:"INICIO_15_DIAS"},{name:"name",label:"Nombre",required:true,minLength:2},{name:"description",label:"Descripción",type:"textarea",required:true,minLength:5},{name:"durationDays",label:"Duración (días)",type:"number",initialValue:15,required:true,min:1,max:365},{name:"price",label:"Precio USD",type:"number",initialValue:0,required:true,min:0,step:.01},{name:"placement",label:"Ubicación principal",type:"select",initialValue:"PASSENGER_SEARCHING_DRIVER",options:[{value:"PASSENGER_SEARCHING_DRIVER",label:"Buscando conductor"},{value:"PASSENGER_WAITING_DRIVER",label:"Esperando conductor"},{value:"PASSENGER_TRIP_IN_PROGRESS",label:"Viaje en curso"}]}]});if(!values)return;await action("/v1/admin/commercial/plans","POST",{...values,code:String(values.code).trim().toUpperCase().replace(/[^A-Z0-9]+/g,"_"),currency:"USD",defaultWeight:1,allowedPlacements:[values.placement],active:false,sortOrder:0},"Plan creado inactivo.")}
  async function editPlan(plan:any){const values=await dialog.open({eyebrow:"PLAN PUBLICITARIO",title:`Editar ${plan.name}`,description:"Los cambios aplican a solicitudes nuevas; las órdenes creadas conservan su snapshot comercial.",confirmLabel:"Guardar plan",fields:[{name:"name",label:"Nombre",required:true,minLength:2,initialValue:plan.name},{name:"description",label:"Descripción",type:"textarea",required:true,minLength:5,initialValue:plan.description??""},{name:"durationDays",label:"Duración (días)",type:"number",required:true,min:1,max:365,initialValue:plan.durationDays},{name:"price",label:"Precio USD",type:"number",required:true,min:0,step:.01,initialValue:plan.price},{name:"placement",label:"Ubicación principal",type:"select",initialValue:plan.placement??"PASSENGER_SEARCHING_DRIVER",options:[{value:"PASSENGER_SEARCHING_DRIVER",label:"Buscando conductor"},{value:"PASSENGER_WAITING_DRIVER",label:"Esperando conductor"},{value:"PASSENGER_TRIP_IN_PROGRESS",label:"Viaje en curso"}]},{name:"active",label:"Disponibilidad",type:"select",initialValue:String(plan.active),options:[{value:"true",label:"Activo para nuevas solicitudes"},{value:"false",label:"Inactivo"}]}]});if(!values)return;await action(`/v1/admin/commercial/plans/${plan.id}`,"PATCH",{...values,active:values.active==="true",currency:"USD",defaultWeight:plan.defaultWeight??1,allowedPlacements:[values.placement],sortOrder:plan.sortOrder??0},"Plan actualizado.")}
  async function editSettings(){const values=await dialog.open({eyebrow:"PARAMETRIZACIÓN",title:"Configuración comercial",description:"Estos valores se aplican sin publicar una nueva versión de la aplicación.",confirmLabel:"Guardar configuración",fields:[{name:"invitationDays",label:"Vigencia de invitaciones (días)",type:"number",required:true,min:1,max:30,initialValue:data.invitationDays},{name:"maxActivePerZone",label:"Máximo de campañas activas por zona",type:"number",required:true,min:1,max:100,initialValue:data.maxActivePerZone},{name:"maxImageMb",label:"Tamaño máximo de imagen (MB)",type:"number",required:true,min:.1,max:5,step:.1,initialValue:Number(data.maxImageBytes??1048576)/1_000_000},{name:"bannerWidth",label:"Ancho recomendado (px)",type:"number",required:true,min:320,max:4000,initialValue:data.bannerWidth},{name:"bannerHeight",label:"Alto recomendado (px)",type:"number",required:true,min:100,max:2000,initialValue:data.bannerHeight},{name:"commercialEmails",label:"Correos comerciales separados por coma",type:"textarea",initialValue:(data.commercialEmails??[]).join(", ")}]});if(!values)return;await action("/v1/admin/commercial/settings","PATCH",{invitationDays:Number(values.invitationDays),maxActivePerZone:Number(values.maxActivePerZone),maxImageBytes:Math.round(Number(values.maxImageMb)*1_000_000),bannerWidth:Number(values.bannerWidth),bannerHeight:Number(values.bannerHeight),commercialEmails:String(values.commercialEmails??"").split(",").map(value=>value.trim()).filter(Boolean)},"Configuración comercial actualizada.")}
  async function editPaymentMethod(method:any){const values=await dialog.open({eyebrow:"FORMA DE PAGO",title:`Configurar ${method.name}`,description:method.code==="BANK_TRANSFER"?"Incluye aquí los datos bancarios y las instrucciones que se enviarán por correo al comercio.":"El comercio solo verá los métodos activos definidos por Costa-Go.",confirmLabel:"Guardar método",fields:[{name:"name",label:"Nombre",required:true,minLength:2,initialValue:method.name},{name:"instructions",label:method.code==="BANK_TRANSFER"?"Datos bancarios e instrucciones":"Instrucciones",type:"textarea",initialValue:method.instructions??""},{name:"requiresProof",label:"Comprobante",type:"select",initialValue:String(method.requiresProof),options:[{value:"true",label:"Requerido"},{value:"false",label:"No requerido"}]},{name:"active",label:"Estado",type:"select",initialValue:String(method.active),options:[{value:"true",label:"Activo"},{value:"false",label:"Inactivo"}]},{name:"sortOrder",label:"Orden",type:"number",min:0,max:9999,initialValue:method.sortOrder??0}]});if(!values)return;await action(`/v1/admin/commercial/payment-methods/${method.id}`,"PATCH",{name:values.name,instructions:values.instructions??"",requiresProof:values.requiresProof==="true",active:values.active==="true",sortOrder:Number(values.sortOrder??0)},"Método de pago actualizado.")}
  async function action(path:string,method:string,body:any,message:string){setBusy(true);try{await apiFetch(path,token,{method,body:JSON.stringify(body)});setSuccess(message);setError("");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo completar la operación.");}finally{setBusy(false)}}
  async function openProof(payment:any){setBusy(true);try{const response=await fetch(apiUrl(`/v1/admin/commercial/payments/${payment.id}/proof`),{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw new Error("No se pudo abrir el comprobante.");const url=URL.createObjectURL(await response.blob());window.open(url,"_blank","noopener,noreferrer");window.setTimeout(()=>URL.revokeObjectURL(url),60_000);}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo abrir el comprobante.");}finally{setBusy(false)}}
  const rows=Array.isArray(data)?data:[];
  return <div className="commercial-module">
    {dialog.modal}
    {paymentOrder&&<div className="commercial-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)setPaymentOrder(null)}}><section className="commercial-payment-modal" role="dialog" aria-modal="true" aria-labelledby="commercial-payment-title"><button className="commercial-modal-close" type="button" aria-label="Cerrar" disabled={busy} onClick={()=>setPaymentOrder(null)}>×</button><span className="eyebrow">COBRO AUDITABLE</span><h2 id="commercial-payment-title">Registrar cobro</h2><p>Orden <strong>{paymentOrder.code}</strong> · {paymentOrder.businessName}</p><div className="commercial-payment-summary"><span>Valor exacto de la orden</span><strong>{money(paymentOrder.amount,paymentOrder.currency)}</strong></div><label>Método<select value={paymentMethod} onChange={event=>{setPaymentMethod(event.target.value as "CASH"|"BANK_TRANSFER");setPaymentProof(null);setPaymentReference("")}}><option value="CASH">Efectivo</option><option value="BANK_TRANSFER">Transferencia</option></select></label>{paymentMethod==="BANK_TRANSFER"&&<><label>Referencia<input value={paymentReference} maxLength={160} onChange={event=>setPaymentReference(event.target.value)} placeholder="Número o referencia de la transferencia"/></label><label>Comprobante<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={event=>setPaymentProof(event.target.files?.[0]??null)}/><small>Imagen o PDF legible, máximo 5 MB.</small></label></>}<div className="commercial-modal-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>setPaymentOrder(null)}>Cancelar</button><button className="primary" type="button" disabled={busy||(paymentMethod==="BANK_TRANSFER"&&(!paymentReference.trim()||!paymentProof))} onClick={()=>void registerPayment()}>{busy?"Registrando…":"Confirmar recepción"}</button></div><small className="commercial-audit-note">Este paso registra “Pago recibido”. La orden solo será Pagada después de la conciliación de Finanzas.</small></section></div>}
    <section className="card commercial-hero"><div><span className="eyebrow">PUBLICIDAD Y VENTAS</span><h2>Gestión comercial Costa-Go</h2><p>Prospectos, comercios, campañas, pagos y métricas en una sola fuente de verdad.</p></div><a className="primary commercial-public-link" href="https://costa-go.com/anunciarme" target="_blank" rel="noreferrer">Ver portal público</a></section>
    <nav className="commercial-tabs" aria-label="Módulo comercial">{tabs.filter(item=>can(tabPermission[item.id])).map(item=><button type="button" key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}>{item.label}</button>)}</nav>
    {(error||success)&&<div className={`alert ${error?"error":"success"}`}>{error||success}</div>}
    {tab!=="dashboard"&&tab!=="plans"&&tab!=="settings"&&tab!=="cash"&&<section className="card commercial-filters"><label>Buscar{["leads","advertisers"].includes(tab)?<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Nombre, contacto o correo"/>:<span className="filter-placeholder">Usa el estado para filtrar</span>}</label><label>Estado<select value={filter} onChange={event=>setFilter(event.target.value)}><option value="ALL">Todos</option>{Object.entries(statusLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="secondary" type="button" disabled={busy} onClick={()=>void load()}>Aplicar filtros</button>{tab==="leads"&&can("commercial:leads:manage")&&<button className="primary" type="button" disabled={busy} onClick={()=>void createLead()}>+ Nuevo prospecto</button>}</section>}
    {busy&&!data?<div className="commercial-loading"><span/><span/><span/></div>:null}
    {tab==="dashboard"&&data&&<div className="commercial-kpis">{[["Nuevos prospectos",data.newLeads],["Solicitan asesor",data.requiresContact],["Órdenes abiertas",data.openOrders],["Campañas por revisar",data.pendingCampaigns],["Campañas activas",data.activeCampaigns],["Comercios activos",data.activeAdvertisers],["Ventas del mes",money(data.monthlySales)]].map(([label,value])=><article className="card" key={String(label)}><span>{label}</span><strong>{String(value??0)}</strong></article>)}</div>}
    {tab==="leads"&&(rows.length?<Table headers={["Código","Negocio","Contacto","Origen","Estado","Creado","Acciones"]} rows={rows.map(item=>[item.code,<><strong>{item.businessName}</strong><small>{item.businessType} · {item.city}</small></>,<><span>{item.contactName}</span><small>{item.email} · {item.phone}</small></>,sourceLabel[item.source]??item.source,<Badge value={item.status}/>,date(item.createdAt),<div className="table-actions">{!item.assignedCommercialId&&<button onClick={()=>void action(`/v1/admin/commercial/leads/${item.id}/claim`,"POST",{},"Prospecto asignado a tu gestión.")}>Tomar prospecto</button>}<button onClick={()=>void updateLead(item)}>Seguimiento</button><button onClick={()=>void invite(item)}>Invitar</button></div>])}/>:<Empty>No existen prospectos con estos filtros.</Empty>)}
    {tab==="advertisers"&&(rows.length?<Table headers={["Comercio","Contacto","Ciudad","Tipo","Estado","Comercial"]} rows={rows.map(item=>[item.businessName,<><span>{item.contactName}</span><small>{item.email} · {item.phone}</small></>,item.city,item.businessType,<Badge value={item.status}/>,item.assignedCommercial??"Sin asignar"])}/>:<Empty>No hay comercios registrados.</Empty>)}
    {tab==="orders"&&(rows.length?<Table headers={["Orden","Comercio","Plan","Valor","Estado","Inicio","Creada","Acción"]} rows={rows.map(item=>[item.code,item.businessName,item.planName,money(item.amount,item.currency),<><Badge value={item.status}/>{item.settlementStatus&&item.settlementStatus!=="NOT_RECEIVED"&&<small>{statusLabel[item.settlementStatus]??item.settlementStatus}</small>}</>,date(item.requestedStartAt),date(item.createdAt),can("commercial:orders:manage")&&["PENDING_PAYMENT","PAYMENT_REVIEW"].includes(item.status)&&!["RECEIVED","APPROVED"].includes(item.paymentStatus)?<button type="button" onClick={()=>openPayment(item)}>Registrar cobro</button>:"—"])}/>:<Empty>No existen órdenes comerciales.</Empty>)}
    {tab==="payments"&&(rows.length?<Table headers={["Orden","Comercio","Método","Valor","Estado","Conciliación","Recibido por","Comprobante","Acciones"]} rows={rows.map(item=>[item.orderCode,item.businessName,item.paymentMethod,money(item.amount,item.currency),<Badge value={item.status}/>,<Badge value={item.settlementStatus??"NOT_RECEIVED"}/>,item.receivedBy?<><span>{item.receivedBy}</span><small>{date(item.receivedAt)}</small></>:"Registro web",item.proofMime?<button className="link" type="button" onClick={()=>void openProof(item)}>Ver archivo</button>:"Sin archivo",can("commercial:payments:review")&&["PENDING","RECEIVED","UNDER_REVIEW"].includes(item.status)&&item.settlementStatus!=="PENDING_CLOSURE"&&item.paymentMethod==="Transferencia bancaria"&&item.proofMime?<div className="table-actions"><button onClick={()=>void reviewPayment(item,"APPROVE")}>Conciliar</button><button className="danger-link" onClick={()=>void reviewPayment(item,"REJECT")}>Rechazar</button></div>:"—"])}/>:<Empty>No hay pagos registrados.</Empty>)}
    {tab==="cash"&&data&&<div className="commercial-cash-grid"><section className="card"><div className="commercial-section-title"><div><span className="eyebrow">CAJA COMERCIAL</span><h2>Jornadas pendientes de cierre</h2></div></div>{data.unclosed?.length?<Table headers={["Jornada","Cobros","Total","Acción"]} rows={data.unclosed.map((item:any)=>[new Date(`${item.businessDate}T12:00:00`).toLocaleDateString("es-EC"),item.paymentCount,money(item.total),can("commercial:orders:manage")?<button type="button" onClick={()=>void closeCash(item)}>Cerrar caja</button>:"—"])}/>:<Empty>No hay efectivo pendiente de cierre.</Empty>}</section><section className="card"><div className="commercial-section-title"><div><span className="eyebrow">FINANZAS</span><h2>Cierres y conciliación</h2></div></div>{data.closures?.length?<Table headers={["Fecha","Comercial","Cobros","Total","Estado","Acciones"]} rows={data.closures.map((item:any)=>[new Date(`${item.businessDate}T12:00:00`).toLocaleDateString("es-EC"),item.commercial,item.paymentCount,money(item.total,item.currency),<Badge value={item.status}/>,can("commercial:payments:review")&&item.status==="PENDING_RECONCILIATION"?<div className="table-actions"><button onClick={()=>void reviewClosure(item,"RECONCILE")}>Conciliar</button><button className="danger-link" onClick={()=>void reviewClosure(item,"REJECT")}>Rechazar</button></div>:item.reconciliationReference??"—"])}/>:<Empty>No existen cierres comerciales.</Empty>}</section></div>}
    {tab==="campaigns"&&(rows.length?<Table headers={["Campaña","Comercio","Estado","Vigencia","Resultados","Acciones"]} rows={rows.map(item=>[item.title,item.advertiserName,<Badge value={item.status}/>,<><span>{date(item.startsAt)}</span><small>hasta {date(item.endsAt)}</small></>,<><span>{item.impressions} impresiones</span><small>{item.clicks} clics</small></>,<div className="table-actions"><a className="table-button" href={apiUrl(`/v1/banners/${item.id}/image`)} target="_blank" rel="noreferrer">Ver pieza</a>{can("commercial:campaigns:review")&&item.status==="PENDING_REVIEW"&&<><button onClick={()=>void campaignAction(item,"APPROVE")}>Aprobar</button><button onClick={()=>void campaignAction(item,"REQUEST_CORRECTION")}>Corregir</button><button className="danger-link" onClick={()=>void campaignAction(item,"REJECT")}>Rechazar</button></>}{can("commercial:campaigns:manage")&&item.status==="ACTIVE"&&<button onClick={()=>void campaignAction(item,"PAUSE")}>Pausar</button>}{can("commercial:campaigns:manage")&&item.status==="PAUSED"&&<button onClick={()=>void campaignAction(item,"RESUME")}>Reanudar</button>}</div>])}/>:<Empty>No existen campañas con este estado.</Empty>)}
    {tab==="plans"&&<section className="card"><div className="commercial-section-title"><div><span className="eyebrow">CATÁLOGO PARAMETRIZABLE</span><h2>Planes publicitarios</h2></div>{can("commercial:plans:manage")&&<button className="primary" onClick={()=>void createPlan()}>+ Nuevo plan</button>}</div>{rows.length?<div className="commercial-plan-grid">{rows.map(item=><article key={item.id}><div><span>{item.code}</span><Badge value={item.active?"ACTIVE":"INACTIVE"}/></div><h3>{item.name}</h3><strong>{money(item.price,item.currency)}</strong><p>{item.durationDays} días · {item.description||"Sin descripción"}</p>{can("commercial:plans:manage")&&<button className="secondary" type="button" onClick={()=>void editPlan(item)}>Editar plan</button>}</article>)}</div>:<Empty>No existen planes publicitarios.</Empty>}</section>}
    {tab==="settings"&&data&&<section className="card"><div className="commercial-section-title"><div><span className="eyebrow">CONFIGURACIÓN</span><h2>Reglas comerciales</h2></div><button className="primary" type="button" onClick={()=>void editSettings()}>Editar configuración</button></div><div className="commercial-kpis"><article className="card"><span>Vigencia de invitación</span><strong>{data.invitationDays} días</strong></article><article className="card"><span>Campañas por zona</span><strong>{data.maxActivePerZone}</strong></article><article className="card"><span>Banner recomendado</span><strong>{data.bannerWidth} × {data.bannerHeight}</strong></article><article className="card"><span>Tamaño máximo</span><strong>{(Number(data.maxImageBytes)/1_000_000).toFixed(1)} MB</strong></article></div><div className="commercial-section-title"><div><span className="eyebrow">COBRO</span><h2>Métodos de pago</h2></div></div><div className="commercial-plan-grid">{(data.paymentMethods??[]).map((method:any)=><article key={method.id}><div><span>{method.code}</span><Badge value={method.active?"ACTIVE":"INACTIVE"}/></div><h3>{method.name}</h3><p>{method.instructions||"Sin instrucciones"}</p><small>{method.requiresProof?"Requiere comprobante":"No requiere comprobante"}</small><button className="secondary" type="button" onClick={()=>void editPaymentMethod(method)}>Configurar</button></article>)}</div></section>}
  </div>
}
