import {useEffect,useState,type ComponentType} from 'react';
import {apiFetch} from './api';
import {dateRange,ecuDate,navigateConsole,usd} from './console-model';
import {ConsoleIcon,ErrorState,LoadingState,MetricStrip,useConsoleState} from './console-ui';
import {MototaxiIcon} from './mototaxi-icon';

export function ConsoleHome({token,name,can,cooperative,Detail,Map}:{token:string;name:string;can:(p:string)=>boolean;cooperative:boolean;Detail:ComponentType<any>;Map:ComponentType<any>}) {
  const [period,setPeriod]=useConsoleState('period','today'),[range,setRange]=useConsoleState('range',dateRange('today'));
  const [data,setData]=useState<Record<string,any>>({}),[busy,setBusy]=useState(true),[errors,setErrors]=useState<string[]>([]),[revision,setRevision]=useState(0),[detail,setDetail]=useState<any>();
  const query=new URLSearchParams({from:new Date(range.from+'T00:00:00-05:00').toISOString(),to:new Date(new Date(range.to+'T00:00:00-05:00').getTime()+86400000).toISOString(),tripType:'ALL'}).toString();
  useEffect(()=>{
    const controller=new AbortController();setBusy(true);setErrors([]);setData({});
    const sources:[string,string][]=[];
    if(cooperative)sources.push(['cooperative','/v1/admin/cooperative-dashboard/overview']);
    else {
      if(can('dashboard:view')&&(can('trips:view')||can('drivers:view')))sources.push(['analytics','/v1/admin/dashboard?'+query]);
      if(can('operations:view'))sources.push(['operations','/v1/admin/operations']);
      if(can('memberships:view')&&(can('memberships:manage')||!can('payments:collect')))sources.push(['memberships','/v1/admin/memberships/dashboard']);
      if(can('commercial:dashboard'))sources.push(['commercial','/v1/admin/commercial/dashboard']);
      if(can('payments:transfer_review'))sources.push(['transfers','/v1/admin/membership-payments/pending']);
      if(can('payments:view_own_point')&&!can('memberships:manage'))sources.push(['collector','/v1/collector/me'],['collectorPending','/v1/collector/payments/pending-closure']);
      if(can('FACTURACION_DASHBOARD_VER'))sources.push(['fiscal','/v1/admin/fiscal/dashboard?'+new URLSearchParams({start:range.from,end:range.to})]);
      if(can('database:view'))sources.push(['database','/v1/admin/database']);
    }
    void Promise.all(sources.map(async([key,path])=>{try{const value=await apiFetch(path,token,{signal:controller.signal});if(!controller.signal.aborted)setData(previous=>({...previous,[key]:value}));}catch{if(!controller.signal.aborted)setErrors(previous=>[...previous,`No se pudo cargar ${({analytics:'estadísticas',operations:'operación',memberships:'membresías',commercial:'comercial',transfers:'comprobantes',database:'base de datos',cooperative:'tu cooperativa',collector:'tu punto de cobro',collectorPending:'cierres pendientes',fiscal:'finanzas'} as Record<string,string>)[key]}.`]);}})).finally(()=>{if(!controller.signal.aborted)setBusy(false);});
    return()=>controller.abort();
  },[token,query,revision,cooperative]);
  const metrics:any[]=[],m=data.analytics?.metrics,selectedPeriod=period==='today'?'Hoy':period==='week'?'Últimos 7 días':period==='month'?'Mes actual':'Período seleccionado';
  const analytics=(key:string,label:string,tone?:string)=>{if(m&&m[key]!=null)metrics.push({label,value:m[key],tone,hint:['connectedDrivers','openIncidents'].includes(key)?'Estado actual':selectedPeriod,onClick:()=>setDetail({metric:key,title:label})});};
  if(can('trips:view')){analytics('requestedTrips','Viajes solicitados');analytics('completedTrips','Viajes completados','positive');analytics('withoutDriver','Sin conductor encontrado','warning');}
  if(can('drivers:view'))analytics('connectedDrivers','Conductores conectados','positive');
  if(can('incidents:view'))analytics('openIncidents','Incidentes abiertos','warning');
  if(data.memberships){metrics.push({label:'Membresías por vencer',value:data.memberships.expiring7Days??0,hint:'Próximos 7 días',tone:'warning',onClick:()=>navigateConsole('memberships',{sub:'memberships',insight:'expiring7Days'})});}
  if(data.transfers)metrics.push({label:'Comprobantes pendientes',value:Array.isArray(data.transfers)?data.transfers.length:0,hint:'Esperan revisión',tone:'warning',onClick:()=>navigateConsole('memberships',{sub:'payments'})});
  if(data.commercial){metrics.push({label:'Campañas activas',value:data.commercial.activeCampaigns??0,hint:'Estado actual',onClick:can('commercial:campaigns:view')?()=>navigateConsole('commercial',{sub:'campaigns',status:'ACTIVE'}):undefined},{label:'Ventas publicitarias',value:usd(data.commercial.monthlySales),hint:'Mes calendario actual · pagadas',tone:'positive',onClick:can('commercial:orders:view')?()=>navigateConsole('commercial',{sub:'orders',status:'INSIGHT:monthSales'}):undefined},{label:'Solicitan asesor',value:data.commercial.requiresContact??0,hint:'Estado actual',onClick:can('commercial:leads:view')?()=>navigateConsole('commercial',{sub:'leads',status:'REQUIRES_CONTACT'}):undefined});}
  if(data.cooperative){const c=data.cooperative.cooperative??{};for(const [key,label] of [['totalDrivers','Conductores de tu cooperativa'],['connectedDrivers','Conductores conectados'],['tripsThisMonth','Viajes del mes'],['completedTrips','Completados']])metrics.push({label,value:c[key!]??0,onClick:()=>navigateConsole('dashboard'),hint:c.name});}
  if(data.fiscal){metrics.push({label:'Recaudación confirmada',value:usd(data.fiscal.collected),hint:selectedPeriod,tone:'positive',onClick:can('FACTURACION_VER')?()=>navigateConsole('fiscal',{sub:'payments',start:range.from,end:range.to,status:'COLLECTED'}):undefined},{label:'Pendiente de facturar',value:usd(data.fiscal.pendingAmount),hint:selectedPeriod,onClick:can('FACTURACION_VER')?()=>navigateConsole('fiscal',{sub:'payments',start:range.from,end:range.to,status:'UNBILLED'}):undefined});}
  if(data.collector){metrics.push({label:'Puntos asignados',value:data.collector.points?.length??0,hint:'Tu asignación vigente',onClick:()=>navigateConsole('memberships')});}
  if(Array.isArray(data.collectorPending)){metrics.push({label:'Cobros sin cierre',value:data.collectorPending.length,hint:'Tus puntos autorizados',onClick:()=>navigateConsole('memberships')},{label:'Efectivo por cerrar',value:usd(data.collectorPending.reduce((sum:number,p:any)=>sum+Number(p.amount??0),0)),hint:'Pendiente de cierre',onClick:()=>navigateConsole('memberships')});}
  const trend=data.analytics?.tripsByDay??[],maximum=Math.max(1,...trend.map((r:any)=>Number(r.requested)));
  const points=trend.map((r:any,i:number)=>`${30+i*540/Math.max(1,trend.length-1)},${160-Number(r.requested)*130/maximum}`).join(' ');
  const actions=[['trips','Viajes','Consulta solicitudes y tarifas','trips:view','trips'],['drivers','Conductores','Revisa habilitantes y aprobaciones','drivers:view','users'],['memberships','Membresías y cobranzas','Vigencia, pagos y puntos','memberships:view','money'],['fiscal','Finanzas','Documentos y clientes fiscales','FACTURACION_VER','document'],['commercial','Comercial','Prospectos, ventas y campañas','commercial:dashboard','chart'],['incidents','Soporte','Atiende solicitudes e incidencias','incidents:view','support'],['fleet','Mototaxis','Unidades y jornadas','fleet:view','shield']].filter(item=>can(item[3]!));
  return <div className="cg-home"><section className="cg-welcome"><div><span className="eyebrow">CENTRO DE CONTROL · {name}</span><h1>Bienvenido al portal de Costa-Go</h1><p>Controla viajes, conductores, cobranzas, finanzas y operación desde un solo lugar.</p></div><div className="cg-coast" aria-hidden="true"><i className="cg-sun"/><i className="cg-wave"/><i className="cg-wave second"/><svg className="cg-palm" viewBox="0 0 90 110"><path d="M40 105Q60 60 45 30" stroke="currentColor" strokeWidth="7" fill="none"/><path d="M45 30Q15 0 2 34Q25 18 45 30M45 30Q25 38 20 60Q25 30 45 30M45 30Q65 0 86 20Q65 16 45 30M45 30Q80 25 88 55Q66 35 45 30M45 30Q33 0 52 2Q45 15 45 30" fill="currentColor"/></svg><div className="cg-coast-vehicle"><MototaxiIcon size={110}/></div></div></section>
    <div className="cg-period"><div><strong>Resumen de tu operación</strong><small>Solo datos y accesos autorizados para tu cuenta</small></div><label>Período de viajes<select value={period} onChange={e=>{setPeriod(e.target.value);if(e.target.value!=='custom')setRange(dateRange(e.target.value));}}><option value="today">Hoy</option><option value="week">Últimos 7 días</option><option value="month">Mes actual</option><option value="custom">Personalizado</option></select></label>{period==='custom'&&<><label>Desde<input type="date" value={range.from} max={range.to} onChange={e=>{if(e.target.value&&e.target.value<=range.to)setRange({...range,from:e.target.value});}}/></label><label>Hasta<input type="date" value={range.to} min={range.from} onChange={e=>{if(e.target.value&&e.target.value>=range.from)setRange({...range,to:e.target.value});}}/></label></>}</div>
    {errors.length>0&&<ErrorState message={errors.join(' ')} onRetry={()=>setRevision(v=>v+1)}/>}{busy&&<LoadingState/>}
    {!busy&&<><MetricStrip items={metrics.slice(0,6)}/>{metrics.length>6&&<details className="cg-insights"><summary>Más indicadores de gestión ({metrics.length-6})</summary><MetricStrip items={metrics.slice(6)}/></details>}{metrics.length===0&&!errors.length&&<section className="card"><h2>Tu espacio de trabajo está listo</h2><p>Accede a los módulos habilitados abajo. No existen estadísticas agregadas autorizadas para esta cuenta.</p></section>}
    <div className="cg-home-grid">{data.fiscal&&<section className="card"><div className="cg-section-title"><h2>Recaudación por fecha</h2><button className="link" onClick={()=>navigateConsole('fiscal',{sub:'dashboard',start:range.from,end:range.to})}>Ver finanzas →</button></div><p className="muted">{selectedPeriod} · pagos confirmados, no facturas autorizadas</p>{data.fiscal.collectedByDay?.length?data.fiscal.collectedByDay.map((r:any)=><div className="fiscal-chart-row" key={r.label}><span>{ecuDate(r.label+'T12:00:00-05:00',false)}</span><strong>{usd(r.value)}</strong><meter aria-label={'Recaudación '+r.label} min={0} max={Math.max(...data.fiscal.collectedByDay.map((v:any)=>Number(v.value)),1)} value={Number(r.value)}/></div>):<div className="empty">No hay cobros confirmados en este período.</div>}</section>}{data.analytics&&<section className="card cg-trend"><div className="cg-section-title"><h2>Tendencia de viajes</h2><button className="link" onClick={()=>navigateConsole('dashboard')}>Ver análisis →</button></div><p className="muted">{selectedPeriod} · solicitudes registradas</p>{trend.length?<><svg viewBox="0 0 600 195" role="img" aria-label="Solicitudes de viaje por día"><path d="M30 30H570M30 95H570M30 160H570" stroke="var(--cg-border)" fill="none"/>{trend.length>1&&<polygon points={`30,160 ${points} 570,160`} fill="var(--cg-soft)"/>}<polyline points={points} fill="none" stroke="var(--cg-primary)" strokeWidth="3"/>{trend.map((r:any,i:number)=><circle key={r.day} cx={trend.length===1?300:30+i*540/Math.max(1,trend.length-1)} cy={160-Number(r.requested)*130/maximum} r="4" fill="var(--cg-primary)"><title>{ecuDate(r.day,false)}: {r.requested} solicitudes</title></circle>)}</svg><div className="cg-trend-values"><span>{ecuDate(range.from+'T12:00:00-05:00',false)}</span><strong>{m?.requestedTrips??0} solicitudes</strong><span>{ecuDate(range.to+'T12:00:00-05:00',false)}</span></div><details><summary>Consultar valores por fecha</summary>{trend.map((r:any)=><p key={r.day}>{ecuDate(r.day,false)} · {r.requested} solicitudes</p>)}</details></>:<div className="empty">No hay viajes en este período.</div>}</section>}
    {data.operations&&<section className="card cg-home-map"><div className="cg-section-title"><h2>Cobertura operativa</h2><button className="link" onClick={()=>navigateConsole('operations')}>Abrir operación →</button></div><p className="muted">Posiciones reportadas y solicitudes actuales</p><Map drivers={data.operations.driverLocations??[]} trips={data.operations.activeTrips??[]}/></section>}
    <section className="card"><h2>Accesos de tu rol</h2><div className="cg-quick-actions">{actions.map(([module,label,description,,icon])=><button key={module} onClick={()=>navigateConsole(module!)}><ConsoleIcon name={icon}/><strong>{label}</strong><small>{description}</small></button>)}</div></section>
    {data.analytics?.origins?.length>0&&<section className="card"><h2>Orígenes con mayor demanda</h2><div className="cg-ranked">{data.analytics.origins.slice(0,5).map((row:any,i:number)=><button key={i} onClick={()=>navigateConsole('trips',{q:row.label,from:range.from,to:range.to})}><span>{i+1}</span><strong>{row.label}</strong><em>{row.value} viajes</em></button>)}</div></section>}
    {data.operations&&<section className="card"><h2>Actividad operativa reciente</h2>{data.operations.activeTrips?.length?<div className="cg-activity">{data.operations.activeTrips.slice(0,5).map((trip:any)=><button key={trip.id} onClick={()=>navigateConsole('trips',{record:trip.id})}><ConsoleIcon name="trips"/><span><strong>{trip.passenger}</strong><small>{trip.origin} → {trip.destination}</small><small>{ecuDate(trip.requestedAt)}</small></span><ConsoleIcon name="arrow" size={15}/></button>)}</div>:<div className="empty">No hay solicitudes activas.</div>}</section>}
    </div><section className="card cg-services"><h2>Estado de servicios</h2><p><ConsoleIcon name="database"/> Base de datos: <strong>{data.database?(data.database.connected?'Conexión verificada':'Sin conexión'):'Sin verificación autorizada en esta vista'}</strong></p><small>La conexión de la API se comprueba en el encabezado. Notificaciones, almacenamiento, respaldos y colas no tienen una sonda de salud consolidada; no se presume que estén operativos.</small></section></>}
    {detail&&<Detail token={token} selection={detail} query={query} onClose={()=>setDetail(undefined)}/>}
  </div>;
}
