import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {apiFetch,type Session} from './api';
import {consoleDescriptions,consoleGroups,ecuDate,navigateConsole,normalizeSearch,subNavigation} from './console-model';
import {ConsoleIcon,ConsoleModal,ErrorState,LoadingState} from './console-ui';
import {MototaxiIcon} from './mototaxi-icon';

const iconFor:Record<string,string>={home:'home',dashboard:'chart',operations:'map',alerts:'alert',trips:'trips',drivers:'users',passengers:'users',cooperatives:'shield',memberships:'money',fiscal:'document',commercial:'chart',advertising:'document',notifications:'bell',pricing:'money',zones:'map',settings:'settings',incidents:'support',access:'shield',audit:'document',database:'database'};
export function ConsoleLayout({session,current,labels,visible,can,roleLabel,onNavigate,onLogout,onRefresh,children}:{session:Session;current:string;labels:Record<string,string>;visible:string[];can:(p:string)=>boolean;roleLabel:string;onNavigate:(module:string,params?:Record<string,string>)=>void;onLogout:()=>void;onRefresh:()=>void;children:ReactNode}) {
  const key=`cg:nav:${session.user.id??session.user.email}`;
  const read=(suffix:string)=>{try{return JSON.parse(localStorage.getItem(key+suffix)??'[]') as string[];}catch{return [];}};
  const write=(key:string,value:string)=>{try{localStorage.setItem(key,value);}catch{}};
  const [expanded,setExpanded]=useState(()=>{try{return localStorage.getItem('cg:sidebar')!=='compact';}catch{return true;}}),[mobile,setMobile]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState<any[]>([]),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState(''),[retry,setRetry]=useState(0),[closed,setClosed]=useState<string[]>([]),[favorites,setFavorites]=useState<string[]>(()=>read(':favorites')),[recent,setRecent]=useState<string[]>(()=>read(':recent')),[health,setHealth]=useState<'checking'|'ok'|'retrying'|'error'>('checking'),[checkedAt,setCheckedAt]=useState<string>(),[notifications,setNotifications]=useState<any[]>([]),[showNotifications,setShowNotifications]=useState(false),[notificationError,setNotificationError]=useState('');
  const healthFailures=useRef(0);
  const closeSearch=useCallback(()=>setSearch(false),[]),closeNotifications=useCallback(()=>setShowNotifications(false),[]);
  useEffect(()=>{const next=[current,...read(':recent').filter(item=>item!==current)].slice(0,5);setRecent(next);write(key+':recent',JSON.stringify(next));setMobile(false);},[current,key]);
  useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(value=>!value);}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);
  useEffect(()=>{const controller=new AbortController();healthFailures.current=0;setHealth('checking');const check=()=>{void apiFetch<any>('/health?consoleHealth=1',undefined,{signal:controller.signal,cache:'no-store'}).then(result=>{if(!controller.signal.aborted){healthFailures.current=0;setHealth(result.status==='ok'?'ok':'retrying');setCheckedAt(new Date().toISOString());}}).catch(()=>{if(!controller.signal.aborted){healthFailures.current+=1;setHealth(healthFailures.current>=3?'error':'retrying');}});};check();const timer=setInterval(check,15000);return()=>{controller.abort();clearInterval(timer);};},[retry]);
  // Existing notification feed is global; only global operations administrators see it.
  const notificationAccess=can('dashboard:view')&&can('drivers:approve')&&can('alerts:view');
  useEffect(()=>{if(!notificationAccess)return;let active=true;const load=()=>{void apiFetch<any[]>('/v1/admin/notifications',session.token).then(rows=>{if(active){setNotifications(rows);setNotificationError('');}}).catch(()=>{if(active)setNotificationError('No se pudieron cargar los avisos.');});};load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer);};},[session.token,notificationAccess,retry]);
  useEffect(()=>{if(!search||query.trim().length<2){setResults([]);setSearchError('');setSearching(false);return;}const controller=new AbortController();setSearching(true);setResults([]);const timer=setTimeout(()=>{void apiFetch<any>('/v1/admin/console/search?q='+encodeURIComponent(query.trim()),session.token,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted){setResults(data.results);setSearchError('');}}).catch(()=>{if(!controller.signal.aborted)setSearchError('La búsqueda no está disponible. Puedes seguir usando los accesos a módulos.');}).finally(()=>{if(!controller.signal.aborted)setSearching(false);});},300);return()=>{controller.abort();clearTimeout(timer);};},[query,search,session.token,retry]);
  const go=(module:string,params?:Record<string,string>)=>{onNavigate(module,params);setSearch(false);setMobile(false);};
  const toggleFavorite=()=>{const next=favorites.includes(current)?favorites.filter(x=>x!==current):[...favorites,current];setFavorites(next);write(key+':favorites',JSON.stringify(next));};
  const moduleMatches=visible.filter(item=>normalizeSearch(labels[item]+' '+consoleDescriptions[item]).includes(normalizeSearch(query)));
  const group=consoleGroups.find(g=>g.modules.includes(current));
  const navButton=(module:string)=><button key={module} type="button" className={current===module?'active':''} title={labels[module]} aria-current={current===module?'page':undefined} onClick={()=>go(module)}><span className="cg-nav-icon">{module==='fleet'?<MototaxiIcon size={21}/>:<ConsoleIcon name={iconFor[module]??'document'}/>}</span><span className="cg-nav-label">{labels[module]}</span></button>;
  return <div className={`control-panel ${expanded?'cg-expanded':'cg-compact'} ${mobile?'cg-mobile-open':''}`}><a className="cg-skip" href="#console-content">Saltar al contenido</a><aside className="cg-sidebar" aria-label="Navegación principal"><div className="cg-sidebar-brand"><button className="cg-icon-button" title={expanded?'Contraer menú':'Expandir menú'} aria-label={expanded?'Contraer menú':'Expandir menú'} onClick={()=>{setExpanded(!expanded);write('cg:sidebar',expanded?'compact':'expanded');}}><ConsoleIcon name="menu"/></button><img src="/costa-go-emblem.png" alt="Costa-Go"/><div><strong>Costa-<em>Go</em></strong><small>Centro de control</small></div></div><nav className="cg-nav">{favorites.some(item=>visible.includes(item))&&<div className="cg-nav-group"><span className="cg-group-label">Favoritos</span>{favorites.filter(item=>visible.includes(item)).map(navButton)}</div>}{consoleGroups.map(g=>{const items=g.modules.filter(item=>visible.includes(item));if(!items.length)return null;const open=g.modules.includes(current)||!closed.includes(g.label);return <div className="cg-nav-group" key={g.label}><button className="cg-group-toggle" aria-expanded={open} onClick={()=>setClosed(open?[...closed,g.label]:closed.filter(x=>x!==g.label))}><span>{g.label}</span><small>{open?'−':'+'}</small></button>{(open||!expanded)&&items.map(navButton)}</div>;})}</nav><div className="cg-sidebar-profile"><div className="cg-avatar">{session.user.name.slice(0,1)}</div><span><strong>{session.user.name}</strong><small>{roleLabel}</small></span><button onClick={onLogout} title="Cerrar sesión"><ConsoleIcon name="logout"/><span>Cerrar sesión</span></button></div></aside>{mobile&&<button className="cg-scrim" aria-label="Cerrar menú" onClick={()=>setMobile(false)}/>}
    <main className="cg-main"><header className="cg-global-header"><button className="cg-mobile-toggle cg-icon-button" aria-label="Abrir menú" onClick={()=>setMobile(true)}><ConsoleIcon name="menu"/></button><button className={`cg-health ${health}`} title={`Estado independiente de la API. ${checkedAt?'Última respuesta correcta '+ecuDate(checkedAt):'Comprobando disponibilidad'}`} onClick={()=>setRetry(v=>v+1)}><i/>{health==='ok'?'API conectada':health==='error'?'API no disponible':health==='retrying'?'Reconectando…':'Verificando API'}</button><button className="cg-global-search" onClick={()=>setSearch(true)}><ConsoleIcon name="search"/><span>Buscar módulos, viajes, usuarios…</span><kbd>Ctrl K</kbd></button><button className="cg-icon-button" title="Actualizar datos de la vista" aria-label="Actualizar datos" onClick={()=>{onRefresh();setRetry(v=>v+1);}}><ConsoleIcon name="refresh"/></button>{notificationAccess&&<button className="cg-notification-button cg-icon-button" title="Avisos administrativos" aria-label={`Avisos: ${notifications.filter(n=>n.unread).length} sin leer`} onClick={()=>setShowNotifications(true)}><ConsoleIcon name="bell"/>{notifications.some(n=>n.unread)&&<b>{notifications.filter(n=>n.unread).length}</b>}</button>}<div className="cg-header-user"><span><strong>{session.user.name}</strong><small>{roleLabel}</small></span><div className="cg-avatar">{session.user.name.slice(0,1)}</div></div></header>
    <div className="cg-content" id="console-content"><div className="cg-breadcrumb"><button onClick={()=>go('home')}>Inicio</button><span>/</span><span>{group?.label}</span>{current!=='home'&&<><span>/</span><strong>{labels[current]}</strong></>}<button className={`cg-favorite ${favorites.includes(current)?'selected':''}`} aria-pressed={favorites.includes(current)} onClick={toggleFavorite} title="Guardar módulo como favorito"><ConsoleIcon name="star" size={16}/><span>Favorito</span></button></div>{current!=='home'&&<div className="cg-page-heading"><div><h1>{labels[current]}</h1><p>{consoleDescriptions[current]}</p></div><button className="secondary" onClick={()=>{if(window.history.state?.cgConsole)window.history.back();else go('home');}}><ConsoleIcon name="back" size={16}/> Volver</button></div>}{subNavigation[current]&&<div className="cg-module-links" aria-label="Secciones del módulo">{subNavigation[current].filter(item=>can(item.permission)).map(item=><button key={item.id} onClick={()=>go(current,{sub:item.id})}>{item.label}</button>)}</div>}{children}<footer className="cg-footer"><img src="/costa-go-emblem.png" alt="Costa-Go"/><span>Centro de control · America/Guayaquil</span>{checkedAt&&<small>API comprobada: {ecuDate(checkedAt)}</small>}</footer></div></main>
    {search&&<ConsoleModal title="Buscar en Costa-Go" onClose={closeSearch}><label className="cg-command-input"><ConsoleIcon name="search"/><input aria-label="Buscar módulos y registros" autoFocus value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} placeholder="Nombre, correo, lugar o código de viaje…"/></label><div className="cg-command-results">{!query&&<><h3>Recientes</h3>{recent.filter(item=>visible.includes(item)).map(item=><button key={item} onClick={()=>go(item)}><ConsoleIcon name={iconFor[item]}/><strong>{labels[item]}</strong><small>Reciente</small></button>)}</>}<h3>Módulos</h3>{moduleMatches.map(item=><button key={item} onClick={()=>go(item)}><ConsoleIcon name={iconFor[item]}/><strong>{labels[item]}</strong><ConsoleIcon name="arrow" size={15}/></button>)}{searching&&<LoadingState/>}{searchError&&<ErrorState message={searchError} onRetry={()=>setRetry(v=>v+1)}/>} {results.filter(item=>visible.includes(item.module)).map(item=><button key={item.module+item.id} onClick={()=>go(item.module,{...(item.sub?{sub:item.sub}:{}),...(item.module==='trips'?{record:item.id}:{q:item.query??item.title}),record:item.id})}><ConsoleIcon name={iconFor[item.module]}/><span><strong>{item.title}</strong><small>{labels[item.module]} · {item.subtitle}</small></span><ConsoleIcon name="arrow" size={15}/></button>)}{query.length>=2&&!searching&&!results.length&&!moduleMatches.length&&!searchError&&<p className="empty">Sin coincidencias para los accesos autorizados.</p>}<small>Hasta 6 coincidencias por tipo. Continúa la búsqueda dentro del módulo para ver más resultados.</small></div></ConsoleModal>}
    {showNotifications&&<ConsoleModal title="Avisos administrativos" onClose={closeNotifications}>{notificationError?<ErrorState message={notificationError} onRetry={()=>setRetry(v=>v+1)}/>:notifications.length?<div className="cg-activity">{notifications.slice(0,30).map(n=><article key={n.id}><ConsoleIcon name="bell"/><div><strong>{n.title}</strong><p>{n.body}</p><small>{ecuDate(n.createdAt)}{n.unread?' · Sin leer':''}</small></div></article>)}</div>:<p className="empty">No hay avisos registrados.</p>}</ConsoleModal>}
  </div>;
}
