import {ReferralPrograms} from './referral-programs';
import {useEffect,useState,type FormEvent} from 'react';
import {apiFetch} from './api';
import {ConsoleModal,ConsoleIcon,ManagedTable} from './console-ui';
import {ecuDate} from './console-model';
import './costa-go-campaigns.css';
import {CampaignResources} from './campaign-resources';
import {CostaGoBenefits} from './costa-go-benefits';

type Campaign={headerDecorationMode?:string;useDecorativeAssetForHeader?:boolean;allowLightAssetsInDark?:boolean;allowMainImageInHome?:boolean;benefitCode?:string|null;decorateHeader?:boolean;id?:string;version?:number;internalName:string;title:string;subtitle:string;description:string;audience:string;startsAt:string;endsAt:string;priority:number;allZones:boolean;zoneIds:string[];variant:string;placements:string[];ctaType:string;ctaText:string;ctaDestination:string;terms:string;status?:string;enabled?:boolean;assets?:string[];reviewReason?:string;history?:{action:string;reason:string;createdAt:string;actor:string}[]};
const root='/v1/admin/costa-go-campaigns';
const states:Record<string,string>={DRAFT:'Borrador',PENDING_APPROVAL:'Pendiente de aprobación',APPROVED:'Aprobada',REJECTED:'Rechazada',ACTIVE:'Activa',PAUSED:'Pausada',FINISHED:'Finalizada'};
const audiences:Record<string,string>={PASSENGER:'Pasajeros',DRIVER:'Conductores',BOTH:'Ambos'};
const variants:Record<string,string>={DEFAULT:'Estándar',CHRISTMAS:'Navidad',CARNIVAL:'Carnaval',SUMMER:'Verano',CUSTOM:'Personalizada'};
const placements:Record<string,string>={HOME:'Inicio de la app (Home)',CAMPAIGNS:'Listado contextual de campañas',NOTIFICATION:'Destino de notificaciones'};
const ctas:Record<string,string>={REFERRAL:'Invita y gana (referidos)',NONE:'Sin acción',CAMPAIGN_DETAIL:'Detalle de campaña',MEMBERSHIP:'Membresía (conductores)',SUPPORT:'Ayuda y soporte',INTERNAL_ROUTE:'Pantalla interna',EXTERNAL_URL:'Enlace externo HTTPS'};
const actions=[['SUBMIT','Enviar a aprobación','edit',['DRAFT','REJECTED']],['APPROVE','Aprobar','approve',['PENDING_APPROVAL']],['REJECT','Rechazar','reject',['PENDING_APPROVAL']],['ACTIVATE','Activar / programar','activate',['APPROVED','PAUSED']],['PAUSE','Pausar','deactivate',['ACTIVE']],['FINISH','Finalizar','deactivate',['DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','ACTIVE','PAUSED']]] as const;
const initial=():Campaign=>({internalName:'',title:'',subtitle:'',description:'',audience:'BOTH',startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+7*86400000).toISOString(),priority:0,allZones:true,zoneIds:[],variant:'DEFAULT',placements:['HOME'],ctaType:'NONE',ctaText:'',ctaDestination:'',terms:'',headerDecorationMode:'EDGES',useDecorativeAssetForHeader:false,allowLightAssetsInDark:false,allowMainImageInHome:false});
const localDate=(value:string)=>value?new Date(Date.parse(value)-5*3600000).toISOString().slice(0,16):'';
const isoDate=(value:string)=>value?new Date(value+'-05:00').toISOString():'';
export function CostaGoCampaigns({token,permissions}:{token:string;permissions:string[]}){
  const [files,setFiles]=useState<Record<string,File>>({});
  const [removed,setRemoved]=useState<string[]>([]);
  const [storageReady,setStorageReady]=useState(false);
  const [tab,setTab]=useState('campaigns');
  const [benefits,setBenefits]=useState<{code:string;name:string;audience:string;status:string}[]>([]);
  useEffect(()=>{if(permissions.includes('benefits:view'))void apiFetch<{items:typeof benefits}>('/v1/admin/benefits',token).then(r=>setBenefits(r.items)).catch(()=>{});},[token,tab]);
  const can=(action:string)=>permissions.includes('costa_campaigns:'+action);
  const [rows,setRows]=useState<Campaign[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[search,setSearch]=useState(''),[status,setStatus]=useState('');
  const [zones,setZones]=useState<{id:string;name:string;enabled:boolean}[]>([]),[selected,setSelected]=useState<Campaign|null>(null),[form,setForm]=useState<Campaign|null>(null);
  const [decision,setDecision]=useState<{action:string;label:string}|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
  const refresh=()=>setRevision(v=>v+1);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');
    Promise.all([apiFetch<{items:Campaign[];total:number}>(`${root}?limit=30&offset=${page*30}&search=${encodeURIComponent(search)}${status?'&status='+status:''}`,token,{signal:controller.signal}),apiFetch<{zones:typeof zones;assetStorageConfigured:boolean}>(root+'/options',token,{signal:controller.signal})])
      .then(([data,options])=>{if(!controller.signal.aborted){setRows(data.items);setTotal(data.total);setZones(options.zones);setStorageReady(options.assetStorageConfigured);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    return()=>controller.abort();},[token,page,search,status,revision]);
  const execute=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
  const open=(row:Campaign)=>execute(async()=>setSelected(await apiFetch<Campaign>(`${root}/${row.id}`,token)));
  const save=(e:FormEvent)=>{e.preventDefault();if(!form)return;if(!form.placements.length){setError('Selecciona al menos una ubicación donde estará disponible la campaña.');return;}void execute(async()=>{
    let result=await apiFetch<Campaign>(form.id?`${root}/${form.id}`:root,token,{method:form.id?'PUT':'POST',body:JSON.stringify(form)});setForm(null);setSelected(result);
    for(const kind of removed){result=await apiFetch<Campaign>(root+'/'+result.id+'/assets/'+kind+'?version='+result.version,token,{method:'DELETE'});setSelected(result);}
    setRemoved([]);
    for(const [kind,file] of Object.entries(files)){result=await uploadResource(result,kind,file);setSelected(result);}
    setFiles({});
  });};
  const update=(key:keyof Campaign,value:unknown)=>setForm(old=>old?{...old,[key]:value}:old);
  function validateFile(kind:string,file:File){
    const types=kind.startsWith('HEADER')?['image/png','image/webp']:['image/jpeg','image/png','image/webp'];
    if(file.size>2*1024*1024||!types.includes(file.type))throw new Error(kind.startsWith('HEADER')?'Usa PNG o WebP transparente de hasta 2 MB.':'Usa JPG, PNG o WebP de hasta 2 MB.');
  }
  async function uploadResource(campaign:Campaign,kind:string,file:File){
    validateFile(kind,file);
    const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]!);reader.onerror=()=>reject(new Error('No se pudo leer la imagen.'));reader.readAsDataURL(file);});
    return apiFetch<Campaign>(root+'/'+campaign.id+'/assets/'+kind,token,{method:'PUT',body:JSON.stringify({version:campaign.version,mime:file.type,filename:file.name,base64})});
  }
  const stageUpload=(kind:string,file:File)=>{try{validateFile(kind,file);setError('');setFiles(old=>({...old,[kind]:file}));setRemoved(old=>old.filter(x=>x!==kind));}catch(e){setError(e instanceof Error?e.message:String(e));}};
  const upload=(kind:string,file:File)=>{if(!selected)return;void execute(async()=>setSelected(await uploadResource(selected,kind,file)));};
  return <><div className="campaign-toolbar"><button className="secondary" onClick={()=>setTab("campaigns")}>Campañas</button>{permissions.includes("benefits:view")&&<button className="secondary" onClick={()=>setTab("benefits")}>Beneficios y recompensas</button>}{permissions.includes("benefits:view")&&<button className="secondary" onClick={()=>setTab("referrals")}>Programas de referidos</button>}</div>{tab==="referrals"?<ReferralPrograms token={token} permissions={permissions}/>:tab==="benefits"?<CostaGoBenefits token={token} permissions={permissions}/>:<section className="costa-campaigns">
    <div className="campaign-intro"><span className="campaign-intro-icon"><ConsoleIcon name="star" size={26}/></span><div><small>EXPERIENCIA EN LA APP</small><h2>Campañas Costa-Go</h2><p>Configura el contenido del Home y los decoración de la isla para cada audiencia.</p></div>{can('create')&&<button disabled={busy} onClick={()=>{setError('');setFiles({});setRemoved([]);setForm(initial());}}>Crear campaña</button>}</div>
    {error&&<p className="error" role="alert">{error}</p>}
    <div className="campaign-toolbar"><label>Buscar<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Nombre o título"/></label><label>Estado<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">Todos</option>{Object.entries(states).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="secondary" onClick={refresh}>Actualizar</button></div>
    {loading?<p role="status">Cargando campañas…</p>:<div className="campaign-table"><ManagedTable serverPaged><thead><tr>{['Nombre / título','Audiencia','Vigencia','Zonas','Estado','Presencia en la app','Prioridad','Acciones'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.internalName}</strong><br/>{row.title}</td><td>{audiences[row.audience]}</td><td>{ecuDate(row.startsAt)}<br/>{ecuDate(row.endsAt)}</td><td>{row.allZones?'Todas':row.zoneIds.map(id=>zones.find(z=>z.id===id)?.name??id).join(', ')}</td><td>{states[row.status!]}{row.status==='ACTIVE'&&<small>{Date.parse(row.endsAt)<=Date.now()?' · Vencida':Date.parse(row.startsAt)>Date.now()?' · Programada':' · En vigencia'}</small>}</td><td><span className="campaign-pill">{row.placements.includes('HOME')?'Tarjeta en Home':'Sin tarjeta en Home'}</span><small className="campaign-cell-hint">{variants[row.variant]??row.variant} · {row.decorateHeader?'Isla decorada':'Isla sin decoración'}</small></td><td>{row.priority}</td><td><button className="secondary" disabled={busy} onClick={()=>void open(row)}>Ver / gestionar</button></td></tr>)}</tbody></ManagedTable>{!rows.length&&<p>No hay campañas para estos filtros.</p>}</div>}
    <div className="campaign-toolbar"><button className="secondary" disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>{total} campañas · Página {page+1}</span><button className="secondary" disabled={(page+1)*30>=total||loading} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div>
    {form&&<ConsoleModal className="campaign-modal" subtitle="Contenido, audiencia y presencia en la aplicación" title={form.id?'Editar campaña':'Crear campaña'} onClose={()=>{if(!busy)setForm(null);}}><form onSubmit={save} className="campaign-form"><div className="campaign-notice"><ConsoleIcon name="alert"/><div><strong>Guardar no publica la campaña</strong><p>Quedará en borrador y dejará de mostrarse si estaba activa. Después debes enviarla a aprobación, aprobarla y activarla.</p></div></div>{error&&<p role="alert" className="error">{error}</p>}
      <section className="campaign-section"><div className="campaign-section-heading"><ConsoleIcon name="document"/><div><h3>1. Contenido de la campaña</h3><p>Separa el nombre de trabajo de los textos que verá el usuario.</p></div></div><div className="campaign-fields"><label>Nombre interno<input required maxLength={120} value={form.internalName} onChange={e=>update('internalName',e.target.value)}/><small>Solo para identificarla en el panel; no se muestra en la app.</small></label>
      <label>Título público<input required maxLength={160} value={form.title} onChange={e=>update('title',e.target.value)}/><small>Encabezado visible de la tarjeta y del detalle.</small></label>
      <label>Subtítulo<input maxLength={240} value={form.subtitle} onChange={e=>update('subtitle',e.target.value)}/><small>Texto breve debajo del título. Opcional.</small></label>
      <label className="wide">Descripción<textarea rows={5} maxLength={12000} value={form.description} onChange={e=>update('description',e.target.value)}/><small>Explicación completa en el detalle de la campaña.</small></label>
      </div></section><section className="campaign-section"><div className="campaign-section-heading"><ConsoleIcon name="users"/><div><h3>2. Audiencia y vigencia</h3><p>Define quién puede verla, durante qué fechas y en qué zonas.</p></div></div><div className="campaign-fields"><label>Audiencia<select value={form.audience} onChange={e=>update('audience',e.target.value)}>{Object.entries(audiences).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      <label>Prioridad (0–1000)<input type="number" min={0} max={1000} required value={form.priority} onChange={e=>update('priority',Number(e.target.value))}/><small>Un número mayor se muestra primero. Home muestra una sola tarjeta.</small></label>
      <label>Inicio<input required type="datetime-local" value={localDate(form.startsAt)} onChange={e=>update('startsAt',isoDate(e.target.value))}/><small>Hora de Ecuador (UTC−5). Antes de esta fecha no se muestra.</small></label>
      <label>Fin<input required type="datetime-local" value={localDate(form.endsAt)} onChange={e=>update('endsAt',isoDate(e.target.value))}/><small>Hora de Ecuador (UTC−5). Al llegar esta fecha deja de mostrarse.</small></label>
      <fieldset className="wide"><legend>Zonas operativas</legend><label className="check"><input type="checkbox" checked={form.allZones} onChange={e=>{update('allZones',e.target.checked);if(e.target.checked)update('zoneIds',[]);}}/>Todas las zonas</label>{!form.allZones&&zones.map(z=><label className="check" key={z.id}><input type="checkbox" disabled={!z.enabled&&!form.zoneIds.includes(z.id)} checked={form.zoneIds.includes(z.id)} onChange={e=>update('zoneIds',e.target.checked?[...form.zoneIds,z.id]:form.zoneIds.filter(id=>id!==z.id))}/>{z.name}{!z.enabled?' (deshabilitada)':''}</label>)}</fieldset>
      </div></section><section className="campaign-section"><div className="campaign-section-heading"><ConsoleIcon name="home"/><div><h3>3. Presencia en la app</h3><p>La tarjeta de Home y la decoración de la isla son opciones independientes.</p></div></div><div className="campaign-fields"><label>Variante visual<select value={form.variant} onChange={e=>update('variant',e.target.value)}>{['DEFAULT','CHRISTMAS','CARNIVAL','SUMMER','CUSTOM'].map((x,i)=><option key={x} value={x}>{['Estándar','Navidad','Carnaval','Verano','Personalizada'][i]}</option>)}</select></label>
      <fieldset><legend>Dónde mostrar la campaña</legend><p>Activa Inicio de la app (Home) para mostrar la tarjeta. La decoración de la isla se configura por separado.</p>{['HOME','CAMPAIGNS','NOTIFICATION'].map((x,i)=><label className="check" key={x}><input type="checkbox" checked={form.placements.includes(x)} onChange={e=>update('placements',e.target.checked?[...form.placements,x]:form.placements.filter(p=>p!==x))}/>{[<span><strong>Inicio de la app (Home)</strong><small>Muestra la tarjeta entre el encabezado Costa-Go y los accesos.</small></span>,<span><strong>Listado contextual de campañas</strong><small>Disponible al abrir el listado desde una acción. No añade una opción a Mi cuenta.</small></span>,<span><strong>Destino de notificaciones</strong><small>No envía mensajes automáticamente; el envío se gestiona aparte.</small></span>][i]}</label>)}</fieldset>
<label className="check campaign-toggle wide"><input type="checkbox" checked={form.decorateHeader??false} onChange={e=>update('decorateHeader',e.target.checked)}/><span><strong>Decorar la isla superior</strong><small>Ambientación independiente de la tarjeta de Home. Desactivado no carga ninguna decoración.</small></span></label>
<label>Modo de decoración<select value={form.headerDecorationMode??'AVATAR_ACCENT'} onChange={e=>update('headerDecorationMode',e.target.value)}>{[['NONE','Sin decoración'],['EDGES','Bordes (recomendado)'],['FULL_OVERLAY','Toda la isla'],['AVATAR_ACCENT','Detalle junto al avatar']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><small>Bordes conserva los adornos del contorno y los desvanece hacia el centro. Toda la isla muestra el overlay completo.</small></label>
<label className="check"><input type="checkbox" checked={form.useDecorativeAssetForHeader??false} onChange={e=>update('useDecorativeAssetForHeader',e.target.checked)}/>Usar decoración adicional como respaldo de isla (solo si es transparente)</label>
<label className="check"><input type="checkbox" checked={form.allowLightAssetsInDark??false} onChange={e=>update('allowLightAssetsInDark',e.target.checked)}/>Permitir recursos claros en tema oscuro: he comprobado el contraste</label>
<label className="check"><input type="checkbox" checked={form.allowMainImageInHome??false} onChange={e=>update('allowMainImageInHome',e.target.checked)}/>Usar imagen principal en Home si no hay miniatura adecuada</label>
<div className="campaign-note wide">Los recursos cargados tienen prioridad. Sin recurso, Navidad, Carnaval y Verano disponen de un pequeño detalle local de respaldo; Personalizada y Estándar mantienen la isla normal.</div></div></section><section className="campaign-section"><div className="campaign-section-heading"><ConsoleIcon name="arrow"/><div><h3>4. Acción y condiciones</h3><p>Define qué ocurre al tocar el botón de la campaña.</p></div></div><div className="campaign-fields"><label className="wide">Beneficio asociado<select value={form.benefitCode??''} onChange={e=>{update('benefitCode',e.target.value||null);if(e.target.value){update('ctaType','CAMPAIGN_DETAIL');update('ctaText','Activar cortesía');}}}><option value="">Sin beneficio</option>{benefits.filter(b=>b.status!=='ARCHIVED'&&(b.audience==='BOTH'||b.audience===form.audience)).map(b=><option key={b.code} value={b.code}>{b.name} · {b.code}</option>)}</select><small>Reutiliza la misma definición entre campañas. El usuario activa en el detalle; el backend comprueba vigencia, límites y elegibilidad. Gestiona sus reglas en Beneficios y recompensas.</small></label><label>Tipo de acción<select value={form.ctaType} onChange={e=>{update('ctaType',e.target.value);update('ctaDestination','');}}>{Object.entries(ctas).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      {form.ctaType!=='NONE'&&<label>Texto del botón<input required maxLength={80} value={form.ctaText} onChange={e=>update('ctaText',e.target.value)}/><small>Texto exacto que verá el usuario, por ejemplo: Descubre la Navidad.</small></label>}
      {form.ctaType==='EXTERNAL_URL'&&<label className="wide">Destino HTTPS<input type="url" required value={form.ctaDestination} onChange={e=>update('ctaDestination',e.target.value)}/><small>Usa una dirección pública que comience con https://.</small></label>}
      {form.ctaType==='INTERNAL_ROUTE'&&<label>Destino<select required value={form.ctaDestination} onChange={e=>update('ctaDestination',e.target.value)}><option value="">Selecciona una pantalla</option>{['support','membership','profile','activity','campaigns'].map((x,i)=><option key={x} value={x}>{['Soporte','Membresía (conductores)','Perfil','Actividad','Campañas'][i]}</option>)}</select></label>}
      <label className="wide">Términos y condiciones<textarea rows={4} maxLength={12000} value={form.terms} onChange={e=>update('terms',e.target.value)}/><small>Condiciones que se muestran en el detalle. Opcional.</small></label>
      </div></section><CampaignResources campaign={{...form,assets:form.assets?.filter(k=>!removed.includes(k))}} token={token} disabled={busy||!can('edit')} files={files} storageReady={storageReady} onUpload={stageUpload} onRemove={kind=>{if(files[kind])setFiles(old=>{const next={...old};delete next[kind];return next;});else setRemoved(old=>[...old,kind]);}}/><div className="campaign-form-footer"><span>Las imágenes seleccionadas se cargan al guardar el borrador.</span><button type="button" className="secondary" disabled={busy} onClick={()=>setForm(null)}>Cancelar</button><button disabled={busy}>{busy?'Guardando…':'Guardar borrador'}</button></div>
    </form></ConsoleModal>}
    {selected&&!form&&<ConsoleModal className="campaign-modal" initialFocus=".campaign-detail-heading" subtitle="Resumen, publicación y recursos visuales" title={selected.title} onClose={()=>{if(!busy){setSelected(null);setDecision(null);}}}>
      {error&&<p className="error" role="alert">{error}</p>}<div className="campaign-detail-heading" tabIndex={-1}><span className="campaign-pill">{states[selected.status!]}</span><span>{selected.internalName}</span><span>Prioridad {selected.priority}</span></div>
      <div className="campaign-summary-grid">
        <article><ConsoleIcon name="home"/><small>Tarjeta en Home</small><strong>{selected.placements.includes('HOME')?'Habilitada':'No habilitada'}</strong><p>{selected.placements.includes('HOME')?'Puede mostrarse cuando la campaña esté activa, vigente y corresponda al usuario.':'No aparecerá una tarjeta en Inicio con esta configuración.'}</p></article>
        <article><ConsoleIcon name="star"/><small>Decoración de la isla</small><strong>{!selected.decorateHeader||selected.headerDecorationMode==='NONE'?'Sin decoración':selected.assets?.some(k=>k.startsWith('HEADER'))?'Recurso cargado':selected.variant==='CUSTOM'?'Falta cargar un recurso':variants[selected.variant]}</strong><p>{selected.decorateHeader&&selected.assets?.includes('DECORATION')?'La imagen decorativa cargada tiene prioridad sobre el detalle de la variante.':'La decoración es independiente de la tarjeta de Home.'}</p></article>
        <article><ConsoleIcon name="users"/><small>Audiencia y zonas</small><strong>{audiences[selected.audience]}</strong><p>{selected.allZones?'Todas las zonas':selected.zoneIds.map(id=>zones.find(z=>z.id===id)?.name??id).join(', ')}</p></article>
        <article><ConsoleIcon name="calendar"/><small>Vigencia · Ecuador</small><strong>{ecuDate(selected.startsAt)}</strong><p>Hasta {ecuDate(selected.endsAt)}</p></article>
      </div>
      <section className="campaign-section campaign-detail-content"><h3>Contenido y destino</h3><p>{selected.subtitle||'Sin subtítulo'}</p><p className="campaign-copy">{selected.description||'Sin descripción adicional'}</p><dl><dt>Ubicaciones</dt><dd>{selected.placements.map(p=>placements[p]??p).join(', ')}</dd><dt>Variante visual</dt><dd>{variants[selected.variant]??selected.variant}</dd><dt>Acción del botón</dt><dd>{ctas[selected.ctaType]} {selected.ctaType!=='NONE'&&<>· {selected.ctaText}</>} {selected.ctaDestination}</dd></dl>{selected.terms&&<><h4>Términos y condiciones</h4><p className="campaign-copy">{selected.terms}</p></>}{selected.reviewReason&&<p className="campaign-note">Revisión: {selected.reviewReason}</p>}</section>
      {!selected.placements.includes('HOME')&&<p className="campaign-note" role="status">Esta campaña no mostrará tarjeta en Home. Edita sus ubicaciones si deseas mostrarla allí.</p>}
      <p className="campaign-publish-help">Publicación: guardar borrador → enviar a aprobación → aprobar → activar. Solo una campaña activa y vigente puede mostrarse en la app.</p>
      <div className="campaign-toolbar">{can('edit')&&selected.status!=='FINISHED'&&<button disabled={busy} onClick={()=>{setError('');setFiles({});setRemoved([]);setForm({...selected});}}>Editar</button>}{can('create')&&<button className="secondary" disabled={busy} onClick={()=>void execute(async()=>setSelected(await apiFetch<Campaign>(`${root}/${selected.id}/duplicate`,token,{method:'POST',body:'{}'})))}>Duplicar como borrador</button>}{actions.filter(a=>can(a[2])&&(a[3] as readonly string[]).includes(selected.status!)).map(a=><button className="secondary" key={a[0]} disabled={busy} onClick={()=>{setReason('');setDecision({action:a[0],label:a[1]});}}>{a[1]}</button>)}</div>
      {decision&&<form className="campaign-decision" onSubmit={e=>{e.preventDefault();void execute(async()=>{setSelected(await apiFetch<Campaign>(`${root}/${selected.id}/actions`,token,{method:'POST',body:JSON.stringify({version:selected.version,action:decision.action,reason})}));setDecision(null);});}}><h3>{decision.label}</h3><label>Motivo {decision.action==='REJECT'?'(obligatorio)':'(opcional)'}<textarea required={decision.action==='REJECT'} minLength={decision.action==='REJECT'?3:0} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>Confirmar {decision.label.toLowerCase()}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setDecision(null)}>Cancelar</button></form>}
      <CampaignResources campaign={selected} token={token} disabled={busy||!can('edit')||selected.status==='FINISHED'} storageReady={storageReady} onUpload={upload} onRemove={kind=>void execute(async()=>setSelected(await apiFetch<Campaign>(root+'/'+selected.id+'/assets/'+kind+'?version='+selected.version,token,{method:'DELETE'})))}/>
      <h3 className="campaign-history-title">Historial de cambios</h3><button className="secondary" disabled={busy} onClick={()=>void open(selected)}>Actualizar historial</button>{selected.history?.map((h,i)=><p key={i}>{ecuDate(h.createdAt)} · {h.actor} · {h.action.replace('COSTA_CAMPAIGN_','')}<br/>{h.reason}</p>)}
    </ConsoleModal>}
  </section>}</>;
}