import {useEffect,useState,type FormEvent} from 'react';
import {apiFetch,apiUrl} from './api';
import {ConsoleModal} from './console-ui';
import {ecuDate} from './console-model';
import './costa-go-campaigns.css';

type Campaign={id?:string;version?:number;internalName:string;title:string;subtitle:string;description:string;audience:string;startsAt:string;endsAt:string;priority:number;allZones:boolean;zoneIds:string[];variant:string;placements:string[];ctaType:string;ctaText:string;ctaDestination:string;terms:string;status?:string;enabled?:boolean;assets?:string[];reviewReason?:string;history?:{action:string;reason:string;createdAt:string;actor:string}[]};
const root='/v1/admin/costa-go-campaigns';
const states:Record<string,string>={DRAFT:'Borrador',PENDING_APPROVAL:'Pendiente de aprobación',APPROVED:'Aprobada',REJECTED:'Rechazada',ACTIVE:'Activa',PAUSED:'Pausada',FINISHED:'Finalizada'};
const audiences:Record<string,string>={PASSENGER:'Pasajeros',DRIVER:'Conductores',BOTH:'Ambos'};
const assets:Record<string,string>={MAIN:'Imagen principal',DARK:'Imagen para tema oscuro',THUMBNAIL:'Miniatura',DECORATION:'Recurso decorativo'};
const ctas:Record<string,string>={NONE:'Sin acción',CAMPAIGN_DETAIL:'Detalle de campaña',MEMBERSHIP:'Membresía (conductores)',SUPPORT:'Ayuda y soporte',INTERNAL_ROUTE:'Pantalla interna',EXTERNAL_URL:'Enlace externo HTTPS'};
const actions=[['SUBMIT','Enviar a aprobación','edit',['DRAFT','REJECTED']],['APPROVE','Aprobar','approve',['PENDING_APPROVAL']],['REJECT','Rechazar','reject',['PENDING_APPROVAL']],['ACTIVATE','Activar / programar','activate',['APPROVED','PAUSED']],['PAUSE','Pausar','deactivate',['ACTIVE']],['FINISH','Finalizar','deactivate',['DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','ACTIVE','PAUSED']]] as const;
const initial=():Campaign=>({internalName:'',title:'',subtitle:'',description:'',audience:'BOTH',startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+7*86400000).toISOString(),priority:0,allZones:true,zoneIds:[],variant:'DEFAULT',placements:['CAMPAIGNS'],ctaType:'NONE',ctaText:'',ctaDestination:'',terms:''});
const localDate=(value:string)=>value?new Date(Date.parse(value)-5*3600000).toISOString().slice(0,16):'';
const isoDate=(value:string)=>value?new Date(value+'-05:00').toISOString():'';
function AssetPreview({token,id,kind,version}:{token:string;id:string;kind:string;version?:number}){
  const [url,setUrl]=useState('');
  useEffect(()=>{const controller=new AbortController();let blobUrl='';
    fetch(apiUrl(`${root}/${id}/assets/${kind}?v=${version}`),{headers:{authorization:`Bearer ${token}`},signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.blob();}).then(blob=>{if(!controller.signal.aborted){blobUrl=URL.createObjectURL(blob);setUrl(blobUrl);}}).catch(()=>{});
    return()=>{controller.abort();if(blobUrl)URL.revokeObjectURL(blobUrl);};},[token,id,kind,version]);
  return url?<img src={url} alt={assets[kind]}/>:<span>Vista previa no disponible</span>;
}
export function CostaGoCampaigns({token,permissions}:{token:string;permissions:string[]}){
  const can=(action:string)=>permissions.includes('costa_campaigns:'+action);
  const [rows,setRows]=useState<Campaign[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[search,setSearch]=useState(''),[status,setStatus]=useState('');
  const [zones,setZones]=useState<{id:string;name:string;enabled:boolean}[]>([]),[selected,setSelected]=useState<Campaign|null>(null),[form,setForm]=useState<Campaign|null>(null);
  const [decision,setDecision]=useState<{action:string;label:string}|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
  const refresh=()=>setRevision(v=>v+1);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');
    Promise.all([apiFetch<{items:Campaign[];total:number}>(`${root}?limit=30&offset=${page*30}&search=${encodeURIComponent(search)}${status?'&status='+status:''}`,token,{signal:controller.signal}),apiFetch<{zones:typeof zones}>(root+'/options',token,{signal:controller.signal})])
      .then(([data,options])=>{if(!controller.signal.aborted){setRows(data.items);setTotal(data.total);setZones(options.zones);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    return()=>controller.abort();},[token,page,search,status,revision]);
  const execute=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
  const open=(row:Campaign)=>execute(async()=>setSelected(await apiFetch<Campaign>(`${root}/${row.id}`,token)));
  const save=(e:FormEvent)=>{e.preventDefault();if(!form)return;void execute(async()=>{
    const result=await apiFetch<Campaign>(form.id?`${root}/${form.id}`:root,token,{method:form.id?'PUT':'POST',body:JSON.stringify(form)});setForm(null);setSelected(result);
  });};
  const update=(key:keyof Campaign,value:unknown)=>setForm(old=>old?{...old,[key]:value}:old);
  const upload=(kind:string,file?:File)=>{if(!file||!selected)return;void execute(async()=>{
    if(file.size>2*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Usa JPG, PNG o WebP de hasta 2 MB.');
    const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]!);reader.onerror=()=>reject(new Error('No se pudo leer la imagen.'));reader.readAsDataURL(file);});
    setSelected(await apiFetch<Campaign>(`${root}/${selected.id}/assets/${kind}`,token,{method:'PUT',body:JSON.stringify({version:selected.version,mime:file.type,base64})}));
  });};
  return <section className="costa-campaigns">
    <div className="campaign-toolbar"><p>Campañas propias de Costa-Go. Se muestran según audiencia, zona y vigencia.</p>{can('create')&&<button disabled={busy} onClick={()=>{setError('');setForm(initial());}}>Crear campaña</button>}</div>
    {error&&<p className="error" role="alert">{error}</p>}
    <div className="campaign-toolbar"><label>Buscar<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Nombre o título"/></label><label>Estado<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">Todos</option>{Object.entries(states).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="secondary" onClick={refresh}>Actualizar</button></div>
    {loading?<p role="status">Cargando campañas…</p>:<div className="campaign-table"><table><thead><tr>{['Nombre / título','Audiencia','Vigencia','Zonas','Estado','Prioridad','Acciones'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.internalName}</strong><br/>{row.title}</td><td>{audiences[row.audience]}</td><td>{ecuDate(row.startsAt)}<br/>{ecuDate(row.endsAt)}</td><td>{row.allZones?'Todas':row.zoneIds.map(id=>zones.find(z=>z.id===id)?.name??id).join(', ')}</td><td>{states[row.status!]}{row.status==='ACTIVE'&&<small>{Date.parse(row.endsAt)<=Date.now()?' · Vencida':Date.parse(row.startsAt)>Date.now()?' · Programada':' · En vigencia'}</small>}</td><td>{row.priority}</td><td><button className="secondary" disabled={busy} onClick={()=>void open(row)}>Ver / gestionar</button></td></tr>)}</tbody></table>{!rows.length&&<p>No hay campañas para estos filtros.</p>}</div>}
    <div className="campaign-toolbar"><button className="secondary" disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>{total} campañas · Página {page+1}</span><button className="secondary" disabled={(page+1)*30>=total||loading} onClick={()=>setPage(p=>p+1)}>Siguiente</button></div>
    {form&&<ConsoleModal title={form.id?'Editar campaña':'Crear campaña'} onClose={()=>{if(!busy)setForm(null);}}><form onSubmit={save} className="campaign-form"><p>Los horarios corresponden a Ecuador (UTC−5). Guardar cambios devuelve la campaña a borrador y requiere nueva aprobación.</p>{error&&<p role="alert" className="error">{error}</p>}
      <label>Nombre interno<input required maxLength={120} value={form.internalName} onChange={e=>update('internalName',e.target.value)}/></label>
      <label>Título público<input required maxLength={160} value={form.title} onChange={e=>update('title',e.target.value)}/></label>
      <label>Subtítulo<input maxLength={240} value={form.subtitle} onChange={e=>update('subtitle',e.target.value)}/></label>
      <label className="wide">Descripción<textarea rows={5} maxLength={12000} value={form.description} onChange={e=>update('description',e.target.value)}/></label>
      <label>Audiencia<select value={form.audience} onChange={e=>update('audience',e.target.value)}>{Object.entries(audiences).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      <label>Prioridad (0–1000)<input type="number" min={0} max={1000} required value={form.priority} onChange={e=>update('priority',Number(e.target.value))}/></label>
      <label>Inicio<input required type="datetime-local" value={localDate(form.startsAt)} onChange={e=>update('startsAt',isoDate(e.target.value))}/></label>
      <label>Fin<input required type="datetime-local" value={localDate(form.endsAt)} onChange={e=>update('endsAt',isoDate(e.target.value))}/></label>
      <fieldset className="wide"><legend>Zonas operativas</legend><label className="check"><input type="checkbox" checked={form.allZones} onChange={e=>{update('allZones',e.target.checked);if(e.target.checked)update('zoneIds',[]);}}/>Todas las zonas</label>{!form.allZones&&zones.map(z=><label className="check" key={z.id}><input type="checkbox" disabled={!z.enabled&&!form.zoneIds.includes(z.id)} checked={form.zoneIds.includes(z.id)} onChange={e=>update('zoneIds',e.target.checked?[...form.zoneIds,z.id]:form.zoneIds.filter(id=>id!==z.id))}/>{z.name}{!z.enabled?' (deshabilitada)':''}</label>)}</fieldset>
      <label>Variante visual<select value={form.variant} onChange={e=>update('variant',e.target.value)}>{['DEFAULT','CHRISTMAS','CARNIVAL','SUMMER','CUSTOM'].map((x,i)=><option key={x} value={x}>{['Estándar','Navidad','Carnaval','Verano','Personalizada'][i]}</option>)}</select></label>
      <fieldset><legend>Ubicaciones</legend>{['HOME','CAMPAIGNS','NOTIFICATION'].map((x,i)=><label className="check" key={x}><input type="checkbox" checked={form.placements.includes(x)} onChange={e=>update('placements',e.target.checked?[...form.placements,x]:form.placements.filter(p=>p!==x))}/>{['Inicio (preparado para próxima fase)','Sección Campañas','Notificación (sin envío automático)'][i]}</label>)}</fieldset>
      <label>Tipo de acción<select value={form.ctaType} onChange={e=>{update('ctaType',e.target.value);update('ctaDestination','');}}>{Object.entries(ctas).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      {form.ctaType!=='NONE'&&<label>Texto del botón<input required maxLength={80} value={form.ctaText} onChange={e=>update('ctaText',e.target.value)}/></label>}
      {form.ctaType==='EXTERNAL_URL'&&<label className="wide">Destino HTTPS<input type="url" required value={form.ctaDestination} onChange={e=>update('ctaDestination',e.target.value)}/></label>}
      {form.ctaType==='INTERNAL_ROUTE'&&<label>Destino<select required value={form.ctaDestination} onChange={e=>update('ctaDestination',e.target.value)}><option value="">Selecciona una pantalla</option>{['support','membership','profile','activity','campaigns'].map((x,i)=><option key={x} value={x}>{['Soporte','Membresía (conductores)','Perfil','Actividad','Campañas'][i]}</option>)}</select></label>}
      <label className="wide">Términos y condiciones<textarea rows={4} maxLength={12000} value={form.terms} onChange={e=>update('terms',e.target.value)}/></label>
      <p className="wide">Las imágenes se agregan después de guardar el borrador. Referidos estará disponible cuando exista su flujo móvil.</p><div className="campaign-toolbar wide"><button type="button" className="secondary" disabled={busy} onClick={()=>setForm(null)}>Cancelar</button><button disabled={busy}>{busy?'Guardando…':'Guardar borrador'}</button></div>
    </form></ConsoleModal>}
    {selected&&!form&&<ConsoleModal title={selected.title} onClose={()=>{if(!busy){setSelected(null);setDecision(null);}}}>
      {error&&<p className="error" role="alert">{error}</p>}<p><strong>{states[selected.status!]}</strong> · {audiences[selected.audience]} · Prioridad {selected.priority}</p><p>{ecuDate(selected.startsAt)} → {ecuDate(selected.endsAt)}</p><p>{selected.subtitle}</p><p className="campaign-copy">{selected.description}</p><p>Zonas: {selected.allZones?'Todas':selected.zoneIds.map(id=>zones.find(z=>z.id===id)?.name??id).join(', ')}</p><p>Ubicaciones: {selected.placements.join(', ')} · Variante: {selected.variant}</p><p>Acción: {ctas[selected.ctaType]} {selected.ctaText} {selected.ctaDestination}</p><p className="campaign-copy">{selected.terms}</p>{selected.reviewReason&&<p>Revisión: {selected.reviewReason}</p>}
      <div className="campaign-toolbar">{can('edit')&&selected.status!=='FINISHED'&&<button disabled={busy} onClick={()=>{setError('');setForm({...selected});}}>Editar</button>}{can('create')&&<button className="secondary" disabled={busy} onClick={()=>void execute(async()=>setSelected(await apiFetch<Campaign>(`${root}/${selected.id}/duplicate`,token,{method:'POST',body:'{}'})))}>Duplicar como borrador</button>}{actions.filter(a=>can(a[2])&&(a[3] as readonly string[]).includes(selected.status!)).map(a=><button className="secondary" key={a[0]} disabled={busy} onClick={()=>{setReason('');setDecision({action:a[0],label:a[1]});}}>{a[1]}</button>)}</div>
      {decision&&<form className="campaign-decision" onSubmit={e=>{e.preventDefault();void execute(async()=>{setSelected(await apiFetch<Campaign>(`${root}/${selected.id}/actions`,token,{method:'POST',body:JSON.stringify({version:selected.version,action:decision.action,reason})}));setDecision(null);});}}><h3>{decision.label}</h3><label>Motivo {decision.action==='REJECT'?'(obligatorio)':'(opcional)'}<textarea required={decision.action==='REJECT'} minLength={decision.action==='REJECT'?3:0} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>Confirmar {decision.label.toLowerCase()}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setDecision(null)}>Cancelar</button></form>}
      <h3>Recursos visuales</h3><p>JPG, PNG o WebP, hasta 2 MB y 4096 px. Cambiar o retirar una imagen devuelve la campaña a borrador.</p><div className="campaign-assets">{Object.entries(assets).map(([kind,label])=><article key={kind}><strong>{label}</strong>{selected.assets?.includes(kind)&&<AssetPreview token={token} id={selected.id!} kind={kind} version={selected.version}/>} {can('edit')&&selected.status!=='FINISHED'&&<><input aria-label={label} type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{upload(kind,e.target.files?.[0]);e.target.value='';}}/>{selected.assets?.includes(kind)&&<button className="secondary" disabled={busy} onClick={()=>void execute(async()=>setSelected(await apiFetch<Campaign>(`${root}/${selected.id}/assets/${kind}?version=${selected.version}`,token,{method:'DELETE'})))}>Retirar imagen</button>}</>}</article>)}</div>
      <h3>Historial</h3><button className="secondary" disabled={busy} onClick={()=>void open(selected)}>Actualizar historial</button>{selected.history?.map((h,i)=><p key={i}>{ecuDate(h.createdAt)} · {h.actor} · {h.action.replace('COSTA_CAMPAIGN_','')}<br/>{h.reason}</p>)}
    </ConsoleModal>}
  </section>;
}
