import {useEffect,useState,type FormEvent} from 'react';
import {apiFetch} from './api';
import {ConsoleModal,ManagedTable} from './console-ui';
import {ecuDate} from './console-model';
import './costa-go-campaigns.css';
type Benefit={expirationDays?:number|null;id?:string;version?:number;code:string;name:string;description:string;benefitType:string;value:number;audience:string;oneTime:boolean;requiresActivation:boolean;startsAt:string;endsAt:string;maxGlobal:number|null;maxPerUser:number|null;status:string;zoneIds:string[];redemptions?:number;totalGranted?:number};
const root='/v1/admin/benefits';
const initial=():Benefit=>({code:'DRIVER_FOUNDER_COURTESY',name:'Conductor fundador',description:'15 días gratis de membresía para conductores aprobados y activos. Disponible una sola vez.',benefitType:'COURTESY_DAYS',value:15,audience:'DRIVER',oneTime:true,requiresActivation:true,startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+30*86400000).toISOString(),maxGlobal:null,maxPerUser:1,status:'DRAFT',zoneIds:[]});
const types:Record<string,string>={COURTESY_DAYS:'Días de cortesía',PROMOTIONAL_BALANCE:'Saldo promocional acumulable',TRIP_DISCOUNT:'Descuento de viaje (preparación)',FIXED_DISCOUNT:'Descuento fijo (preparación)',PERCENTAGE_DISCOUNT:'Descuento porcentual (preparación)',FREE_TRIPS:'Viajes gratis (preparación)',MEMBERSHIP:'Membresía (preparación)',REFERRAL_REWARD:'Referidos (preparación)',CUSTOM:'Personalizado (preparación)'};
const states:Record<string,string>={DRAFT:'Borrador',ACTIVE:'Activo',PAUSED:'Pausado',ARCHIVED:'Archivado',PENDING:'Programado',EXPIRED:'Vencido',USED:'Usado',CANCELLED:'Cancelado',FAILED:'Fallido'};
const local=(v:string)=>v?new Date(Date.parse(v)-5*3600000).toISOString().slice(0,16):'';
const iso=(v:string)=>v?new Date(v+'-05:00').toISOString():'';
export function CostaGoBenefits({token,permissions}:{token:string;permissions:string[]}){
 const [rows,setRows]=useState<Benefit[]>([]),[zones,setZones]=useState<{id:string;name:string;enabled:boolean}[]>([]),[form,setForm]=useState<Benefit|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const [claims,setClaims]=useState<any[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[filters,setFilters]=useState({code:'',status:'',audience:'',zone:'',from:'',until:''});
 const [history,setHistory]=useState<any[]|null>(null);
 const can=permissions.includes('benefits:manage');
 useEffect(()=>{const controller=new AbortController();setError('');const query=new URLSearchParams({offset:String(page*50)});Object.entries(filters).forEach(([k,v])=>{if(v)query.set(k,['from','until'].includes(k)?iso(v):v);});
 Promise.all([apiFetch<{items:Benefit[];zones:typeof zones}>(root,token,{signal:controller.signal}),apiFetch<{items:any[];total:number}>(root+'/redemptions?'+query,token,{signal:controller.signal})]).then(([b,r])=>{setRows(b.items);setZones(b.zones);setClaims(r.items);setTotal(r.total);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[token,revision,filters,page]);
 const set=(k:keyof Benefit,v:unknown)=>setForm(f=>f?{...f,[k]:v}:f);
 async function save(e:FormEvent){e.preventDefault();if(!form||busy)return;setBusy(true);setError('');try{const {id,redemptions,totalGranted,version,...body}=form;await apiFetch(id?`${root}/${id}`:root,token,{method:id?'PUT':'POST',body:JSON.stringify({...body,...(id?{version}:{})})});setForm(null);setRevision(x=>x+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const filter=(key:string,value:string)=>{setFilters(f=>({...f,[key]:value}));setPage(0);};
 return <section className="costa-campaigns"><div className="campaign-intro"><div><small>BENEFICIOS Y RECOMPENSAS</small><h2>Beneficios Costa-Go</h2><p>La campaña comunica; el beneficio valida y entrega la cobertura. No modifica compras, facturas ni dinero recargado.</p></div>{can&&<button onClick={()=>setForm(initial())}>Crear beneficio</button>}</div>
 {error&&<p className="error" role="alert">{error}</p>}<div className="campaign-notice"><div><strong>Cortesía por días disponible</strong><p>Solo conductores aprobados, activos y sin suspensión. Si tienen membresía vigente, la cortesía comienza después de su vencimiento. La vigencia de la campaña limita cuándo activar; los días otorgados conservan su propia fecha de fin.</p><p>Las cortesías y el saldo promocional pueden entregarse automáticamente por referidos. El saldo promocional se acumula separado del saldo real; aún no se puede gastar en viajes. Descuentos y otros tipos siguen en preparación.</p></div></div>
 <ManagedTable><thead><tr>{['Beneficio / código','Tipo / valor','Audiencia','Ventana de activación','Límites','Activaciones / total otorgado','Estado','Acciones'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(b=><tr key={b.id}><td><strong>{b.name}</strong><br/>{b.code}</td><td>{types[b.benefitType]}<br/>{b.value}{b.benefitType==='COURTESY_DAYS'?' días':''}</td><td>{b.audience==='DRIVER'?'Conductores':b.audience==='PASSENGER'?'Pasajeros':'Ambos'}</td><td>{ecuDate(b.startsAt)}<br/>{ecuDate(b.endsAt)}</td><td>{b.oneTime?'Una sola vez':`${b.maxPerUser??'Sin límite'} por usuario`}<br/>{b.maxGlobal??'Sin límite'} global</td><td>{b.redemptions??0} activaciones<br/>{b.totalGranted??0} {b.benefitType==='COURTESY_DAYS'?'días':''}</td><td>{states[b.status]}</td><td>{can&&<button className="secondary" onClick={()=>setForm({...b})}>Editar</button>}<button className="secondary" onClick={()=>filter('code',b.code)}>Redenciones</button><button className="secondary" onClick={()=>{void apiFetch<{items:any[]}>(`${root}/${b.id}/history`,token).then(r=>setHistory(r.items)).catch(e=>setError(e.message));}}>Auditoría</button></td></tr>)}</tbody></ManagedTable>
 <h3>Historial de beneficios otorgados</h3><p>Se conserva incluso si se pausa o archiva el beneficio. No existe borrado ni entrega manual arbitraria.</p><div className="campaign-fields">
 <label>Beneficio<select value={filters.code} onChange={e=>filter('code',e.target.value)}><option value="">Todos</option>{rows.map(b=><option key={b.code} value={b.code}>{b.name}</option>)}</select></label>
 <label>Estado<select value={filters.status} onChange={e=>filter('status',e.target.value)}><option value="">Todos</option>{['PENDING','ACTIVE','EXPIRED','USED','CANCELLED','FAILED'].map(s=><option key={s} value={s}>{states[s]}</option>)}</select></label>
 <label>Audiencia<select value={filters.audience} onChange={e=>filter('audience',e.target.value)}><option value="">Todas</option><option value="DRIVER">Conductores</option><option value="PASSENGER">Pasajeros</option></select></label>
 <label>Zona<select value={filters.zone} onChange={e=>filter('zone',e.target.value)}><option value="">Todas</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label>
 <label>Activado desde (Ecuador)<input type="datetime-local" value={filters.from} onChange={e=>filter('from',e.target.value)}/></label><label>Activado antes de (Ecuador)<input type="datetime-local" value={filters.until} onChange={e=>filter('until',e.target.value)}/></label></div>
 <ManagedTable serverPaged><thead><tr>{['Usuario','Beneficio / campaña','Otorgado','Activación','Estado','Cobertura'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{claims.map(r=><tr key={r.id}><td>{r.user}</td><td>{r.benefitCode}<br/>{r.campaign}</td><td>{r.value} {r.benefitType==='COURTESY_DAYS'?'días':'USD promocionales'}</td><td>{ecuDate(r.redeemedAt)}</td><td>{states[r.status]}</td><td>{ecuDate(r.effectiveFrom)}<br/>{ecuDate(r.effectiveUntil)}</td></tr>)}</tbody></ManagedTable><div className="campaign-toolbar"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>{total} redenciones</span><button disabled={(page+1)*50>=total} onClick={()=>setPage(p=>p+1)}>Siguiente</button><button onClick={()=>setRevision(x=>x+1)}>Actualizar</button></div>
 {history&&<ConsoleModal title="Auditoría del beneficio" onClose={()=>setHistory(null)}>{history.length?history.map((h,i)=><div key={i}><strong>{h.action}</strong> · {ecuDate(h.created_at)}<p>{h.actor??'Sistema'} · {h.reason}</p><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(h.next_value,null,2)}</pre></div>):<p>Sin operaciones registradas.</p>}</ConsoleModal>}
 {form&&<ConsoleModal title={form.id?'Editar beneficio':'Crear beneficio'} subtitle="Reglas del motor; no se aplican hasta que el usuario lo active desde una campaña vigente" onClose={()=>{if(!busy)setForm(null);}} className="campaign-modal"><form onSubmit={save} className="campaign-form">{error&&<p className="error" role="alert">{error}</p>}<section className="campaign-section"><h3>Identidad y entrega</h3><div className="campaign-fields">
 <label>Nombre<input required maxLength={160} value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Código estable<input required disabled={!!form.id} pattern="[A-Z][A-Z0-9_]{2,79}" value={form.code} onChange={e=>set('code',e.target.value)}/><small>Identifica el beneficio entre campañas. Es inmutable.</small></label>
 <label className="wide">Descripción<textarea value={form.description} maxLength={4000} onChange={e=>set('description',e.target.value)}/></label>
 <label>Tipo<select disabled={!!form.id} value={form.benefitType} onChange={e=>{set('benefitType',e.target.value);set('status','DRAFT');}}>{Object.entries(types).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
 <label>{form.benefitType==='COURTESY_DAYS'?'Días de membresía gratis':form.benefitType==='PROMOTIONAL_BALANCE'?'Saldo promocional (USD)':'Valor previsto'}<input required type="number" min={form.benefitType==='PROMOTIONAL_BALANCE'?0.01:1} max={365} step={form.benefitType==='PROMOTIONAL_BALANCE'?0.01:1} value={form.value} onChange={e=>set('value',Number(e.target.value))}/><small>El backend establece inicio y fin. No modifica dinero recargado ni viajes de un paquete.</small></label>
 {form.benefitType==='PROMOTIONAL_BALANCE'&&<label>Vigencia del crédito (días)<input type="number" required min={1} max={365} value={form.expirationDays??''} onChange={e=>set('expirationDays',Number(e.target.value))}/><small>Cuenta desde la entrega automática. No es dinero retirable.</small></label>}<label>Audiencia<select value={form.audience} onChange={e=>set('audience',e.target.value)}><option value="DRIVER">Conductores</option>{form.benefitType!=='COURTESY_DAYS'&&<><option value="PASSENGER">Pasajeros</option><option value="BOTH">Ambos</option></>}</select></label>
 <label>Activación<select value={String(form.requiresActivation)} onChange={e=>{set('requiresActivation',e.target.value==='true');set('status','DRAFT');}}><option value="true">Manual: el usuario debe activar</option><option value="false">Automática: al calificar un referido</option></select></label></div></section>
 <section className="campaign-section"><h3>Vigencia, zonas y límites</h3><div className="campaign-fields"><label>Inicio para activar (Ecuador)<input required type="datetime-local" value={local(form.startsAt)} onChange={e=>set('startsAt',iso(e.target.value))}/></label><label>Fin para activar (Ecuador)<input required type="datetime-local" value={local(form.endsAt)} onChange={e=>set('endsAt',iso(e.target.value))}/></label>
 <label className="check"><input type="checkbox" disabled={!!form.id} checked={form.oneTime} onChange={e=>{set('oneTime',e.target.checked);if(e.target.checked)set('maxPerUser',1);}}/>Una sola vez por usuario, incluso entre campañas</label>
 <label>Máximo por usuario<input type="number" min={1} disabled={form.oneTime} value={form.maxPerUser??''} onChange={e=>set('maxPerUser',e.target.value?Number(e.target.value):null)}/><small>Vacío: sin límite. Fundador: 1.</small></label><label>Máximo global<input type="number" min={1} value={form.maxGlobal??''} onChange={e=>set('maxGlobal',e.target.value?Number(e.target.value):null)}/><small>Vacío: sin límite global. Cuenta todas las redenciones históricas.</small></label>
 <fieldset className="wide"><legend>Zonas permitidas</legend><p>Sin selección: todas. En zonas específicas se requiere una ubicación resoluble en el área operativa.</p>{zones.map(z=><label className="check" key={z.id}><input type="checkbox" disabled={!z.enabled} checked={form.zoneIds.includes(z.id)} onChange={e=>set('zoneIds',e.target.checked?[...form.zoneIds,z.id]:form.zoneIds.filter(x=>x!==z.id))}/>{z.name}</label>)}</fieldset>
 <label>Estado<select value={form.status} onChange={e=>set('status',e.target.value)}>{['DRAFT','ACTIVE','PAUSED','ARCHIVED'].map(s=><option key={s} value={s} disabled={s==='ACTIVE'&&!['COURTESY_DAYS','PROMOTIONAL_BALANCE'].includes(form.benefitType)}>{states[s]}</option>)}</select><small>Activo permite nuevas activaciones desde una campaña vigente. Pausar no revoca beneficios ya otorgados.</small></label></div></section><div className="campaign-toolbar"><button type="button" className="secondary" disabled={busy} onClick={()=>setForm(null)}>Cancelar</button><button disabled={busy}>Guardar beneficio</button></div></form></ConsoleModal>}
 </section>;
}
