import { useEffect, useState } from "react";
import { apiFetch } from "./api.js";
import { ServiceAreaMap, type ServiceAreaGeometry } from "./service-area-map.js";

type Area={id:string;code:string;name:string};
type Sector={id:string;serviceAreaId:string;serviceAreaCode:string;code:string;name:string;description?:string;priority:number;enabled:boolean;geometry:ServiceAreaGeometry};
type Rule={id:string;serviceAreaId:string;originSectorId:string;originSector:string;destinationSectorId:string;destinationSector:string;minimumPassengers:number;maximumPassengers:number;dayTotalCents:number;nightTotalCents:number;bidirectional:boolean;enabled:boolean;priority:number};
const emptySector={id:"",serviceAreaId:"",code:"",name:"",description:"",priority:0,enabled:false,geometry:null as ServiceAreaGeometry|null};
const emptyRule={id:"",serviceAreaId:"",originSectorId:"",destinationSectorId:"",minimumPassengers:1,maximumPassengers:1,dayTotalCents:50,nightTotalCents:100,bidirectional:true,enabled:false,priority:0};

export function FareTerritories({token,canManage}:{token:string;canManage:boolean}){
  const [areas,setAreas]=useState<Area[]>([]);const [sectors,setSectors]=useState<Sector[]>([]);const [rules,setRules]=useState<Rule[]>([]);
  const [sector,setSector]=useState(emptySector);const [rule,setRule]=useState(emptyRule);const [drawing,setDrawing]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");
  async function load(){try{const [a,s,r]=await Promise.all([apiFetch<Area[]>("/v1/admin/zones",token),apiFetch<Sector[]>("/v1/admin/fare-sectors",token),apiFetch<Rule[]>("/v1/admin/fare-rules",token)]);setAreas(a);setSectors(s);setRules(r);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}}
  useEffect(()=>{void load();},[token]);
  function editSector(value:Sector){setSector({id:value.id,serviceAreaId:value.serviceAreaId,code:value.code,name:value.name,description:value.description??"",priority:value.priority,enabled:value.enabled,geometry:value.geometry});}
  async function saveSector(event:React.FormEvent){event.preventDefault();if(!sector.geometry)return;setError("");try{await apiFetch("/v1/admin/fare-sectors",token,{method:"POST",body:JSON.stringify(sector)});setSuccess(sector.id?"Sector tarifario actualizado.":"Sector creado inactivo; revísalo antes de habilitarlo.");setSector(emptySector);await load();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}}
  async function saveRule(event:React.FormEvent){event.preventDefault();setError("");try{await apiFetch("/v1/admin/fare-rules",token,{method:"POST",body:JSON.stringify(rule)});setSuccess(rule.id?"Regla tarifaria actualizada.":"Regla creada inactiva; actívala después de revisarla.");setRule(emptyRule);await load();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}}
  const areaSectors=sectors.filter(value=>value.serviceAreaId===rule.serviceAreaId);
  return <section className="card" style={{gridColumn:"1/-1"}}><div className="section-heading"><div><span className="eyebrow">TARIFA TERRITORIAL</span><h2>Sectores y trayectos</h2><p className="muted">Los polígonos identifican sectores tarifarios dentro de una misma zona de cobertura. Las reglas vigentes del tarifario tienen prioridad; si falta una regla, la app muestra únicamente un valor sugerido de respaldo.</p></div></div>{error&&<div className="alert error">{error}</div>}{success&&<div className="alert success">{success}</div>}
    <div className="split"><div><h3>Sectores configurados</h3>{sectors.map(value=><button className="list-row" type="button" key={value.id} onClick={()=>editSector(value)}><span><strong>{value.name}</strong><small>{value.serviceAreaCode} · {value.code}</small></span><span>{value.enabled?"Activo":"Inactivo"}</span></button>)}{!sectors.length&&<p className="muted">Todavía no existen subsectores tarifarios.</p>}</div>
    {canManage&&<form className="form-card" onSubmit={saveSector}><h3>{sector.id?"Editar sector":"Nuevo sector"}</h3><label>Zona de cobertura<select required value={sector.serviceAreaId} onChange={event=>setSector({...sector,serviceAreaId:event.target.value})}><option value="">Seleccionar</option>{areas.map(area=><option key={area.id} value={area.id}>{area.code} · {area.name}</option>)}</select></label><div className="form-grid"><label>Código<input required pattern="[A-Z0-9_]+" value={sector.code} onChange={event=>setSector({...sector,code:event.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,"")})}/></label><label>Nombre<input required value={sector.name} onChange={event=>setSector({...sector,name:event.target.value})}/></label><label>Prioridad<input type="number" value={sector.priority} onChange={event=>setSector({...sector,priority:Number(event.target.value)})}/></label><label><input type="checkbox" checked={sector.enabled} onChange={event=>setSector({...sector,enabled:event.target.checked})}/> Activo</label></div><label>Descripción<textarea value={sector.description} onChange={event=>setSector({...sector,description:event.target.value})}/></label><ServiceAreaMap geometry={sector.geometry} zones={sectors} editable={!drawing} drawing={drawing} onDrawingChange={setDrawing} onGeometryChange={geometry=>setSector({...sector,geometry})}/><button className="primary" disabled={!sector.geometry}>Guardar sector</button></form>}</div>
    <div className="split"><div><h3>Reglas por trayecto</h3>{rules.map(value=><button className="list-row" type="button" key={value.id} onClick={()=>setRule({...value})}><span><strong>{value.originSector} ↔ {value.destinationSector}</strong><small>{value.minimumPassengers}–{value.maximumPassengers} pasajeros · día ${(value.dayTotalCents/100).toFixed(2)} · noche ${(value.nightTotalCents/100).toFixed(2)}</small></span><span>{value.enabled?"Activa":"Inactiva"}</span></button>)}{!rules.length&&<p className="muted">Hasta crear reglas, se mostrará el valor local sugerido.</p>}</div>
    {canManage&&<form className="form-card" onSubmit={saveRule}><h3>{rule.id?"Editar regla":"Nueva regla"}</h3><label>Zona de cobertura<select required value={rule.serviceAreaId} onChange={event=>setRule({...rule,serviceAreaId:event.target.value,originSectorId:"",destinationSectorId:""})}><option value="">Seleccionar</option>{areas.map(area=><option key={area.id} value={area.id}>{area.code}</option>)}</select></label><div className="form-grid"><label>Origen<select required value={rule.originSectorId} onChange={event=>setRule({...rule,originSectorId:event.target.value})}><option value="">Seleccionar</option>{areaSectors.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label>Destino<select required value={rule.destinationSectorId} onChange={event=>setRule({...rule,destinationSectorId:event.target.value})}><option value="">Seleccionar</option>{areaSectors.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label>Pasajeros desde<input type="number" min="1" max="3" value={rule.minimumPassengers} onChange={event=>setRule({...rule,minimumPassengers:Number(event.target.value)})}/></label><label>Pasajeros hasta<input type="number" min="1" max="3" value={rule.maximumPassengers} onChange={event=>setRule({...rule,maximumPassengers:Number(event.target.value)})}/></label><label>Día (centavos)<input type="number" min="0" value={rule.dayTotalCents} onChange={event=>setRule({...rule,dayTotalCents:Number(event.target.value)})}/></label><label>Noche (centavos)<input type="number" min="0" value={rule.nightTotalCents} onChange={event=>setRule({...rule,nightTotalCents:Number(event.target.value)})}/></label><label>Prioridad<input type="number" min="-1000" max="1000" value={rule.priority} onChange={event=>setRule({...rule,priority:Number(event.target.value)})}/></label><label><input type="checkbox" checked={rule.bidirectional} onChange={event=>setRule({...rule,bidirectional:event.target.checked})}/> Viceversa</label><label><input type="checkbox" checked={rule.enabled} onChange={event=>setRule({...rule,enabled:event.target.checked})}/> Activa</label></div><button className="primary">Guardar regla</button></form>}</div></section>;
}
