import {useEffect,useRef,useState} from 'react';
import {apiFetch} from './api.js';
import {FiscalProfileCard,fiscalMessage} from './fiscal-profile.js';
import './fiscal.css';

type Tab='dashboard'|'invoices'|'clients'|'payments'|'config';
const entityNames:Record<string,string>={CONDUCTOR:'Conductor',COMERCIO:'Comercio',COOPERATIVA:'Cooperativa',EMPRESA:'Empresa',OTRO:'Otro'};
const tabs:[Tab,string,string][]=[['dashboard','Dashboard','FACTURACION_DASHBOARD_VER'],['invoices','Facturas','FACTURACION_VER'],['clients','Clientes fiscales','CLIENTES_FISCALES_VER'],['payments','Pagos','FACTURACION_VER'],['config','Configuración','FACTURACION_VER']];
const statusNames:Record<string,string>={PENDING_ALL:'Todas las pendientes',COLLECTED:'Pagos vigentes',UNBILLED:'Pagos pendientes de facturar',BORRADOR:'Borrador',PENDIENTE:'Pendiente',PENDIENTE_INTEGRACION:'Pendiente de integración',ENVIANDO:'Enviando',RECIBIDA:'Recibida',AUTORIZADA:'Autorizada',RECHAZADA:'Rechazada',ERROR:'Error',PENDIENTE_REINTENTO:'Pendiente de reintento',ANULADA:'Anulada'};
const sourceNames:Record<string,string>={MEMBRESIA:'Membresía',PUBLICIDAD:'Publicidad',PUNTO_VENTA:'Punto de venta',OTRO:'Otro'};
const money=(v:any)=>v==null?'—':new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(Number(v));
const date=(v:any)=>v?new Date(v).toLocaleString('es-EC',{timeZone:'America/Guayaquil'}):'—';
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Guayaquil'});
const monthStart=()=>today().slice(0,8)+'01';
function Empty(){return <p className="fiscal-empty">No hay registros para los filtros seleccionados.</p>;}

export function FiscalAdmin({token,permissions}:{token:string;permissions:string[]}){
  const [tab,setTab]=useState<Tab>(tabs.find(t=>permissions.includes(t[2]))?.[0]??'clients');
  const [filters,setFilters]=useState({start:monthStart(),end:today(),source:'',status:'',search:'',zoneId:'',serviceType:'',clientId:''});
  const [offset,setOffset]=useState(0),[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[detail,setDetail]=useState<any>(null),[options,setOptions]=useState<any>({zones:[]});
  const revision=useRef(0);const [navigation,setNavigation]=useState(0);
  const allowed=(p:string)=>permissions.includes(p);
  async function load(){const sequence=++revision.current;setBusy(true);setError('');try{
    const query=new URLSearchParams({limit:'25',offset:String(offset),...Object.fromEntries(Object.entries(filters).filter(([,v])=>v))});
    const result=await apiFetch<any>(`/v1/admin/fiscal/${tab}?${query}`,token);if(sequence===revision.current)setData(result);
  }catch(e){if(sequence===revision.current)setError(fiscalMessage(e));}finally{if(sequence===revision.current)setBusy(false);}}
  useEffect(()=>{void load();return()=>{revision.current++;};},[tab,offset,token,navigation]);
  useEffect(()=>{if(allowed('FACTURACION_DASHBOARD_VER'))void apiFetch<any>('/v1/admin/fiscal/options',token).then(setOptions).catch(()=>{});},[token]);
  function navigate(next:Tab,extra:Partial<typeof filters>={}){setFilters(v=>({...v,status:'',search:'',clientId:'',...(next==='clients'?{source:'',zoneId:'',serviceType:''}:{}),...extra}));setOffset(0);setData(null);setTab(next);setNavigation(n=>n+1);}
  async function open(kind:'clients'|'invoices',id:string){setBusy(true);try{const result=await apiFetch<any>(`/v1/admin/fiscal/${kind}/${id}`,token);setDetail({kind,id,...result});}catch(e){setError(fiscalMessage(e));}finally{setBusy(false);}}
  function period(value:string){if(value==='custom')return;const now=new Date(`${today()}T12:00:00-05:00`),start=new Date(now);if(value==='week')start.setDate(now.getDate()-6);if(value==='month')start.setDate(1);if(value==='quarter'){start.setDate(1);start.setMonth(Math.floor(now.getMonth()/3)*3);}if(value==='year'){start.setDate(1);start.setMonth(0);}setFilters({...filters,start:start.toLocaleDateString('en-CA'),end:today()});}
  const rows=data?.items??[];
  const kpis=data&&tab==='dashboard'?[
    ['Total cobrado',money(data.collected),'payments','COLLECTED'],['Total facturado',money(data.invoiced),'invoices','AUTORIZADA'],['Pendiente de facturar',money(data.pendingAmount),'payments','UNBILLED'],
    ['Subtotal facturado',money(data.subtotal),'invoices','AUTORIZADA'],['IVA generado',money(data.tax),'invoices','AUTORIZADA'],['Facturas',data.invoiceCount,'invoices',''],
    ['Autorizadas',data.authorizedCount,'invoices','AUTORIZADA'],['Pendientes',data.pendingCount,'invoices','PENDING_ALL'],['Rechazadas',data.rejectedCount,'invoices','RECHAZADA'],['Con error',data.errorCount,'invoices','ERROR'],
    ['Clientes fiscales activos',data.clients?.active??0,'clients',''],['Nuevos clientes fiscales',data.clients?.new??0,'clients',''],
  ]:[];
  return <div className="fiscal-admin"><nav className="fiscal-tabs" aria-label="Facturación">{tabs.filter(t=>allowed(t[2])).map(([id,label])=><button key={id} className={tab===id?'primary':'secondary'} onClick={()=>navigate(id)}>{label}</button>)}</nav>
    <div className="fiscal-note">Los clientes y datos fiscales están activos. Un pago aprobado no es una factura autorizada. La emisión electrónica permanece pendiente de contratar y configurar un proveedor.</div>
    {tab!=='config'&&<form className="card fiscal-filters" onSubmit={e=>{e.preventDefault();if(offset)setOffset(0);else void load();}}>
      <label>Período<select defaultValue="month" onChange={e=>period(e.target.value)}><option value="today">Hoy</option><option value="week">Últimos 7 días</option><option value="month">Mes</option><option value="quarter">Trimestre</option><option value="year">Año</option><option value="custom">Personalizado</option></select></label>
      <label>Desde<input type="date" value={filters.start} max={filters.end} onChange={e=>setFilters({...filters,start:e.target.value})}/></label><label>Hasta<input type="date" value={filters.end} min={filters.start} onChange={e=>setFilters({...filters,end:e.target.value})}/></label>
      {tab!=='clients'&&<><label>Origen<select value={filters.source} onChange={e=>setFilters({...filters,source:e.target.value})}><option value="">Todos</option>{Object.entries(sourceNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
      <label>Estado fiscal<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Todos</option>{Object.entries(statusNames).filter(([k])=>k==='PENDING_ALL'?tab==='invoices':['COLLECTED','UNBILLED'].includes(k)?tab==='payments':true).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></>}
      {tab==='dashboard'&&<><label>Zona<select value={filters.zoneId} onChange={e=>setFilters({...filters,zoneId:e.target.value})}><option value="">Todas / sin zona</option>{options.zones?.map((z:any)=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label><label>Servicio<select value={filters.serviceType} onChange={e=>setFilters({...filters,serviceType:e.target.value})}><option value="">Todos</option>{Object.entries(sourceNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></>}
      {tab!=='dashboard'&&<label>Buscar<input placeholder="Nombre, identificación o referencia" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label>}
      <button className="primary" disabled={busy}>Aplicar filtros</button>{filters.clientId&&<button className="secondary" type="button" onClick={()=>navigate(tab,{clientId:''})}>Quitar filtro de cliente</button>}
    </form>}
    {busy&&<p role="status">Consultando información…</p>}{error&&<p role="alert" className="alert error">{error}</p>}
    {tab==='dashboard'&&data&&<><div className="fiscal-kpis">{kpis.map(([label,value,target,status])=><button key={label} onClick={()=>navigate(target as Tab,{status,search:'',...(label==='Clientes fiscales activos'?{start:'',end:''}:{})})}><span>{label}</span><strong>{value}</strong></button>)}</div>
      <div className="card"><h3>Indicadores complementarios</h3><div className="fiscal-detail-grid"><span><small>Ticket promedio autorizado</small>{money(data.averageTicket)}</span><span><small>Facturación promedio por cliente</small>{money(data.averagePerClient)}</span><span><small>Facturas promedio por cliente</small>{Number(data.averageInvoicesPerClient).toFixed(2)}</span><span><small>Promedio facturado por conductor</small>{money(data.averagePerDriver)}</span><span><small>Promedio facturado por comercio</small>{money(data.averagePerBusiness)}</span><span><small>Clientes recurrentes en el período</small>{data.recurringClients}</span><span><small>Notas de crédito autorizadas</small>{data.creditNotes?.count??0} · {money(data.creditNotes?.amount??0)}</span></div><p className="fiscal-empty">{data.clientMetricsScope}</p></div>
      <div className="fiscal-charts">{[['Por día','byDay'],['Por mes','byMonth'],['Por origen','bySource'],['Por servicio','byService'],['Por estado','byStatus'],['Altas fiscales por día','newClients'],['Top clientes por facturación','topClients']] .map(([title = '',key = ''])=><section className="card" key={key}><h3>{title}</h3>{data[key]?.length?data[key].map((r:any)=><div className="fiscal-chart-row" key={r.label}><span>{key==='topClients'&&r.clientId&&allowed('CLIENTES_FISCALES_VER')?<button className="secondary" onClick={()=>void open('clients',r.clientId)}>{r.label}</button>:sourceNames[r.label]??statusNames[r.label]??r.label}</span><strong>{['byStatus','newClients'].includes(key)?r.value:money(r.value)}</strong><meter aria-label={`${title}: ${r.label}`} min={0} max={Math.max(...data[key].map((v:any)=>v.value),1)} value={r.value}/></div>):<Empty/>}</section>)}</div></>}
    {['clients','invoices','payments'].includes(tab)&&data&&<section className="card"><div className="table-wrap fiscal-table"><table><thead><tr>{(tab==='clients'?['Cliente / razón social','Identificación','Correo','Origen','Estado','Registro / actualización','Acción']:tab==='invoices'?['Documento','Cliente','Concepto / origen','Subtotal','IVA','Total','Estado / proveedor','Emisión / autorización','Acción']:['Pago','Cliente','Origen','Monto','Estado fiscal','Fecha','Acción']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>
      {rows.map((r:any)=><tr key={r.id}>{tab==='clients'?<><td>{r.legalName??'Datos fiscales pendientes'}</td><td>{r.identificationType==='CEDULA'?'Cédula':r.identificationType} {r.identification??'—'}</td><td>{r.billingEmail??'—'}</td><td>{String(r.origin??'').split(', ').map(v=>entityNames[v]??v).join(', ')}</td><td>{r.active?'Activo':'Inactivo'}</td><td>{date(r.createdAt)}<small>{date(r.updatedAt)}</small></td><td><button onClick={()=>void open('clients',r.id)}>Ver detalle</button></td></>:tab==='invoices'?<><td>{r.number??'Sin número fiscal'}<small>{r.reference}</small></td><td>{r.profile?.legalName??'Histórico sin perfil'}<small>{r.profile?.identification}</small></td><td>{r.concept}<small>{sourceNames[r.source]}</small></td><td>{money(r.subtotal)}</td><td>{money(r.tax)}</td><td>{money(r.total)}</td><td>{statusNames[r.status]}<small>{r.provider}</small></td><td>{date(r.issuedAt)}<small>{date(r.authorizedAt)}</small></td><td><button onClick={()=>void open('invoices',r.id)}>Ver detalle</button></td></>:<><td>{r.paymentId}<small>{r.reversed?'Pago revertido · no suma en cobrado':'Pago confirmado'}</small></td><td>{r.profile?.legalName??'Histórico sin perfil'}</td><td>{sourceNames[r.source]}</td><td>{money(r.amount)}</td><td>{statusNames[r.billingStatus]}</td><td>{date(r.paidAt)}</td><td>{r.invoiceId?<button onClick={()=>void open('invoices',r.invoiceId)}>Ver documento</button>:'Preparando registro'}</td></>}</tr>)}
    </tbody></table></div>{!rows.length&&<Empty/>}<div className="fiscal-pager"><button className="secondary" disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Anterior</button><span>{data.total} registros · página {offset/25+1}</span><button className="secondary" disabled={busy||offset+25>=data.total} onClick={()=>setOffset(offset+25)}>Siguiente</button></div></section>}
    {tab==='config'&&data&&<section className="card"><h2>Preparación de facturación electrónica</h2><p>Los adaptadores todavía no realizan llamadas externas, incluso si alguien activa la variable por error.</p><dl><dt>Datos fiscales</dt><dd>Activos</dd><dt>Emisión electrónica</dt><dd>{data.emissionAvailable?'Habilitada':'Desactivada / pendiente de integración'}</dd><dt>Proveedor previsto</dt><dd>{data.provider}</dd><dt>Ambiente</dt><dd>{data.environment==='TEST'?'Pruebas':'Producción'}</dd><dt>Envío futuro de correo</dt><dd>{data.emailMode==='PROVIDER'?'A cargo del proveedor':'Correo corporativo'}</dd></dl><p>La configuración de despliegue mantiene FACTURACION_ENABLED=false. Para habilitar la emisión se necesita completar el adaptador, credenciales, emisor, impuestos y pruebas con el proveedor. Los valores de IVA no se inventan ni se descuentan de los pagos actuales.</p><p>XML, RIDE, reintentos y notas de crédito se habilitarán cuando exista un proveedor real.</p></section>}
    {detail&&<div className="fiscal-modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setDetail(null);}}><section className="fiscal-modal" role="dialog" aria-modal="true" aria-label="Detalle fiscal"><button className="secondary fiscal-close" aria-label="Cerrar" onClick={()=>setDetail(null)}>×</button>
      {detail.kind==='clients'?<><h2>Cliente fiscal</h2><p>{detail.links.map((l:any)=>`${entityNames[l.type]??l.type}: ${l.name??l.entityId}`).join(' · ')}</p><FiscalProfileCard key={detail.id} endpoint={`/v1/admin/fiscal/clients/${detail.id}/profile`} token={token} editable={allowed('CLIENTES_FISCALES_EDITAR')} onSaved={()=>{void load();void open('clients',detail.id);}}/><div className="fiscal-actions">{allowed('FACTURACION_VER')&&<><button className="primary" onClick={()=>{navigate('payments',{clientId:detail.id,start:'',end:''});setDetail(null);}}>Consultar pagos</button><button className="secondary" onClick={()=>{navigate('invoices',{clientId:detail.id,start:'',end:''});setDetail(null);}}>Consultar facturas</button></>}</div><h3>Notas de crédito</h3>{detail.creditNotes.length?detail.creditNotes.map((n:any)=><p key={n.id}>{date(n.date)} · {money(n.amount)} · {statusNames[n.status]}</p>):<Empty/>}</>:<><h2>{detail.invoice.document_number??'Documento pendiente de emisión'}</h2><p className="fiscal-note">{statusNames[detail.invoice.status]}. Este registro no es una factura autorizada mientras no exista autorización real.</p><div className="fiscal-detail-grid">{Object.entries({Cliente:detail.invoice.fiscal_snapshot?.legalName,Identificación:detail.invoice.fiscal_snapshot?.identification,Dirección:detail.invoice.fiscal_snapshot?.address,Correo:detail.invoice.email_to,Concepto:detail.invoice.concept,Subtotal:money(detail.invoice.subtotal),IVA:money(detail.invoice.tax_amount),Total:money(detail.invoice.total),Origen:sourceNames[detail.invoice.source],Proveedor:detail.invoice.provider,Pago:detail.invoice.payment_id,'Clave de acceso':detail.invoice.access_key,Autorización:detail.invoice.authorization_number,'Fecha autorización':date(detail.invoice.authorized_at)}).map(([label,value])=><span key={label}><small>{label}</small>{String(value??'—')}</span>)}</div><div className="fiscal-actions">{['Descargar RIDE','Descargar XML','Reenviar factura','Consultar estado','Reintentar','Crear nota de crédito'].map(label=><button key={label} className="secondary" disabled title="Disponible cuando se integre un proveedor real">{label}</button>)}</div></>}
      <h3>Historial de auditoría · últimas 100 operaciones</h3>{detail.history.length?detail.history.map((h:any,i:number)=><p key={i}>{date(h.date)} · {h.event.replace(/([a-z])([A-Z])/g,'$1 $2')} · {h.result==='SUCCESS'?'Correcto':h.result}</p>):<Empty/>}
    </section></div>}
  </div>;
}
