import {useEffect,useRef,useState} from 'react';
import {apiFetch,apiUrl} from './api.js';
import {usePanelDialog,type PanelDialogField} from './panel-dialog.js';
import './fleet.css';
import {FleetReport} from './fleet-report.js';

const labels:Record<string,string>={PENDING:'En revisión',VERIFIED:'Verificada',SUSPENDED:'Suspendida',APPROVED:'Autorizado',REJECTED:'Rechazado',REVOKED:'Revocado',ACTIVE:'Activa',ENDED:'Finalizada',AUTHORIZED_DRIVER:'Conductor autorizado',OWNER_MANAGER:'Propietario / responsable',LEGACY_MIGRATION:'Migración histórica',USER_REQUEST:'Solicitud del usuario',ADMIN:'Administrador',MANAGER:'Responsable',MANUAL_SELECTION:'Selección manual',QR_SCAN:'Escaneo QR',RECOVERY:'Recuperación',ADMIN_ASSIGNED:'Asignación administrativa',MANUAL_RELEASE:'Fin de jornada',LOGOUT:'Cierre de sesión',AUTO_RELEASE:'Desconexión prolongada',TAKEOVER:'Relevo',VEHICLE_CHANGE:'Cambio de unidad',ADMIN_RELEASE:'Liberación administrativa',COMPLETED:'Finalizado',DRIVER_CANCELLED:'Cancelado por conductor',PASSENGER_CANCELLED:'Cancelado por pasajero',CANCELLED:'Cancelado',REASSIGNED:'Reasignado',INCIDENT:'Incidente',PHOTO:'Fotografía',REGISTRATION:'Matrícula',OPERATING_PERMIT:'Permiso de operación',OWNERSHIP_EVIDENCE:'Evidencia de propiedad'};
Object.assign(labels,{vehicle_created:'Unidad registrada',vehicle_updated:'Información actualizada',vehicle_verified:'Unidad verificada',vehicle_suspended:'Estado de unidad actualizado',vehicle_file_uploaded:'Documento recibido',driver_link_requested:'Autorización solicitada',driver_authorized:'Relación autorizada',driver_removed:'Relación retirada',session_started:'Jornada iniciada',session_ended:'Jornada finalizada',session_auto_released:'Jornada cerrada por inactividad',vehicle_takeover:'Relevo de conductor',vehicle_qr_generated:'QR generado',vehicle_qr_regenerated:'QR reemplazado',vehicle_qr_invalidated:'QR invalidado',vehicle_legacy_migrated:'Referencia histórica migrada',vehicle_ownership_claim_requested:'Responsabilidad reclamada',vehicle_ownership_claimed:'Responsable validado',vehicle_ownership_claim_rejected:'Reclamación rechazada',fleet_settings_updated:'Parámetros actualizados'});
const label=(v:unknown)=>v?labels[String(v)]??String(v).replaceAll('_',' '):'—';
const date=(v:unknown)=>v?new Date(String(v)).toLocaleString('es-EC',{dateStyle:'medium',timeStyle:'short'}):'—';
const money=(v:unknown)=>new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(Number(v??0)/100);
const base='/v1/admin/fleet';
function Photo({id,token}:{id?:string;token:string}){
  const [url,setUrl]=useState('');useEffect(()=>{let alive=true,object='';if(id)void fetch(apiUrl(`${base}/files/${id}`),{headers:{authorization:`Bearer ${token}`}})
    .then(r=>{if(!r.ok)throw Error();return r.blob();}).then(b=>{object=URL.createObjectURL(b);if(alive)setUrl(object);else URL.revokeObjectURL(object);}).catch(()=>{});
    return()=>{alive=false;if(object)URL.revokeObjectURL(object);};},[id,token]);
  return url?<img className="fleet-photo" src={url} alt="Fotografía real de la mototaxi"/>:<span className="fleet-photo fleet-placeholder" aria-label="Sin fotografía">▧</span>;
}
export function FleetAdmin({token,permissions,cooperativeScoped=false}:{token:string;permissions:string[];cooperativeScoped?:boolean}){
  const dialog=usePanelDialog();const [rows,setRows]=useState<any[]>([]),[page,setPage]=useState(0),[search,setSearch]=useState(''),[status,setStatus]=useState('');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[detail,setDetail]=useState<any>(null),[tab,setTab]=useState('info');
  const [detailPage,setDetailPage]=useState(0),[from,setFrom]=useState(''),[to,setTo]=useState(''),[qr,setQr]=useState<any>(null);
  const revision=useRef(0),mutation=useRef(false);const canManage=permissions.includes('fleet:manage');
  const call=(path:string,method='GET',body?:unknown)=>apiFetch<any>(base+path,token,{method,...(body===undefined?{}:{body:JSON.stringify(body)})});
  async function load(){const seq=++revision.current;setBusy(true);try{const d=await call(`/vehicles?${new URLSearchParams({search,page:String(page),status})}`);if(seq===revision.current)setRows(d.items);}catch(e){if(seq===revision.current)setError((e as Error).message);}finally{if(seq===revision.current)setBusy(false);}}
  useEffect(()=>{void load();return()=>{revision.current++;};},[page,status,token]);
  async function open(id:string,p=0){setBusy(true);setError('');try{const q=new URLSearchParams({page:String(p)});if(from)q.set('from',new Date(from+'T00:00:00-05:00').toISOString());if(to)q.set('to',new Date(to+'T23:59:59-05:00').toISOString());setDetail(await call(`/vehicles/${id}?${q}`));setDetailPage(p);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function mutate(action:()=>Promise<unknown>,success='Cambios guardados correctamente.'){
    if(mutation.current)return;mutation.current=true;setBusy(true);setError('');setNotice('');
    try{await action();setNotice(success);if(detail)await open(detail.vehicle.id,detailPage);await load();return true;}catch(e){setError((e as Error).message);return false;}finally{mutation.current=false;setBusy(false);}
  }
  async function reason(title:string){return dialog.open({title,description:'Esta acción quedará registrada en la auditoría.',confirmLabel:'Confirmar',fields:[{name:'reason',label:'Motivo',required:true,minLength:5,type:'textarea'}]});}
  async function edit(v?:any){
    try{const options=await call('/options');
    const fields:PanelDialogField[]=[['identifier','Placa / registro'],['brand','Marca'],['model','Modelo'],['color','Color'],['unitNumber','Número de unidad'],['declaredOwnerName','Propietario declarado (puede no tener cuenta)']].map(([name,title])=>({name:name!,label:title!,required:name!=='unitNumber',initialValue:v?.[name!]??''}));
    fields.push({name:'maximumPassengers',label:'Máximo de pasajeros',type:'number',min:1,max:10,required:true,initialValue:v?.maximumPassengers??3});
    fields.push({name:'cooperativeId',label:'Cooperativa',type:'select',initialValue:v?.cooperativeId??'',options:[{value:'',label:'Independiente'},...options.cooperatives.map((c:any)=>({value:c.id,label:c.name}))]});
    const data=await dialog.open({title:v?'Editar mototaxi':'Agregar mototaxi',size:'wide',confirmLabel:'Guardar',fields});if(!data)return;
    await mutate(()=>call(v?`/vehicles/${v.id}`:'/vehicles',v?'PUT':'POST',{...data,maximumPassengers:Number(data.maximumPassengers),cooperativeId:data.cooperativeId||null}));
    }catch(e){setError((e as Error).message);}
  }
  async function assign(){const find=await dialog.open({title:'Buscar persona',fields:[{name:'search',label:'Nombre o correo',required:true,minLength:3}]});if(!find)return;
    try{const options=await call(`/options?search=${encodeURIComponent(String(find.search))}`);if(!options.users.length){setNotice('No se encontraron cuentas con esos datos.');return;}
      const data=await dialog.open({title:'Autorizar persona',fields:[{name:'userId',label:'Cuenta',type:'select',required:true,initialValue:options.users[0]?.id??'',options:options.users.map((u:any)=>({value:u.id,label:`${u.name} · ${u.email}`}))},{name:'type',label:'Relación',type:'select',initialValue:'AUTHORIZED_DRIVER',options:[{value:'AUTHORIZED_DRIVER',label:'Conductor autorizado'},{value:'OWNER_MANAGER',label:'Propietario / responsable'}]},{name:'reason',label:'Motivo de autorización',required:true,minLength:5}]});
      if(data)await mutate(()=>call(`/vehicles/${detail.vehicle.id}/relations`,'PUT',{...data,status:'APPROVED'}));
    }catch(e){setError((e as Error).message);}
  }
  async function file(id:string){setBusy(true);try{const r=await fetch(apiUrl(`${base}/files/${id}?original=true`),{headers:{authorization:`Bearer ${token}`}});if(!r.ok)throw Error('No fue posible abrir el documento.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`mototaxi-${id}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function upload(file:File,kind:string){if(file.size>5*1024*1024){setError('El archivo supera 5 MB.');return;}const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]!);r.onerror=reject;r.readAsDataURL(file);});await mutate(()=>call(`/vehicles/${detail.vehicle.id}/files`,'POST',{kind,mimeType:file.type,data}));}
  async function settings(){try{const current=await call('/settings');const data=await dialog.open({title:'Jornadas y conexión',description:'Estos tiempos no liberan unidades con carreras activas o incidencias pendientes.',fields:[
    {name:'heartbeatSeconds',label:'Latido (segundos)',type:'number',min:10,max:120,initialValue:current.heartbeatSeconds,required:true},
    {name:'offlineSeconds',label:'Sin conexión desde (segundos)',type:'number',min:30,max:1800,initialValue:current.offlineSeconds,required:true},
    {name:'autoReleaseSeconds',label:'Liberar jornada inactiva después de (segundos)',type:'number',min:60,max:86400,initialValue:current.autoReleaseSeconds,required:true}, {name:'ownerNotifications',label:'Habilitar avisos de actividad para responsables',type:'checkbox',initialValue:current.ownerNotifications}
  ]});if(data)await mutate(()=>call('/settings','PUT',data));}catch(e){setError((e as Error).message);}}
  async function qrAction(regenerate=false){const confirmation=regenerate?await reason('¿Reemplazar QR? El anterior dejará de funcionar.'):null;if(regenerate&&!confirmation)return;
    setBusy(true);try{setQr(await call(`/vehicles/${detail.vehicle.id}/qr`,'POST',{regenerate,reason:confirmation?.reason??'Generación inicial'}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function downloadQr(){try{
    const response=await fetch('/costa-go-emblem.png');if(!response.ok)throw Error('No se pudo cargar el logo oficial.');
    const logo=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;void response.blob().then(b=>reader.readAsDataURL(b));});
    const escape=(value:string)=>value.replace(/[<>&"']/g,'');
    const text=`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="850"><rect width="600" height="850" rx="28" fill="white"/><image href="${logo}" x="180" y="12" width="240" height="105"/><text x="300" y="145" text-anchor="middle" font-family="sans-serif" font-size="24" fill="#07344e">UNIDAD VERIFICADA</text><g transform="translate(44,160)">${qr.svg.replace(/<\?xml[^>]*>/,'')}</g><text x="300" y="721" text-anchor="middle" font-family="sans-serif" font-size="36">${escape(detail.vehicle.identifier)}</text><text x="300" y="766" text-anchor="middle" font-family="sans-serif" font-size="24">${escape(detail.vehicle.color??'')}</text><text x="300" y="817" text-anchor="middle" font-family="sans-serif" font-size="20">Tu seguridad es nuestra prioridad</text></svg>`;
    const url=URL.createObjectURL(new Blob([text],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download=`QR-${detail.vehicle.identifier}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }catch(e){setError((e as Error).message);}}
  return <section className="fleet-admin">
    <FleetReport token={token} onVehicle={id=>{setTab('sessions');void open(id);}}/>
    <div className="fleet-toolbar"><div><h2>Mototaxis</h2><p>Unidades, autorizaciones y jornadas. Las membresías pertenecen al conductor.</p></div>{canManage&&<>{!cooperativeScoped&&<button className="secondary" onClick={()=>void settings()}>Conexión y jornadas</button>}<button className="primary" onClick={()=>void edit()}>+ Agregar mototaxi</button></>}</div>
    {error&&<p className="alert error" role="alert">{error}</p>}{notice&&<p className="note" role="status">{notice}</p>}
    <form className="fleet-toolbar" onSubmit={e=>{e.preventDefault();setPage(0);void load();}}><input aria-label="Buscar mototaxi" placeholder="Placa o número de unidad" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Estado" value={status} onChange={e=>{setPage(0);setStatus(e.target.value);}}>{['','PENDING','VERIFIED','SUSPENDED'].map(s=><option key={s} value={s}>{s?label(s):'Todos los estados'}</option>)}</select><button className="secondary" disabled={busy}>Buscar</button></form>
    <div className="card table-wrap"><table><thead><tr>{['Mototaxi','Cooperativa','Propietario declarado','Conductor actual','Estado','Última conexión',''].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(v=><tr key={v.id}><td><div className="fleet-identity"><Photo id={v.photoId} token={token}/><div><strong>{v.identifier}</strong><small>{v.brand} {v.model} · {v.color}</small></div></div></td><td>{v.cooperative??'Independiente'}</td><td>{v.declaredOwnerName??'Sin validar'}</td><td>{v.currentDriverName??'Sin jornada'}<small>{v.available?'Disponible':'No disponible'}</small></td><td>{label(v.status)}</td><td>{date(v.lastHeartbeat)}</td><td><button className="secondary" disabled={busy} onClick={()=>{setTab('info');setQr(null);void open(v.id);}}>Ver detalle</button></td></tr>)}</tbody></table>{!rows.length&&!busy&&<p className="empty">No hay mototaxis con estos filtros.</p>}</div>
    <div className="fleet-toolbar"><button className="secondary" disabled={busy||page===0} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page+1} · {rows[0]?.totalCount??0} unidades</span><button className="secondary" disabled={busy||rows.length<30} onClick={()=>setPage(p=>p+1)}>Siguiente</button>{busy&&<span role="status">Cargando…</span>}</div>
    {detail&&<div className="fleet-overlay"><section className="card fleet-dialog" role="dialog" aria-modal="true" aria-label={`Mototaxi ${detail.vehicle.identifier}`}><div className="fleet-toolbar"><h2>Mototaxi {detail.vehicle.identifier}</h2><button className="secondary" disabled={busy} onClick={()=>{setDetail(null);setQr(null);}}>Cerrar</button></div>
      {error&&<p className="alert error" role="alert">{error}</p>}{notice&&<p className="note" role="status">{notice}</p>}
      <nav className="fleet-tabs">{[['info','Información'],['relations','Autorizaciones'],['sessions','Jornadas'],['trips','Viajes'],['files','Documentos'],['qr','QR'],['history','Auditoría']].map(([key,title])=><button key={key} className={tab===key?'primary':'secondary'} onClick={()=>setTab(key!)}>{title}</button>)}</nav>
      {tab==='info'&&<><div className="fleet-identity"><Photo id={detail.vehicle.photoId} token={token}/><div><h3>{detail.vehicle.brand} {detail.vehicle.model}</h3><p>{detail.vehicle.color} · Unidad {detail.vehicle.unitNumber??'sin número'}</p><p>{label(detail.vehicle.status)} · {detail.vehicle.maximumPassengers} pasajeros</p><p>Propietario declarado: {detail.vehicle.declaredOwnerName??'No registrado'}</p></div></div>{detail.current&&<p>Conductor actual: <strong>{detail.current.driverName}</strong> · Inicio: {date(detail.current.startedAt)} · Última conexión: {date(detail.current.lastHeartbeat)}</p>}{canManage&&<div className="fleet-toolbar"><button className="secondary" disabled={busy} onClick={()=>void edit(detail.vehicle)}>Editar información</button>{['VERIFIED','SUSPENDED','PENDING'].map(s=><button className="secondary" disabled={busy||s===detail.vehicle.status} key={s} onClick={async()=>{const data=await reason(`Cambiar estado a ${label(s)}`);if(data)await mutate(()=>call(`/vehicles/${detail.vehicle.id}/status`,'PUT',{status:s,reason:data.reason}));}}>{label(s)}</button>)}</div>}</>}
      {tab==='relations'&&<>{canManage&&<button className="primary" disabled={busy} onClick={()=>void assign()}>Autorizar persona</button>}{detail.relations.map((r:any)=><div className="fleet-row" key={r.id}><div><strong>{r.name}</strong><small>{label(r.type)} · {label(r.status)} · {label(r.source)}</small></div>{canManage&&['APPROVED','REJECTED','REVOKED'].filter(s=>s!==r.status).map(s=><button key={s} className="secondary" disabled={busy} onClick={async()=>{const data=await reason(`${label(s)}: ${r.name}`);if(data)await mutate(()=>call(`/vehicles/${detail.vehicle.id}/relations`,'PUT',{userId:r.userId,type:r.type,status:s,reason:data.reason}));}}>{label(s)}</button>)}</div>)}{detail.claims.map((c:any)=><div className="fleet-row" key={c.id}><span>Reclamación de {c.name} · {label(c.status)}</span><button className="secondary" onClick={()=>void file(c.evidenceId)}>Evidencia</button>{c.status==='PENDING'&&canManage&&[true,false].map(approved=><button className="secondary" key={String(approved)} onClick={async()=>{const data=await reason(approved?'Validar responsable':'Rechazar reclamación');if(data)await mutate(()=>call(`/ownership-claims/${c.id}/review`,'POST',{approved,reason:data.reason}));}}>{approved?'Validar':'Rechazar'}</button>)}</div>)}</>}
      {['sessions','trips'].includes(tab)&&<><form className="fleet-toolbar" onSubmit={e=>{e.preventDefault();void open(detail.vehicle.id,0);}}><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="secondary">Filtrar período</button></form>{detail[tab].map((r:any)=><article className="fleet-row" key={r.id}><div><strong>{r.driverName}</strong><small>{date(r.startedAt??r.acceptedAt)} → {date(r.endedAt)}</small><small>{label(r.status??r.outcome)} · {label(r.endReason)}</small><small>{tab==='sessions'?`${r.received} recibidos · ${r.accepted} aceptados · ${r.completed} finalizados · ${r.driverCancelled} cancelados por conductor · ${r.passengerCancelled} por pasajero · ${Math.round(r.durationSeconds/60)} min`:r.vehicle?.identifier}</small><small>{(Number(r.distanceMeters)/1000).toFixed(2)} km · {money(r.totalCents)}</small></div>{tab==='sessions'&&r.status==='ACTIVE'&&canManage&&<button className="secondary" disabled={busy} onClick={async()=>{const data=await reason('Liberar jornada de forma administrativa');if(data)await mutate(()=>call(`/sessions/${r.id}/release`,'POST',{reason:'ADMIN_RELEASE',note:data.reason}));}}>Liberar jornada</button>}</article>)}</>}
      {tab==='files'&&<>{canManage&&<div className="fleet-toolbar">{['PHOTO','REGISTRATION','OPERATING_PERMIT'].map(kind=><label key={kind}>{label(kind)}<input type="file" disabled={busy} accept={kind==='PHOTO'?'image/jpeg,image/png':'image/jpeg,image/png,application/pdf'} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,kind);e.target.value='';}}/></label>)}</div>}{detail.files.map((f:any)=><div className="fleet-row" key={f.id}><span>{label(f.kind)} · {date(f.createdAt)}</span><button className="secondary" onClick={()=>void file(f.id)}>Descargar original</button></div>)}</>}
      {tab==='qr'&&<><p>El QR identifica la unidad; no concede permiso para conducirla. Solo conductores autorizados pueden utilizarla.</p><div className="fleet-toolbar"><button className="primary" disabled={busy} onClick={()=>void qrAction()}>Consultar / generar QR</button><button className="secondary" disabled={busy} onClick={()=>void qrAction(true)}>Reemplazar QR</button><button className="secondary" disabled={busy} onClick={async()=>{const data=await reason('Invalidar QR');if(data){if(await mutate(()=>call(`/vehicles/${detail.vehicle.id}/qr`,'DELETE',data)))setQr(null);}}}>Invalidar QR</button></div>{qr&&<><div className="fleet-qr" id="fleet-print-qr"><img src="/costa-go-emblem.png" alt="Costa-Go"/><h3>Unidad verificada</h3><div dangerouslySetInnerHTML={{__html:qr.svg}}/><h2>{detail.vehicle.identifier}</h2><p>{detail.vehicle.color}</p><small>Tu seguridad es nuestra prioridad</small></div><div className="fleet-toolbar"><button className="primary" onClick={downloadQr}>Descargar QR</button><button className="secondary" onClick={()=>window.print()}>Imprimir QR</button></div></>}</>}
      {tab==='history'&&detail.history.map((h:any)=><div className="fleet-row" key={h.id}><div><strong>{label(h.action)}</strong><small>{date(h.occurredAt)} · {h.actor??'Sistema'}</small><p>{h.reason}</p></div></div>)}
      {['relations','sessions','trips','files','history'].includes(tab)&&!detail[tab]?.length&&<p className="empty">No hay registros en esta sección.</p>}
      {['sessions','trips','files','history'].includes(tab)&&<div className="fleet-toolbar"><button className="secondary" disabled={busy||detailPage===0} onClick={()=>void open(detail.vehicle.id,detailPage-1)}>Anterior</button><span>Página {detailPage+1}</span><button className="secondary" disabled={busy||detail[tab]?.length<30} onClick={()=>void open(detail.vehicle.id,detailPage+1)}>Siguiente</button></div>}
    </section></div>}{dialog.modal}
  </section>;
}
