import {ManagedTable} from './console-ui';
import {ecuDate} from './console-model';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {apiFetch,apiUrl} from './api.js';
import {usePanelDialog,type PanelDialogField} from './panel-dialog.js';
import './fleet.css';
import {FleetReport} from './fleet-report.js';
import {VehicleThumbnail as Photo} from './vehicle-thumbnail.js';
import {MototaxiIcon} from './mototaxi-icon.js';

const labels:Record<string,string>={PENDING:'En revisión',VERIFIED:'Verificada',SUSPENDED:'Suspendida',APPROVED:'Autorizado',REJECTED:'Rechazado',REVOKED:'Revocado',ACTIVE:'Activa',ENDED:'Finalizada',AUTHORIZED_DRIVER:'Conductor autorizado',OWNER_MANAGER:'Propietario / responsable',LEGACY_MIGRATION:'Migración histórica',USER_REQUEST:'Solicitud del usuario',ADMIN:'Administrador',MANAGER:'Responsable',MANUAL_SELECTION:'Selección manual',QR_SCAN:'Escaneo QR',RECOVERY:'Recuperación',ADMIN_ASSIGNED:'Asignación administrativa',MANUAL_RELEASE:'Fin de jornada',LOGOUT:'Cierre de sesión',AUTO_RELEASE:'Desconexión prolongada',TAKEOVER:'Relevo',VEHICLE_CHANGE:'Cambio de unidad',ADMIN_RELEASE:'Liberación administrativa',COMPLETED:'Finalizado',DRIVER_CANCELLED:'Cancelado por conductor',PASSENGER_CANCELLED:'Cancelado por pasajero',CANCELLED:'Cancelado',REASSIGNED:'Reasignado',INCIDENT:'Incidente',PHOTO:'Fotografía',REGISTRATION:'Matrícula',OPERATING_PERMIT:'Anexos',OWNERSHIP_EVIDENCE:'Evidencia de propiedad'};
Object.assign(labels,{vehicle_created:'Unidad registrada',vehicle_updated:'Información actualizada',vehicle_verified:'Unidad verificada',vehicle_suspended:'Estado de unidad actualizado',vehicle_file_uploaded:'Documento recibido',driver_link_requested:'Autorización solicitada',driver_authorized:'Relación autorizada',driver_removed:'Relación retirada',session_started:'Jornada iniciada',session_ended:'Jornada finalizada',session_auto_released:'Jornada cerrada por inactividad',vehicle_takeover:'Relevo de conductor',vehicle_qr_generated:'QR generado',vehicle_qr_regenerated:'QR reemplazado',vehicle_qr_invalidated:'QR invalidado',vehicle_legacy_migrated:'Referencia histórica migrada',vehicle_ownership_claim_requested:'Responsabilidad reclamada',vehicle_ownership_claimed:'Responsable validado',vehicle_ownership_claim_rejected:'Reclamación rechazada',fleet_settings_updated:'Parámetros actualizados'});
const label=(value:unknown)=>value?labels[String(value)]??String(value).replaceAll('_',' '):'—';
const date=ecuDate;
const money=(value:unknown)=>new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD'}).format(Number(value??0)/100);
const base='/v1/admin/fleet';
const tabs=[['info','Información','ⓘ'],['relations','Autorizaciones','♙'],['sessions','Jornadas','▣'],['trips','Viajes','▰'],['files','Documentos','▤'],['qr','QR','⌗'],['history','Auditoría','◷']] as const;

function StateBadge({value}:{value:string}){const tone=value==='VERIFIED'||value==='APPROVED'||value==='ACTIVE'?'success':value==='SUSPENDED'||value==='REJECTED'||value==='REVOKED'?'danger':'warning';return <span className={`fleet-badge fleet-badge-${tone}`}><i/>{label(value)}</span>;}
function EmptyState({icon='◇',title,children,action}:{icon?:string;title:string;children:ReactNode;action?:ReactNode}){return <div className="fleet-empty"><span aria-hidden="true">{icon}</span><strong>{title}</strong><p>{children}</p>{action}</div>;}
function Panel({title,icon,children,className=''}:{title:string;icon?:string;children:ReactNode;className?:string}){return <section className={`fleet-panel ${className}`}><h3>{icon&&<span aria-hidden="true">{icon}</span>}{title}</h3>{children}</section>;}

export function FleetAdmin({token,permissions,cooperativeScoped=false}:{token:string;permissions:string[];cooperativeScoped?:boolean}){
  const dialog=usePanelDialog();
  const [rows,setRows]=useState<any[]>([]),[page,setPage]=useState(0),[search,setSearch]=useState(''),[status,setStatus]=useState('');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[detail,setDetail]=useState<any>(null),[tab,setTab]=useState('info');
  const [detailPage,setDetailPage]=useState(0),[from,setFrom]=useState(''),[to,setTo]=useState(''),[qr,setQr]=useState<any>(null);
  const revision=useRef(0),mutation=useRef(false),canManage=permissions.includes('fleet:manage');
  const call=(path:string,method='GET',body?:unknown)=>apiFetch<any>(base+path,token,{method,...(body===undefined?{}:{body:JSON.stringify(body)})});
  async function load(){const seq=++revision.current;setBusy(true);try{const data=await call(`/vehicles?${new URLSearchParams({search,page:String(page),status})}`);if(seq===revision.current)setRows(data.items);}catch(reason){if(seq===revision.current)setError((reason as Error).message);}finally{if(seq===revision.current)setBusy(false);}}
  useEffect(()=>{void load();return()=>{revision.current++;};},[page,status,token]);
  async function open(id:string,p=0){setBusy(true);setError('');try{const query=new URLSearchParams({page:String(p)});if(from)query.set('from',new Date(from+'T00:00:00-05:00').toISOString());if(to)query.set('to',new Date(to+'T23:59:59-05:00').toISOString());setDetail(await call(`/vehicles/${id}?${query}`));setDetailPage(p);}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}
  async function mutate(action:()=>Promise<unknown>,success='Cambios guardados correctamente.'){if(mutation.current)return;mutation.current=true;setBusy(true);setError('');setNotice('');try{await action();setNotice(success);if(detail)await open(detail.vehicle.id,detailPage);await load();return true;}catch(reason){setError((reason as Error).message);return false;}finally{mutation.current=false;setBusy(false);}}
  async function reason(title:string){return dialog.open({title,description:'Esta acción quedará registrada en la auditoría.',confirmLabel:'Confirmar',fields:[{name:'reason',label:'Motivo',required:true,minLength:5,type:'textarea'}]});}
  async function edit(vehicle?:any){try{const options=await call('/options');const fields:PanelDialogField[]=[['identifier','Placa / registro'],['brand','Marca'],['model','Modelo'],['color','Color'],['unitNumber','Número de unidad'],['declaredOwnerName','Propietario declarado (puede no tener cuenta)']].map(([name,title])=>({name:name!,label:title!,required:name!=='unitNumber',initialValue:vehicle?.[name!]??''}));fields.push({name:'maximumPassengers',label:'Máximo de pasajeros',type:'number',min:1,max:10,required:true,initialValue:vehicle?.maximumPassengers??3},{name:'cooperativeId',label:'Cooperativa',type:'select',initialValue:vehicle?.cooperativeId??'',options:[{value:'',label:'Independiente'},...options.cooperatives.map((item:any)=>({value:item.id,label:item.name}))]});const data=await dialog.open({title:vehicle?'Editar mototaxi':'Agregar mototaxi',size:'wide',confirmLabel:'Guardar',fields});if(data)await mutate(()=>call(vehicle?`/vehicles/${vehicle.id}`:'/vehicles',vehicle?'PUT':'POST',{...data,maximumPassengers:Number(data.maximumPassengers),cooperativeId:data.cooperativeId||null}));}catch(reason){setError((reason as Error).message);}}
  async function assign(){const find=await dialog.open({title:'Buscar persona',fields:[{name:'search',label:'Nombre o correo',required:true,minLength:3}]});if(!find)return;try{const options=await call(`/options?search=${encodeURIComponent(String(find.search))}`);if(!options.users.length){setNotice('No se encontraron cuentas con esos datos.');return;}const data=await dialog.open({title:'Autorizar persona',fields:[{name:'userId',label:'Cuenta',type:'select',required:true,initialValue:options.users[0]?.id??'',options:options.users.map((user:any)=>({value:user.id,label:`${user.name} · ${user.email}`}))},{name:'type',label:'Relación',type:'select',initialValue:'AUTHORIZED_DRIVER',options:[{value:'AUTHORIZED_DRIVER',label:'Conductor autorizado'},{value:'OWNER_MANAGER',label:'Propietario / responsable'}]},{name:'reason',label:'Motivo de autorización',required:true,minLength:5}]});if(data)await mutate(()=>call(`/vehicles/${detail.vehicle.id}/relations`,'PUT',{...data,status:'APPROVED'}));}catch(reason){setError((reason as Error).message);}}
  async function accessFile(id:string,download=false){setBusy(true);try{const response=await fetch(apiUrl(`${base}/files/${id}?original=true`),{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw Error('No fue posible abrir el documento.');const url=URL.createObjectURL(await response.blob());if(download){const anchor=document.createElement('a');anchor.href=url;anchor.download=`mototaxi-${id}`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}else{window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);}}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}
  async function upload(source:File,kind?:string){if(!kind)return;if(source.size>5*1024*1024){setError('El archivo supera 5 MB.');return;}const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]!);reader.onerror=reject;reader.readAsDataURL(source);});await mutate(()=>call(`/vehicles/${detail.vehicle.id}/files`,'POST',{kind,mimeType:source.type,data}),'Documento recibido correctamente.');}
  async function settings(){try{const current=await call('/settings');const data=await dialog.open({title:'Jornadas y conexión',description:'Estos tiempos no liberan unidades con carreras activas o incidencias pendientes.',fields:[{name:'heartbeatSeconds',label:'Latido (segundos)',type:'number',min:10,max:120,initialValue:current.heartbeatSeconds,required:true},{name:'offlineSeconds',label:'Sin conexión desde (segundos)',type:'number',min:30,max:1800,initialValue:current.offlineSeconds,required:true},{name:'autoReleaseSeconds',label:'Liberar jornada inactiva después de (segundos)',type:'number',min:60,max:86400,initialValue:current.autoReleaseSeconds,required:true},{name:'ownerNotifications',label:'Habilitar avisos de actividad para responsables',type:'checkbox',initialValue:current.ownerNotifications}]});if(data)await mutate(()=>call('/settings','PUT',data));}catch(reason){setError((reason as Error).message);}}
  async function qrAction(regenerate=false){const confirmation=regenerate?await reason('¿Reemplazar QR? El anterior dejará de funcionar.'):null;if(regenerate&&!confirmation)return;setBusy(true);try{setQr(await call(`/vehicles/${detail.vehicle.id}/qr`,'POST',{regenerate,reason:confirmation?.reason??'Generación inicial'}));}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}
  async function downloadQr(){try{const response=await fetch('/costa-go-emblem.png');if(!response.ok)throw Error('No se pudo cargar el logo oficial.');const logo=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;void response.blob().then(blob=>reader.readAsDataURL(blob));});const escape=(value:string)=>value.replace(/[<>&"']/g,'');const text=`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="850"><rect width="600" height="850" rx="28" fill="white"/><image href="${logo}" x="180" y="12" width="240" height="105"/><text x="300" y="145" text-anchor="middle" font-family="sans-serif" font-size="24" fill="#07344e">UNIDAD VERIFICADA</text><g transform="translate(44,160)">${qr.svg.replace(/<\?xml[^>]*>/,'')}</g><text x="300" y="721" text-anchor="middle" font-family="sans-serif" font-size="36">${escape(detail.vehicle.identifier)}</text><text x="300" y="766" text-anchor="middle" font-family="sans-serif" font-size="24">${escape(detail.vehicle.color??'')}</text><text x="300" y="817" text-anchor="middle" font-family="sans-serif" font-size="20">Tu seguridad es nuestra prioridad</text></svg>`;const url=URL.createObjectURL(new Blob([text],{type:'image/svg+xml'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`QR-${detail.vehicle.identifier}.svg`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(reason){setError((reason as Error).message);}}
  async function changeStatus(next:string){const data=await reason(`Cambiar estado a ${label(next)}`);if(data)await mutate(()=>call(`/vehicles/${detail.vehicle.id}/status`,'PUT',{status:next,reason:data.reason}));}
  const close=()=>{setDetail(null);setQr(null);setNotice('');setError('');};
  const goto=(next?:string)=>{if(next)setTab(next);};
  const filesByKind=(kind?:string):any=>detail?.files?.filter((item:any)=>item.kind===kind)??[];

  const periodControls=()=> <form className="fleet-period" onSubmit={event=>{event.preventDefault();void open(detail.vehicle.id,0);}}><label>Desde<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button className="secondary">Filtrar</button></form>;
  const period=periodControls();
  return <section className="fleet-admin">
    <FleetReport token={token} onVehicle={id=>{setTab('sessions');void open(id);}}/>
    <div className="fleet-toolbar"><div><h2 className="fleet-heading"><MototaxiIcon/> Mototaxis</h2><p>Unidades, autorizaciones y jornadas. Las membresías pertenecen al conductor.</p></div>{canManage&&<>{!cooperativeScoped&&<button className="secondary" onClick={()=>void settings()}>Conexión y jornadas</button>}<button className="primary" onClick={()=>void edit()}>+ Agregar mototaxi</button></>}</div>
    {error&&<p className="alert error" role="alert">{error}</p>}{notice&&<p className="note" role="status">{notice}</p>}
    <form className="fleet-toolbar" onSubmit={event=>{event.preventDefault();setPage(0);void load();}}><input aria-label="Buscar mototaxi" placeholder="Placa o número de unidad" value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label="Estado" value={status} onChange={event=>{setPage(0);setStatus(event.target.value);}}>{['','PENDING','VERIFIED','SUSPENDED'].map(value=><option key={value} value={value}>{value?label(value):'Todos los estados'}</option>)}</select><button className="secondary" disabled={busy}>Buscar</button></form>
    <div className="card table-wrap"><ManagedTable serverPaged className="fleet-units-table"><thead><tr>{['Mototaxi','Propietario / responsable','Conductor actual','Estado / jornada','Última actividad','Acciones'].map(title=><th key={title}>{title}</th>)}</tr></thead><tbody>{rows.map(vehicle=><tr key={vehicle.id}><td><div className="fleet-identity"><Photo id={vehicle.photoId} token={token}/><div><strong>{vehicle.identifier}</strong><small>{[vehicle.brand,vehicle.model].filter(Boolean).join(' ')||'Sin marca/modelo'}</small><small>{vehicle.color||'Color sin registrar'}{vehicle.unitNumber?` · Unidad ${vehicle.unitNumber}`:''}</small></div></div></td><td>{vehicle.declaredOwnerName||'Sin registrar'}<small>{vehicle.cooperative||'Independiente'}</small></td><td>{vehicle.currentDriverName||'Sin asignar'}</td><td><span className={`fleet-state ${vehicle.sessionId?'fleet-state-live':''}`}><i/>{vehicle.sessionId?'En jornada':'Sin jornada'}</span><small>{vehicle.available?'Disponible':'No disponible'}</small><small>{label(vehicle.status)}</small></td><td className="fleet-date">{date(vehicle.lastHeartbeat)}</td><td><button className="secondary" disabled={busy} onClick={()=>{setTab('info');setQr(null);void open(vehicle.id);}}>Ver detalle</button></td></tr>)}</tbody></ManagedTable>{!rows.length&&!busy&&<p className="empty">No hay mototaxis con estos filtros.</p>}</div>
    <div className="fleet-toolbar"><button className="secondary" disabled={busy||page===0} onClick={()=>setPage(value=>value-1)}>Anterior</button><span>Página {page+1} · {rows[0]?.totalCount??0} unidades</span><button className="secondary" disabled={busy||rows.length<30} onClick={()=>setPage(value=>value+1)}>Siguiente</button>{busy&&<span role="status">Cargando…</span>}</div>
    {detail&&<div className="fleet-overlay"><section className="card fleet-dialog" role="dialog" aria-modal="true" aria-label={`Mototaxi ${detail.vehicle.identifier}`}>
      <header className="fleet-dialog-header"><div className="fleet-dialog-title"><span><MototaxiIcon/></span><div><h2>Mototaxi {detail.vehicle.identifier}</h2><p>Gestión completa de la unidad</p></div></div><button className="fleet-close" disabled={busy} onClick={close}><span>Cerrar</span> ×</button></header>
      {error&&<p className="alert error" role="alert">{error}</p>}{notice&&<p className="note" role="status">{notice}</p>}
      <nav className="fleet-tabs" aria-label="Secciones de la mototaxi">{tabs.map(([key,title,icon])=><button key={key} className={tab===key?'active':''} onClick={()=>goto(key)}><span>{icon}</span>{title}</button>)}</nav>
      <main className="fleet-tab-content">
        {tab==='info'&&<div className="fleet-info-grid"><Panel title="Unidad" className="fleet-vehicle-card"><div className="fleet-hero-photo"><Photo id={detail.vehicle.photoId} token={token}/></div><small>Foto normalizada para visualización</small><h3>{[detail.vehicle.brand,detail.vehicle.model].filter(Boolean).join(' ')||detail.vehicle.identifier}</h3><p>{detail.vehicle.color||'Color sin registrar'}{detail.vehicle.unitNumber?` · Unidad ${detail.vehicle.unitNumber}`:''}</p><div className="fleet-badge-row"><StateBadge value={detail.vehicle.status}/><span className="fleet-badge fleet-badge-info">♙ {detail.vehicle.maximumPassengers} pasajeros</span></div></Panel><div className="fleet-info-main"><Panel title="Datos generales" icon="▣"><dl className="fleet-data-grid"><div><dt>Placa</dt><dd>{detail.vehicle.identifier}</dd></div><div><dt>Unidad</dt><dd>{detail.vehicle.unitNumber||'Sin número'}</dd></div><div><dt>Marca / modelo</dt><dd>{[detail.vehicle.brand,detail.vehicle.model].filter(Boolean).join(' ')||'Sin registrar'}</dd></div><div><dt>Color</dt><dd>{detail.vehicle.color||'Sin registrar'}</dd></div><div><dt>Propietario declarado</dt><dd>{detail.vehicle.declaredOwnerName||'No registrado'}</dd></div><div><dt>Conductor actual</dt><dd>{detail.current?.driverName||'Sin asignar'}</dd></div></dl></Panel><Panel title="Estado operativo" icon="◇"><div className="fleet-status-selector">{['VERIFIED','PENDING','SUSPENDED'].map(value=><button key={value} className={detail.vehicle.status===value?'selected':''} disabled={!canManage||busy||detail.vehicle.status===value} onClick={()=>void changeStatus(value)}><StateBadge value={value}/></button>)}</div>{detail.current&&<div className="fleet-current"><strong>Jornada activa con {detail.current.driverName}</strong><span>Inicio {date(detail.current.startedAt)} · Última señal {date(detail.current.lastHeartbeat)}</span></div>}{canManage&&<div className="fleet-actions-inline"><button className="primary" onClick={()=>void edit(detail.vehicle)}>✎ Editar información</button><button className="secondary" onClick={()=>void changeStatus(detail.vehicle.status==='SUSPENDED'?'PENDING':'SUSPENDED')}>⇄ Cambiar estado</button></div>}</Panel></div><aside><Panel title="Acciones rápidas" icon="ϟ" className="fleet-quick-actions">{[['relations','♙','Autorizar conductor'],['files','⇧','Subir documentos'],['qr','⌗','Ver QR'],['history','◇','Revisar auditoría']].map(([key,icon,title])=><button key={key} onClick={()=>goto(key)}><span>{icon}</span>{title}<b>›</b></button>)}</Panel><Panel title="Flujo sugerido" icon="⌁" className="fleet-mini-flow">{[['info','Información'],['relations','Autorizaciones'],['info','Estado'],['files','Documentos'],['qr','QR'],['history','Auditoría']].map(([key,title],index)=><button key={`${key}-${title}`} onClick={()=>goto(key)}><i>{index+1}</i>{title}</button>)}</Panel></aside></div>}
        {tab==='relations'&&<><div className="fleet-section-head"><div><h3>Personas autorizadas</h3><p>Las personas autorizadas pueden conducir o administrar esta unidad según la relación asignada.</p></div>{canManage&&<button className="primary" onClick={()=>void assign()}>+ Autorizar persona</button>}</div>{detail.relations.length?<div className="fleet-table-card"><table><thead><tr><th>Persona autorizada</th><th>Rol / estado</th><th>Origen</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody>{detail.relations.map((relation:any)=><tr key={relation.id}><td><div className="fleet-person"><span>{relation.name?.slice(0,1)||'?'}</span><div><strong>{relation.name}</strong><small>{label(relation.type)}</small></div></div></td><td><StateBadge value={relation.status}/></td><td>{label(relation.source)}</td><td>{date(relation.requestedAt)}</td><td><div className="fleet-row-actions">{canManage&&['APPROVED','REJECTED','REVOKED'].filter(value=>value!==relation.status).map(value=><button key={value} className={value==='APPROVED'?'primary':'secondary'} onClick={async()=>{const data=await reason(`${label(value)}: ${relation.name}`);if(data)await mutate(()=>call(`/vehicles/${detail.vehicle.id}/relations`,'PUT',{userId:relation.userId,type:relation.type,status:value,reason:data.reason}));}}>{label(value)}</button>)}</div></td></tr>)}</tbody></table></div>:<EmptyState icon="♙" title="Aún no hay personas autorizadas" action={canManage?<button className="primary" onClick={()=>void assign()}>Autorizar persona</button>:undefined}>Agrega un conductor o responsable para esta unidad.</EmptyState>}{detail.claims.map((claim:any)=><div className="fleet-claim" key={claim.id}><div><strong>Reclamación de {claim.name}</strong><small>{label(claim.status)} · {date(claim.createdAt)}</small></div><button className="secondary" onClick={()=>void accessFile(claim.evidenceId)}>Ver evidencia</button>{claim.status==='PENDING'&&canManage&&[true,false].map(approved=><button className={approved?'primary':'secondary'} key={String(approved)} onClick={async()=>{const data=await reason(approved?'Validar responsable':'Rechazar reclamación');if(data)await mutate(()=>call(`/ownership-claims/${claim.id}/review`,'POST',{approved,reason:data.reason}));}}>{approved?'Validar':'Rechazar'}</button>)}</div>)}</>}
        {['sessions','trips'].includes(tab)&&<><div className="fleet-section-head"><div><h3>{tab==='sessions'?'Historial de jornadas':'Historial de viajes'}</h3><p>{tab==='sessions'?'Actividad operativa de la unidad por conductor.':'Carreras vinculadas a esta mototaxi.'}</p></div>{period}</div>{detail[tab].length?<div className="fleet-table-card"><table><thead><tr>{(tab==='sessions'?['Conductor','Inicio / cierre','Estado','Actividad','Acciones']:['Fecha','Conductor','Estado','Distancia','Total']).map(title=><th key={title}>{title}</th>)}</tr></thead><tbody>{detail[tab].map((item:any)=><tr key={item.id}>{tab==='sessions'?<><td><strong>{item.driverName}</strong></td><td>{date(item.startedAt)}<small>{item.endedAt?`Cierre: ${date(item.endedAt)}`:'Jornada en curso'}</small></td><td><StateBadge value={item.status}/><small>{label(item.endReason)}</small></td><td><strong>{item.completed} finalizados</strong><small>{item.received} recibidos · {item.accepted} aceptados</small><small>{item.driverCancelled} por conductor · {item.passengerCancelled} por pasajero</small></td><td>{item.status==='ACTIVE'&&canManage&&<button className="secondary" onClick={async()=>{const data=await reason('Liberar jornada de forma administrativa');if(data)await mutate(()=>call(`/sessions/${item.id}/release`,'POST',{reason:'ADMIN_RELEASE',note:data.reason}));}}>Liberar jornada</button>}</td></>:<><td>{date(item.acceptedAt)}<small>{item.endedAt?`Fin: ${date(item.endedAt)}`:''}</small></td><td>{item.driverName}</td><td><StateBadge value={item.outcome}/></td><td>{(Number(item.distanceMeters)/1000).toFixed(2)} km</td><td><strong>{money(item.totalCents)}</strong></td></>}</tr>)}</tbody></table></div>:<EmptyState icon={tab==='sessions'?'▣':'▰'} title={tab==='sessions'?'Sin jornadas registradas':'Sin viajes registrados'}>{tab==='sessions'?'Cuando un conductor use esta unidad, su jornada aparecerá aquí.':'Los viajes realizados con esta mototaxi aparecerán aquí.'}</EmptyState>}</>}
        {tab==='files'&&<><div className="fleet-section-head"><div><h3>Documentos de la unidad</h3><p>Sube archivos legibles y conserva el historial original para auditoría.</p></div></div>{canManage&&<div className="fleet-upload-grid">{[['PHOTO','Fotografía','Imagen frontal o lateral de la mototaxi.'],['REGISTRATION','Matrícula','Documento vigente de la unidad.'],['OPERATING_PERMIT','Anexos','Documentación adicional opcional cuando corresponda.']].map(([kind,title,description])=><article key={kind}><span className="fleet-upload-icon">{kind==='PHOTO'?'▧':'▤'}</span><div><strong>{title}</strong><p>{description}</p>{filesByKind(kind).length>0&&<small>Último archivo: {date(filesByKind(kind)[0].createdAt)}</small>}</div><label className="secondary">⇧ Subir archivo<input type="file" disabled={busy} accept={kind==='PHOTO'?'image/jpeg,image/png':'image/jpeg,image/png,application/pdf'} onChange={event=>{const source=event.target.files?.[0];if(source)void upload(source,kind);event.target.value='';}}/></label></article>)}</div>}<p className="fleet-file-help">Formatos aceptados: JPG, PNG y PDF según el documento · Tamaño máximo: 5 MB.</p>{detail.files.length?<div className="fleet-table-card"><table><thead><tr><th>Documento</th><th>Fecha / hora</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{detail.files.map((item:any)=><tr key={item.id}><td><strong>{label(item.kind)}</strong><small>{item.mimeType}</small></td><td>{date(item.createdAt)}</td><td><span className="fleet-badge fleet-badge-success"><i/>Vigente</span></td><td><div className="fleet-row-actions"><button className="secondary" onClick={()=>void accessFile(item.id)}>Ver</button><button className="secondary" onClick={()=>void accessFile(item.id,true)}>Descargar original</button></div></td></tr>)}</tbody></table></div>:<EmptyState icon="▤" title="Sin documentos cargados">Los archivos de la unidad aparecerán aquí con su historial.</EmptyState>}</>}
        {tab==='qr'&&<div className="fleet-qr-layout"><div><h3>Identificación QR de la unidad</h3><p>El QR identifica la mototaxi; no concede permiso para conducirla. Solo las personas autorizadas pueden utilizarla.</p><div className="fleet-qr-actions"><button className="primary" onClick={()=>void qrAction()}>Consultar / generar QR</button><button className="secondary" onClick={()=>void qrAction(true)}>Regenerar QR</button><button className="secondary" onClick={async()=>{const data=await reason('Invalidar QR');if(data&&await mutate(()=>call(`/vehicles/${detail.vehicle.id}/qr`,'DELETE',data)))setQr(null);}}>Invalidar QR</button></div></div>{qr?<div><div className="fleet-qr" id="fleet-print-qr"><img src="/costa-go-emblem.png" alt="Costa-Go"/><h3>Unidad verificada</h3><div dangerouslySetInnerHTML={{__html:qr.svg}}/><h2>{detail.vehicle.identifier}</h2><p>{detail.vehicle.color}</p><small>Tu seguridad es nuestra prioridad</small></div><div className="fleet-qr-actions"><button className="primary" onClick={downloadQr}>Descargar QR</button><button className="secondary" onClick={()=>window.print()}>Ver ampliado / imprimir</button></div></div>:<EmptyState icon="⌗" title="QR todavía no consultado" action={<button className="primary" onClick={()=>void qrAction()}>Generar o consultar QR</button>}>Genera la identificación segura de esta unidad.</EmptyState>}</div>}
        {tab==='history'&&<><div className="fleet-section-head"><div><h3>Auditoría administrativa</h3><p>Cambios, responsables y motivos vinculados a la unidad.</p></div></div>{detail.history.length?<div className="fleet-timeline">{detail.history.map((item:any)=><article key={item.id}><i/><div><strong>{label(item.action)}</strong><span>{date(item.occurredAt)} · {item.actor??'Sistema'}</span>{item.reason&&<p>{item.reason}</p>}</div></article>)}</div>:<EmptyState icon="◷" title="Sin eventos de auditoría">Los cambios administrativos de esta unidad aparecerán aquí.</EmptyState>}</>}
        {['sessions','trips','files','history'].includes(tab)&&detail[tab]?.length>0&&<div className="fleet-pagination"><button className="secondary" disabled={busy||detailPage===0} onClick={()=>void open(detail.vehicle.id,detailPage-1)}>Anterior</button><span>Página {detailPage+1}</span><button className="secondary" disabled={busy||detail[tab]?.length<30} onClick={()=>void open(detail.vehicle.id,detailPage+1)}>Siguiente</button></div>}
      </main>
      <footer className="fleet-flow-footer"><strong>Flujo de gestión</strong>{[['info','Información'],['relations','Autorizaciones'],['info','Estado'],['files','Documentos'],['qr','QR'],['history','Auditoría']].map(([key,title],index)=><span key={`${key}-${title}`}><button className={tab===key?'active':''} onClick={()=>goto(key)}>{title}</button>{index<5&&<b>→</b>}</span>)}</footer>
    </section></div>}{dialog.modal}
  </section>;
}
