import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { apiFetch, login, type Session } from "./api.js";
import "./styles.css";

type Module = "dashboard" | "trips" | "drivers" | "passengers" | "pricing" | "zones" | "incidents" | "audit" | "database";
const labels: Record<Module, string> = { dashboard:"Tablero", trips:"Viajes", drivers:"Conductores", passengers:"Pasajeros", pricing:"Tarifas", zones:"Zonas", incidents:"Incidentes", audit:"Auditoría", database:"PostgreSQL" };
function Badge({value}:{value:string}) { return <span className={`badge ${value.toLowerCase()}`}>{value.replaceAll("_", " ")}</span>; }
function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}) { return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>; }
function Header({title,detail}:{title:string;detail?:string}) { return <div className="section-title"><div><span className="eyebrow">MOTOTAXI ATACAMES</span><h2>{title}</h2></div>{detail&&<span className="muted-pill">{detail}</span>}</div>; }
function money(c:number) { return `$${(c / 100).toFixed(2)}`; }

function Login({onSession}:{onSession:(s:Session)=>void}) { const [email,setEmail]=useState("admin@mototaxi.local"),[password,setPassword]=useState("Mototaxi2026!"),[error,setError]=useState(""); async function submit(e:React.FormEvent){e.preventDefault();try{onSession(await login(email,password));}catch(e){setError(e instanceof Error?e.message:"No se pudo ingresar");}} return <div className="login-shell"><form className="login-card" onSubmit={submit}><div className="brand-mark">M</div><h1>Centro de control</h1><label>Correo<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="alert error">{error}</div>}<button className="primary">Ingresar</button></form></div>; }
function Trips({token,admin}:{token:string;admin:boolean}) { const [data,setData]=useState<any[]>([]); const load=()=>apiFetch<any[]>("/v1/admin/trips",token).then(setData); useEffect(()=>{void load();const id=setInterval(load,5000);return()=>clearInterval(id);},[token]); async function cancel(id:string){if(!confirm("¿Cancelar este viaje?"))return;await apiFetch(`/v1/admin/trips/${id}/action`,token,{method:"POST",body:JSON.stringify({action:"CANCEL",reason:"Cancelado desde el panel administrativo"})});load();} return <section className="card"><Header title="Viajes y asignaciones" detail={`${data.filter(t=>!["COMPLETED","CANCELLED","NO_DRIVER"].includes(t.status)).length} activos`}/><Table headers={["Hora","Pasajero","Conductor","Ruta","Estado","Total","Acción"]} rows={data.map(t=>[new Date(t.requestedAt).toLocaleString(),t.passenger,t.driver,`${t.originReference??"Origen"} → ${t.destinationReference??"Destino"}`,<Badge value={t.status}/>,money(t.quotedTotalCents),admin&&!["COMPLETED","CANCELLED","NO_DRIVER"].includes(t.status)?<button className="link" onClick={()=>cancel(t.id)}>Cancelar</button>:"—"])} /></section>; }
function SimpleList({token,path,title}:{token:string;path:string;title:string}) { const [data,setData]=useState<any[]>([]);useEffect(()=>{apiFetch<any[]>(path,token).then(setData)},[path,token]);return <section className="card"><Header title={title}/><pre>{JSON.stringify(data,null,2)}</pre></section>; }
function Dashboard({token}:{token:string}) { const [data,setData]=useState<any>();useEffect(()=>{apiFetch<any>("/v1/admin/dashboard",token).then(setData)},[token]);return <section className="card"><Header title="Operación piloto"/>{data?<div className="metric-grid">{Object.entries(data.metrics).map(([k,v])=><article className="metric" key={k}><span>{k}</span><strong>{String(v)}</strong></article>)}</div>:"Cargando…"}</section>; }
function App(){const[session,setSession]=useState<Session|undefined>(()=>{try{return JSON.parse(localStorage.getItem("admin-session")??"")}catch{return undefined}});const[module,setModule]=useState<Module>("dashboard");if(!session)return <Login onSession={s=>{localStorage.setItem("admin-session",JSON.stringify(s));setSession(s);}}/>;const admin=session.user.role==="ADMIN";return <div className="app-shell"><aside><div className="brand"><div className="brand-mark">M</div><div><strong>Mototaxi</strong><small>Atacames</small></div></div><nav>{(Object.keys(labels) as Module[]).map(m=><button key={m} className={module===m?"active":""} onClick={()=>setModule(m)}>{labels[m]}</button>)}</nav><div className="profile"><strong>{session.user.name}</strong><button onClick={()=>{localStorage.removeItem("admin-session");setSession(undefined);}}>Cerrar sesión</button></div></aside><main><header className="topbar"><h1>{labels[module]}</h1></header>{module==="dashboard"&&<Dashboard token={session.token}/>} {module==="trips"&&<Trips token={session.token} admin={admin}/>} {module!=="dashboard"&&module!=="trips"&&<SimpleList token={session.token} path={`/v1/admin/${module}`} title={labels[module]}/>}</main></div>;}
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
