import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { apiFetch, login, type Session } from "./api.js";
import "./styles.css";
import "./settings.css";

type Module = "dashboard" | "trips" | "drivers" | "passengers" | "pricing" | "zones" | "settings" | "incidents" | "audit" | "database";
const labels: Record<Module, string> = { dashboard:"Tablero", trips:"Viajes", drivers:"Conductores", passengers:"Pasajeros", pricing:"Tarifas", zones:"Zonas", settings:"Configuración", incidents:"Incidentes", audit:"Auditoría", database:"PostgreSQL" };
const stateLabels: Record<string,string> = { SEARCHING:"Buscando conductor", ASSIGNED:"Asignado", DRIVER_EN_ROUTE:"Conductor en camino", DRIVER_ARRIVED:"Conductor llegó", IN_PROGRESS:"Viaje en curso", COMPLETED:"Finalizado", CANCELLED:"Cancelado", NO_DRIVER:"Sin conductor", INCIDENT:"Incidente", PENDING:"Pendiente", ACTIVE:"Activo", SUSPENDED:"Suspendido", REJECTED:"Rechazado", OPEN:"Abierto", IN_REVIEW:"En revisión", RESOLVED:"Resuelto" };
function Badge({value}:{value:string}) { return <span className={`badge ${value.toLowerCase()}`}>{stateLabels[value] ?? value.replaceAll("_", " ")}</span>; }
function Table({headers,rows}:{headers:string[];rows:React.ReactNode[][]}) { return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>; }
function Header({title,detail}:{title:string;detail?:string}) { return <div className="section-title"><div><span className="eyebrow">MOTOTAXI ATACAMES</span><h2>{title}</h2></div>{detail&&<span className="muted-pill">{detail}</span>}</div>; }
function money(c:number) { return `$${(c / 100).toFixed(2)}`; }

function Drivers({token,admin}:{token:string;admin:boolean}) {
  const [data,setData]=useState<any[]>([]); const [error,setError]=useState("");
  const load=()=>apiFetch<any[]>("/v1/admin/drivers",token).then(setData).catch(e=>setError(e.message));
  useEffect(()=>{void load();},[token]);
  async function update(id:string,status:string,deunaEnabled=false){try{await apiFetch(`/v1/admin/drivers/${id}`,token,{method:"PATCH",body:JSON.stringify({status,deunaEnabled,reason:"Configuración de pagos De Una"})});load();}catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar");}}
  return <section className="card"><Header title="Conductores" detail={`${data.filter(d=>d.status==="PENDING").length} pendientes`}/>{error&&<div className="alert error">{error}</div>}<Table headers={["Nombre","Vehículo","Estado","Acepta pagos","Acción"]} rows={data.map(d=>[d.name,d.vehicle,<Badge value={d.status}/>,admin?<label><input type="checkbox" checked={Boolean(d.deunaEnabled)} onChange={e=>update(d.id,d.status,e.target.checked)}/> De Una</label>:"—",admin?<select value={d.status} onChange={e=>update(d.id,e.target.value,Boolean(d.deunaEnabled))}><option value="PENDING">PENDIENTE</option><option value="ACTIVE">ACTIVO</option><option value="SUSPENDED">SUSPENDER</option><option value="REJECTED">RECHAZAR</option></select>:"Solo lectura"])} /></section>;
}

function Passengers({token,admin}:{token:string;admin:boolean}) {
  const [data,setData]=useState<any[]>([]); const [error,setError]=useState("");
  const load=()=>apiFetch<any[]>("/v1/admin/passengers",token).then(setData).catch(e=>setError(e.message));
  useEffect(()=>{void load();},[token]);
  async function update(id:string,status:string){try{await apiFetch(`/v1/admin/passengers/${id}`,token,{method:"PATCH",body:JSON.stringify({status,reason:"Actualización desde el panel administrativo"})});load();}catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar");}}
  return <section className="card"><Header title="Pasajeros" detail={`${data.length} registrados`}/>{error&&<div className="alert error">{error}</div>}<Table headers={["Nombre","Teléfono","Viajes","Último viaje","Estado","Acción"]} rows={data.map(p=>[p.name,p.phone,p.trips,p.lastTrip?new Date(p.lastTrip).toLocaleString():"Sin viajes",<Badge value={p.status}/>,admin?<button className="link" onClick={()=>update(p.id,p.status==="ACTIVE"?"SUSPENDED":"ACTIVE")}>{p.status==="ACTIVE"?"Suspender":"Reactivar"}</button>:"Solo lectura"])} /></section>;
}

function Login({onSession}:{onSession:(s:Session)=>void}) { const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""); async function submit(e:React.FormEvent){e.preventDefault();try{onSession(await login(email,password));}catch(e){setError(e instanceof Error?e.message:"No se pudo ingresar");}} return <div className="login-shell"><form className="login-card" onSubmit={submit}><div className="brand-mark">M</div><h1>Centro de control</h1><label>Correo<input autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="alert error">{error}</div>}<button className="primary">Ingresar</button></form></div>; }
function Trips({token,admin}:{token:string;admin:boolean}) { const [data,setData]=useState<any[]>([]); const load=()=>apiFetch<any[]>("/v1/admin/trips",token).then(setData); useEffect(()=>{void load();const id=setInterval(load,5000);return()=>clearInterval(id);},[token]); async function cancel(id:string){const reason=prompt("Motivo que recibirán pasajero y conductor:","Cancelado desde el panel administrativo");if(!reason?.trim())return;await apiFetch(`/v1/admin/trips/${id}/action`,token,{method:"POST",body:JSON.stringify({action:"CANCEL",reason:reason.trim()})});load();} return <section className="card"><Header title="Viajes y asignaciones" detail={`${data.filter(t=>!["COMPLETED","CANCELLED","NO_DRIVER"].includes(t.status)).length} activos`}/><Table headers={["Hora","Pasajero","Conductor","Ruta","Estado","Total","Acción"]} rows={data.map(t=>[new Date(t.requestedAt).toLocaleString(),t.passenger,t.driver,`${t.originReference??"Origen"} → ${t.destinationReference??"Destino"}`,<Badge value={t.status}/>,money(t.quotedTotalCents),admin&&!["COMPLETED","CANCELLED","NO_DRIVER"].includes(t.status)?<button className="link" onClick={()=>cancel(t.id)}>Cancelar</button>:"—"])} /></section>; }
function Settings({token,admin}:{token:string;admin:boolean}) { const [radius,setRadius]=useState(3000),[saved,setSaved]=useState(""),[error,setError]=useState(""); useEffect(()=>{apiFetch<{searchRadiusMeters:number}>("/v1/admin/settings",token).then(v=>setRadius(v.searchRadiusMeters)).catch(e=>setError(e.message));},[token]); async function save(e:React.FormEvent){e.preventDefault();setSaved("");setError("");try{const value=await apiFetch<{searchRadiusMeters:number}>("/v1/admin/settings",token,{method:"PATCH",body:JSON.stringify({searchRadiusMeters:radius})});setRadius(value.searchRadiusMeters);setSaved("Configuración guardada. Las nuevas solicitudes usarán este radio.");}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar");}} return <section className="card settings-card"><Header title="Configuración operativa" detail={`${(radius/1000).toFixed(1)} km`}/><form onSubmit={save}><label>Radio máximo para buscar conductores cercanos<div className="radius-control"><input type="range" min="500" max="20000" step="500" value={radius} disabled={!admin} onChange={e=>setRadius(Number(e.target.value))}/><input type="number" min="500" max="20000" step="500" value={radius} disabled={!admin} onChange={e=>setRadius(Number(e.target.value))}/><span>metros</span></div></label><p className="note">Se aplica desde el punto GPS real del conductor hasta el origen solicitado por el pasajero. Rango permitido: 500 m a 20 km.</p>{saved&&<div className="alert success">{saved}</div>}{error&&<div className="alert error">{error}</div>}{admin&&<button className="primary" type="submit">Guardar radio de búsqueda</button>}</form></section>; }
function SimpleList({token,path,title}:{token:string;path:string;title:string}) { const [data,setData]=useState<any[]>([]);useEffect(()=>{apiFetch<any[]>(path,token).then(setData)},[path,token]);return <section className="card"><Header title={title}/><pre>{JSON.stringify(data,null,2)}</pre></section>; }
function Dashboard({token}:{token:string}) { const [data,setData]=useState<any>();useEffect(()=>{apiFetch<any>("/v1/admin/dashboard",token).then(setData)},[token]);return <section className="card"><Header title="Operación piloto"/>{data?<div className="metric-grid">{Object.entries(data.metrics).map(([k,v])=><article className="metric" key={k}><span>{k}</span><strong>{String(v)}</strong></article>)}</div>:"Cargando…"}</section>; }
function App(){const[session,setSession]=useState<Session|undefined>(()=>{try{return JSON.parse(localStorage.getItem("admin-session")??"")}catch{return undefined}});const[module,setModule]=useState<Module>("dashboard");if(!session)return <Login onSession={s=>{localStorage.setItem("admin-session",JSON.stringify(s));setSession(s);}}/>;const admin=session.user.role==="ADMIN";return <div className="app-shell"><aside><div className="brand"><div className="brand-mark">M</div><div><strong>Mototaxi</strong><small>Atacames</small></div></div><nav>{(Object.keys(labels) as Module[]).map(m=><button key={m} className={module===m?"active":""} onClick={()=>setModule(m)}>{labels[m]}</button>)}</nav><div className="profile"><strong>{session.user.name}</strong><button onClick={()=>{localStorage.removeItem("admin-session");setSession(undefined);}}>Cerrar sesión</button></div></aside><main><header className="topbar"><h1>{labels[module]}</h1></header>{module==="dashboard"&&<Dashboard token={session.token}/>} {module==="trips"&&<Trips token={session.token} admin={admin}/>} {module==="drivers"&&<Drivers token={session.token} admin={admin}/>} {module==="passengers"&&<Passengers token={session.token} admin={admin}/>} {module==="settings"&&<Settings token={session.token} admin={admin}/>} {!["dashboard","trips","drivers","passengers","settings"].includes(module)&&<SimpleList token={session.token} path={`/v1/admin/${module}`} title={labels[module]}/>}</main></div>;}
createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
