import { useEffect, useMemo, useState } from "react";
import { apiFetch, apiUrl } from "./api.js";
import "./memberships.css";

type Props = { token: string; permissions: string[] };
const money = (value: unknown, currency = "USD") => new Intl.NumberFormat("es-EC", { style: "currency", currency }).format(Number(value ?? 0));
const date = (value: unknown) => value ? new Date(String(value)).toLocaleString("es-EC") : "Sin fecha";
const membershipLabels: Record<string,string> = {
  PENDING:"Pendiente de activación",ACTIVE:"Activa",EXPIRING:"Próxima a vencer",GRACE_PERIOD:"En gracia",
  PAYMENT_DUE:"Pago pendiente",SUSPENSION_PENDING_ACTIVE_TRIP:"Suspensión al finalizar viaje",
  SUSPENDED_NON_PAYMENT:"Vencida",SUSPENDED:"Suspendida",CLOSED:"Ciclo cerrado"
};

function Card({label,value,tone=""}:{label:string;value:unknown;tone?:string}) {
  return <article className={`membership-stat ${tone}`}><span>{label}</span><strong>{String(value ?? 0)}</strong></article>;
}

function CollectorPortal({token}:Pick<Props,"token">) {
  const [profile,setProfile]=useState<any>({points:[]});
  const [payments,setPayments]=useState<any[]>([]);
  const [closures,setClosures]=useState<any[]>([]);
  const [lookup,setLookup]=useState(()=>new URLSearchParams(window.location.search).get("paymentToken")??"");
  const [order,setOrder]=useState<any>();
  const [pointId,setPointId]=useState("");
  const [method,setMethod]=useState("CASH");
  const [message,setMessage]=useState("");
  const [error,setError]=useState("");
  const [busy,setBusy]=useState(false);
  const rawToken=()=>{const parts=lookup.trim().split("/").filter(Boolean);return parts[parts.length-1]??"";};
  async function load(){try{const [me,today,history]=await Promise.all([apiFetch<any>("/v1/collector/me",token),apiFetch<any[]>("/v1/collector/payments/today",token),apiFetch<any[]>("/v1/collector/closures",token)]);setProfile(me);setPayments(today);setClosures(history);if(!pointId&&me.points?.[0])setPointId(me.points[0].id);}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo cargar el portal.");}}
  useEffect(()=>{void load();if(rawToken().length>=10)void findOrder();},[token]);
  async function findOrder(){setBusy(true);setError("");setMessage("");try{setOrder(await apiFetch(`/v1/collector/payment-orders/token/${encodeURIComponent(rawToken())}`,token));}catch(reason){setError(reason instanceof Error?reason.message:"Orden no encontrada.");}finally{setBusy(false);}}
  async function confirm(){if(!order||!pointId)return;setBusy(true);setError("");try{await apiFetch(`/v1/collector/payment-orders/token/${encodeURIComponent(rawToken())}/confirm`,token,{method:"POST",body:JSON.stringify({method,collectionPointId:pointId,idempotencyKey:`collector-${order.id}-${method}`})});setMessage("Pago confirmado. La membresía ya está activa.");setOrder(undefined);setLookup("");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo confirmar el pago.");}finally{setBusy(false);}}
  async function closeCash(){if(!pointId)return;setBusy(true);setError("");try{const result=await apiFetch<any>("/v1/collector/closures",token,{method:"POST",body:JSON.stringify({collectionPointId:pointId,notes:"Cierre generado desde el portal de recaudación"})});setMessage(`Cierre creado por ${money(result.grossAmount)} con ${result.payments} pago(s).`);await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo crear el cierre.");}finally{setBusy(false);}}
  return <div className="membership-admin collector-portal">
    <section className="card membership-hero"><div><span className="eyebrow">PORTAL DE RECAUDACIÓN</span><h2>Confirmar membresías</h2><p>Valida el QR o código del conductor. No modifica perfiles, documentos ni viajes.</p></div><button className="secondary" onClick={()=>void load()}>Actualizar</button></section>
    {error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}
    <section className="card"><h2>Buscar orden</h2><div className="membership-toolbar"><label>QR, enlace o token<input value={lookup} onChange={event=>setLookup(event.target.value)} placeholder="Pega el enlace leído del QR"/></label><label>Punto<select value={pointId} onChange={event=>setPointId(event.target.value)}>{profile.points?.map((point:any)=><option key={point.id} value={point.id}>{point.name}</option>)}</select></label><button className="primary" disabled={busy||rawToken().length<10} onClick={()=>void findOrder()}>Consultar</button></div>{order&&<div className="collector-order"><h3>{order.driver}</h3><p>{order.plan?.name} · <strong>{money(order.amount,order.currency)}</strong></p><p>Código {order.shortCode} · vence {date(order.expiresAt)}</p><label>Método<select value={method} onChange={event=>setMethod(event.target.value)}><option value="CASH">Efectivo</option><option value="DEUNA">De Una</option><option value="BANK_TRANSFER">Transferencia verificada en punto</option></select></label><button className="primary" disabled={busy} onClick={()=>void confirm()}>Confirmar pago</button></div>}</section>
    <section className="card"><div className="membership-toolbar"><div><h2>Recaudación de hoy</h2><p>{payments.length} pago(s) · {money(payments.reduce((sum,item)=>sum+Number(item.amount),0))}</p></div><button className="secondary" disabled={busy||!pointId} onClick={()=>void closeCash()}>Cerrar caja</button></div><div className="table-wrap"><table><thead><tr><th>Hora</th><th>Conductor</th><th>Método</th><th>Monto</th><th>Estado</th></tr></thead><tbody>{payments.map(item=><tr key={item.id}><td>{date(item.confirmedAt)}</td><td>{item.driver}</td><td>{item.method}</td><td>{money(item.amount,item.currency)}</td><td>{item.settlementStatus}</td></tr>)}</tbody></table></div></section>
    <section className="card"><h2>Últimos cierres</h2><div className="table-wrap"><table><thead><tr><th>Período</th><th>Punto</th><th>Total</th><th>Estado</th></tr></thead><tbody>{closures.map(item=><tr key={item.id}><td>{date(item.periodEnd)}</td><td>{item.point}</td><td>{money(item.netAmount)}</td><td>{item.status}</td></tr>)}</tbody></table></div></section>
  </div>;
}

export function MembershipAdmin(props:Props) {
  const collectorOnly=props.permissions.includes("payments:collect")&&!props.permissions.includes("memberships:manage")&&!props.permissions.includes("payments:transfer_review");
  return collectorOnly?<CollectorPortal token={props.token}/>:<MembershipManagement {...props}/>;
}

function MembershipManagement({token,permissions}:Props) {
  const can=(permission:string)=>permissions.includes(permission);
  const [summary,setSummary]=useState<any>();
  const [memberships,setMemberships]=useState<any>({items:[]});
  const [plans,setPlans]=useState<any[]>([]);
  const [settings,setSettings]=useState<any>();
  const [pendingPayments,setPendingPayments]=useState<any[]>([]);
  const [usage,setUsage]=useState<any>();
  const [collectionData,setCollectionData]=useState<any>({points:[],collectors:[]});
  const [closures,setClosures]=useState<any[]>([]);
  const [gracePolicies,setGracePolicies]=useState<any[]>([]);
  const [filters,setFilters]=useState({status:"",search:""});
  const [tab,setTab]=useState<"memberships"|"plans"|"payments"|"settings"|"import"|"collection"|"grace">("memberships");
  const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [busy,setBusy]=useState(false);
  const [importPreview,setImportPreview]=useState<any>();

  async function load() {
    setError("");
    try {
      const query=new URLSearchParams({page:"1",limit:"100"});if(filters.status)query.set("status",filters.status);if(filters.search)query.set("search",filters.search);
      const calls:Promise<any>[]=[apiFetch("/v1/admin/memberships/dashboard",token),apiFetch(`/v1/admin/memberships?${query}`,token),apiFetch("/v1/admin/membership-plans",token)];
      const [nextSummary,nextMemberships,nextPlans]=await Promise.all(calls);
      setSummary(nextSummary);setMemberships(nextMemberships);setPlans(nextPlans);
      if(can("settings:view"))setSettings(await apiFetch("/v1/admin/platform-settings",token));
      if(can("payments:transfer_review"))setPendingPayments(await apiFetch("/v1/admin/membership-payments/pending",token));
      if(can("api_usage:view"))setUsage(await apiFetch("/v1/admin/api-usage",token));
      if(can("collection_points:manage"))setCollectionData(await apiFetch("/v1/admin/collection-points",token));
      if(can("cash_closures:review"))setClosures(await apiFetch("/v1/admin/collection-closures",token));
      if(can("memberships:view"))setGracePolicies(await apiFetch("/v1/admin/membership-grace-policies",token));
    } catch(reason){setError(reason instanceof Error?reason.message:"No se pudo cargar membresías.");}
  }
  useEffect(()=>{void load();},[token,filters.status]);

  async function action(driverId:string,action:string) {
    const reason=window.prompt(action==="SUSPEND"?"Motivo de suspensión":"Motivo de la acción","Gestión autorizada desde el panel Costa-Go");
    if(!reason||reason.trim().length<5)return;
    setBusy(true);setError("");
    try{await apiFetch(`/v1/admin/memberships/${driverId}/action`,token,{method:"POST",body:JSON.stringify({action,reason})});setSuccess("Membresía actualizada y auditada.");await load();}
    catch(reason){setError(reason instanceof Error?reason.message:"No se pudo actualizar.");}finally{setBusy(false);}
  }

  async function grantGrace(driverId:string){const days=Number(window.prompt("Días de gracia",String(settings?.membershipGraceDays??2)));if(!Number.isInteger(days)||days<1||days>90)return;const reason=window.prompt("Motivo obligatorio");if(!reason||reason.trim().length<5)return;setBusy(true);try{await apiFetch(`/v1/admin/memberships/${driverId}/action`,token,{method:"POST",body:JSON.stringify({action:"GRANT_GRACE",days,allowsTrips:true,reason})});setSuccess(`Se concedieron ${days} día(s) de gracia con auditoría.`);await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo aplicar la gracia.");}finally{setBusy(false);}}
  async function adjustMembership(driverId:string){const amount=Number(window.prompt("Ajuste en USD. Usa negativo para descuento o positivo para recargo","-1.00"));if(!Number.isFinite(amount)||amount===0)return;const reason=window.prompt("Motivo obligatorio");if(!reason||reason.trim().length<5)return;setBusy(true);try{await apiFetch(`/v1/admin/memberships/${driverId}/action`,token,{method:"POST",body:JSON.stringify({action:"ADJUST",amount,adjustmentType:amount<0?"DISCOUNT":"POSITIVE",reason})});setSuccess("Ajuste aplicado al ciclo sin modificar su historial.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo ajustar.");}finally{setBusy(false);}}

  async function createPlan(){const name=window.prompt("Nombre del plan","Mensual");if(!name)return;const code=window.prompt("Código único",name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]+/g,"_"));if(!code)return;const durationDays=Number(window.prompt("Duración en días","30"));const baseAmount=Number(window.prompt("Precio base USD","10"));const includedTrips=Number(window.prompt("Viajes incluidos","100"));const maximum=Number(window.prompt("Tope máximo de renovación USD",String(baseAmount)));if(!Number.isInteger(durationDays)||durationDays<1||!Number.isFinite(baseAmount)||baseAmount<0||!Number.isInteger(includedTrips)||includedTrips<0||!Number.isFinite(maximum)||maximum<baseAmount)return;const periodUnit=durationDays<=24?"DAY":"MONTH";const periodCount=durationDays<=24?durationDays:Math.max(1,Math.min(24,Math.round(durationDays/30)));setBusy(true);try{await apiFetch("/v1/admin/membership-plans",token,{method:"POST",body:JSON.stringify({code,name,periodUnit,periodCount,durationDays,baseAmount,currency:"USD",includedTrips,maxRenewalAmount:maximum,extraTripSharePercent:Number(settings?.membershipExtraTripSharePercent??40),enabled:true})});setSuccess("Plan creado. Los ciclos existentes conservan su snapshot.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo crear el plan.");}finally{setBusy(false);}}

  async function createGraceCampaign(){const name=window.prompt("Nombre de la campaña");if(!name)return;const days=Number(window.prompt("Días de gracia","2"));const reason=window.prompt("Motivo y alcance de la campaña");if(!reason||reason.trim().length<5||!Number.isInteger(days)||days<0||days>90)return;const now=new Date();const end=new Date(now.getTime()+30*24*60*60*1000);setBusy(true);try{const payload={name,reason,scope:"ALL",cooperativeId:null,driverId:null,graceDays:days,allowsTrips:true,campaignKind:"RENEWAL",startsAt:now.toISOString(),endsAt:end.toISOString(),expiryWindowStart:null,expiryWindowEnd:null,priority:0,status:"DRAFT"};const preview=await apiFetch<any>("/v1/admin/membership-grace-policies/preview",token,{method:"POST",body:JSON.stringify(payload)});if(!window.confirm(`La campaña en borrador alcanzaría aproximadamente ${preview.affected??0} membresía(s). ¿Crear?`))return;await apiFetch("/v1/admin/membership-grace-policies",token,{method:"POST",body:JSON.stringify(payload)});setSuccess("Campaña creada en borrador; no se aplicará hasta activarla de forma controlada.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo crear la campaña.");}finally{setBusy(false);}}

  async function saveSettings() {
    setBusy(true);setError("");
    try{await apiFetch("/v1/admin/platform-settings",token,{method:"PATCH",body:JSON.stringify(settings)});setSuccess("Parámetros guardados. Los cambios se aplican desde backend.");await load();}
    catch(reason){setError(reason instanceof Error?reason.message:"No se pudo guardar.");}finally{setBusy(false);}
  }

  async function reviewPayment(proof:any,approve:boolean) {
    setBusy(true);setError("");
    try{
      if(approve)await apiFetch(`/v1/admin/membership-payments/${proof.id}/approve`,token,{method:"POST",body:JSON.stringify({idempotencyKey:`admin-proof-${proof.id}`})});
      else {const comment=window.prompt("Motivo del rechazo","El comprobante no coincide con la transferencia.");if(!comment)return;await apiFetch(`/v1/admin/membership-payments/${proof.id}/reject`,token,{method:"POST",body:JSON.stringify({reason:"INVALID_RECEIPT",comment})});}
      setSuccess(approve?"Pago aprobado y membresía activada.":"Comprobante rechazado.");await load();
    }catch(reason){setError(reason instanceof Error?reason.message:"No se pudo revisar el pago.");}finally{setBusy(false);}
  }

  async function openPaymentProof(proofId:string){try{const response=await fetch(apiUrl(`/v1/admin/membership-payments/${proofId}/proof`),{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error("No se pudo abrir el comprobante.");const url=URL.createObjectURL(await response.blob());window.open(url,"_blank","noopener,noreferrer");window.setTimeout(()=>URL.revokeObjectURL(url),60_000);}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo abrir el comprobante.");}}

  async function validateCsv(file:File) {
    setBusy(true);setError("");setImportPreview(undefined);
    try{const contentBase64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result).split(",")[1]??"");reader.readAsDataURL(file);});
      const preview=await apiFetch<any>("/v1/admin/drivers/import/validate",token,{method:"POST",body:JSON.stringify({filename:file.name,contentBase64})});setImportPreview(preview);
    }catch(reason){setError(reason instanceof Error?reason.message:"CSV inválido.");}finally{setBusy(false);}
  }
  async function confirmImport(){if(!importPreview)return;setBusy(true);try{const result=await apiFetch<any>(`/v1/admin/drivers/import/${importPreview.batchId}/confirm`,token,{method:"POST",body:"{}"});setSuccess(`${result.importedRows} conductores creados en pendiente de documentos.`);setImportPreview(undefined);await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo importar.");}finally{setBusy(false);}}
  function downloadTemplate(){const header="nombres,apellidos,identificacion,correo,telefono,cooperativa,placa,marca,modelo,anio,informacion_adicional\n";const anchor=document.createElement("a");anchor.href=URL.createObjectURL(new Blob([header],{type:"text/csv;charset=utf-8"}));anchor.download="plantilla-conductores-costa-go.csv";anchor.click();URL.revokeObjectURL(anchor.href);}

  async function createCollectionPoint(){
    const name=window.prompt("Nombre del punto de recaudación");if(!name)return;
    const proposed=name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]+/g,"_").replace(/^_|_$/g,"");
    const code=window.prompt("Código único",proposed);if(!code)return;
    setBusy(true);setError("");try{await apiFetch("/v1/admin/collection-points",token,{method:"POST",body:JSON.stringify({code,name,status:"INACTIVE",cashEnabled:false,deunaEnabled:false,bankTransferEnabled:false,settlementDeadlineHours:48,pendingLimit:null})});setSuccess("Punto creado inactivo. Configura sus métodos antes de activarlo.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo crear el punto.");}finally{setBusy(false);}
  }
  async function editCollectionPoint(point:any){
    const name=window.prompt("Nombre",point.name);if(!name)return;
    const status=window.prompt("Estado: ACTIVE, SUSPENDED o INACTIVE",point.status)?.toUpperCase();if(!status||!["ACTIVE","SUSPENDED","INACTIVE"].includes(status))return;
    const methods=window.prompt("Métodos separados por coma: CASH, DEUNA, BANK_TRANSFER",[point.cashEnabled&&"CASH",point.deunaEnabled&&"DEUNA",point.bankTransferEnabled&&"BANK_TRANSFER"].filter(Boolean).join(","))?.toUpperCase()??"";
    setBusy(true);try{await apiFetch(`/v1/admin/collection-points/${point.id}`,token,{method:"PATCH",body:JSON.stringify({name,address:point.address??null,serviceAreaId:point.serviceAreaId??null,status,cashEnabled:methods.includes("CASH"),deunaEnabled:methods.includes("DEUNA"),bankTransferEnabled:methods.includes("BANK_TRANSFER"),settlementDeadlineHours:Number(point.settlementDeadlineHours??48),pendingLimit:point.pendingLimit??null})});setSuccess("Punto actualizado y auditado.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo actualizar.");}finally{setBusy(false);}
  }
  async function assignCollector(point:any){
    const available=collectionData.collectors as any[];if(!available.length){setError("Primero crea un usuario con rol RECAUDADOR.");return;}
    const options=available.map((item,index)=>`${index+1}. ${item.name} (${item.email})`).join("\n");const chosen=Number(window.prompt(`Selecciona recaudador:\n${options}`));const collector=available[chosen-1];if(!collector)return;
    setBusy(true);try{await apiFetch(`/v1/admin/collection-points/${point.id}/collectors`,token,{method:"POST",body:JSON.stringify({collectorId:collector.id})});setSuccess("Recaudador asignado.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo asignar.");}finally{setBusy(false);}
  }
  async function settleClosure(closure:any){
    const reference=window.prompt("Referencia del depósito o liquidación");if(!reference)return;
    setBusy(true);try{await apiFetch(`/v1/admin/collection-closures/${closure.id}/settle`,token,{method:"POST",body:JSON.stringify({method:"BANK_TRANSFER",reference,idempotencyKey:`settlement-${closure.id}`})});setSuccess("Liquidación verificada y cierre conciliado.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo conciliar.");}finally{setBusy(false);}
  }

  const setting=(key:string,label:string,type:"number"|"text"|"checkbox"="number")=><label>{label}{type==="checkbox"?<input type="checkbox" checked={Boolean(settings?.[key])} onChange={event=>setSettings({...settings,[key]:event.target.checked})}/>:<input type={type} value={settings?.[key]??""} onChange={event=>setSettings({...settings,[key]:type==="number"?Number(event.target.value):event.target.value})}/>}</label>;
  const statusOptions=useMemo(()=>Object.entries(membershipLabels),[]);
  return <div className="membership-admin">
    <section className="card membership-hero"><div><span className="eyebrow">GESTIÓN DE CONDUCTORES</span><h2>Membresías y recaudación</h2><p>Vigencia, gracia, cobros confirmados y control de acceso a solicitudes desde una sola fuente.</p></div><button className="secondary" onClick={()=>void load()}>Actualizar</button></section>
    {error&&<div className="alert error">{error}</div>}{success&&<div className="alert success">{success}</div>}
    <div className="membership-stats"><Card label="Activas" value={summary?.active}/><Card label="Vencen en 7 días" value={summary?.expiring7Days} tone="warning"/><Card label="En gracia" value={summary?.grace}/><Card label="Vencidas" value={summary?.expired} tone="danger"/><Card label="Suspendidas" value={summary?.suspended} tone="danger"/><Card label="Cooperativas" value={summary?.cooperatives}/><Card label="Individuales" value={summary?.individual}/><Card label="Ingresos confirmados del mes" value={money(summary?.confirmedIncomeMonth)} tone="positive"/></div>
    <div className="membership-tabs" role="tablist"><button className={tab==="memberships"?"active":""} onClick={()=>setTab("memberships")}>Membresías</button><button className={tab==="plans"?"active":""} onClick={()=>setTab("plans")}>Planes</button>{can("membership_grace:manage")&&<button className={tab==="grace"?"active":""} onClick={()=>setTab("grace")}>Campañas de gracia</button>}{can("payments:transfer_review")&&<button className={tab==="payments"?"active":""} onClick={()=>setTab("payments")}>Pagos pendientes</button>}{can("collection_points:manage")&&<button className={tab==="collection"?"active":""} onClick={()=>setTab("collection")}>Puntos y cierres</button>}{can("settings:view")&&<button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}>Parámetros</button>}{can("membership_import:manage")&&<button className={tab==="import"?"active":""} onClick={()=>setTab("import")}>Importar CSV</button>}</div>
    {tab==="memberships"&&<section className="card"><div className="membership-toolbar"><label>Estado<select value={filters.status} onChange={event=>setFilters({...filters,status:event.target.value})}><option value="">Todos</option>{statusOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Buscar<input value={filters.search} onChange={event=>setFilters({...filters,search:event.target.value})} placeholder="Nombre, correo o teléfono"/></label><button className="primary" onClick={()=>void load()}>Aplicar</button></div><div className="table-wrap"><table><thead><tr><th>Conductor</th><th>Plan</th><th>Estado</th><th>Vigencia</th><th>Uso</th><th>Próxima renovación</th><th>Cobertura</th><th>Acciones</th></tr></thead><tbody>{memberships.items?.map((item:any)=><tr key={item.id}><td><strong>{item.driver}</strong><small>{item.email}<br/>{item.cooperative??"Individual"}</small></td><td>{item.plan}</td><td><span className={`membership-badge ${String(item.status).toLowerCase()}`}>{membershipLabels[item.status]??item.status}</span></td><td>{date(item.expiresAt)}{item.graceEndsAt&&<small>Gracia: {date(item.graceEndsAt)}</small>}</td><td>{item.completedTrips}/{item.includedTrips}<small>{item.extraTrips} adicionales</small></td><td><strong>{money(item.estimatedRenewal,item.currency)}</strong></td><td>{item.payerType==="COOPERATIVE"?"Cooperativa":"Individual"}</td><td>{can("memberships:manage")?<div className="row-actions"><button className="link" disabled={busy} onClick={()=>void action(item.driverId,"REACTIVATE")}>Reactivar</button><button className="link" disabled={busy} onClick={()=>void grantGrace(item.driverId)}>Dar gracia</button><button className="link" disabled={busy} onClick={()=>void adjustMembership(item.driverId)}>Ajustar</button><button className="link danger" disabled={busy} onClick={()=>void action(item.driverId,"SUSPEND")}>Suspender</button></div>:"Solo lectura"}</td></tr>)}</tbody></table></div>{!memberships.items?.length&&<p className="empty">No hay membresías para este filtro.</p>}</section>}
    {tab==="plans"&&<section className="card"><div className="membership-toolbar"><div><h2>Planes vigentes</h2><p className="note">Los ciclos guardan un snapshot: cambiar un plan no altera ciclos históricos.</p></div>{can("membership_plans:manage")&&<button className="primary" disabled={busy} onClick={()=>void createPlan()}>+ Nuevo plan</button>}</div><div className="plan-grid">{plans.map(plan=><article key={plan.id}><span>{plan.code}</span><h3>{plan.name}</h3><strong>{money(plan.baseAmount,plan.currency)}</strong><p>{plan.durationDays} días · {plan.includedTrips} viajes incluidos</p><small>Tope de renovación: {money(plan.maxRenewalAmount,plan.currency)} · participación adicional {plan.extraTripSharePercent}%</small></article>)}</div></section>}
    {tab==="grace"&&<section className="card"><div className="membership-toolbar"><div><h2>Campañas de gracia</h2><p>Se crean en borrador, muestran el alcance y requieren activación explícita.</p></div><button className="primary" disabled={busy} onClick={()=>void createGraceCampaign()}>+ Nueva campaña</button></div><div className="table-wrap"><table><thead><tr><th>Campaña</th><th>Alcance</th><th>Días</th><th>Vigencia</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{gracePolicies.map(policy=><tr key={policy.id}><td><strong>{policy.name}</strong><small>{policy.reason}</small></td><td>{policy.scope}</td><td>{policy.graceDays}</td><td>{date(policy.startsAt)}<br/>{date(policy.endsAt)}</td><td><span className={`membership-badge ${String(policy.status).toLowerCase()}`}>{policy.status}</span></td><td>{policy.status!=="FINISHED"?<button className="link" disabled={busy} onClick={async()=>{const next=policy.status==="ACTIVE"?"PAUSED":"ACTIVE";if(next==="ACTIVE"&&!window.confirm("¿Activar esta campaña? La política será considerada por el backend según su alcance y vigencia."))return;setBusy(true);try{await apiFetch(`/v1/admin/membership-grace-policies/${policy.id}/status`,token,{method:"PATCH",body:JSON.stringify({status:next})});await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo cambiar el estado.");}finally{setBusy(false);}}}>{policy.status==="ACTIVE"?"Pausar":"Activar"}</button>:"Finalizada"}</td></tr>)}</tbody></table></div>{!gracePolicies.length&&<p className="empty">No existen campañas configuradas.</p>}</section>}
    {tab==="payments"&&<section className="card"><h2>Transferencias por verificar</h2><div className="table-wrap"><table><thead><tr><th>Conductor</th><th>Referencia</th><th>Declarado</th><th>Esperado</th><th>Fecha</th><th>Acción</th></tr></thead><tbody>{pendingPayments.map(item=><tr key={item.id}><td>{item.driver}</td><td>{item.reference}</td><td>{money(item.declaredAmount,item.currency)}</td><td>{money(item.expectedAmount,item.currency)}</td><td>{date(item.createdAt)}</td><td><div className="row-actions"><button className="link" disabled={busy} onClick={()=>void openPaymentProof(item.id)}>Ver comprobante</button><button className="link" disabled={busy} onClick={()=>void reviewPayment(item,true)}>Aprobar</button><button className="link danger" disabled={busy} onClick={()=>void reviewPayment(item,false)}>Rechazar</button></div></td></tr>)}</tbody></table></div>{!pendingPayments.length&&<p className="empty">No existen comprobantes pendientes.</p>}</section>}
    {tab==="collection"&&<><section className="card"><div className="membership-toolbar"><div><h2>Puntos de recaudación</h2><p>Los nuevos puntos nacen inactivos y requieren métodos y recaudadores autorizados.</p></div><button className="primary" disabled={busy} onClick={()=>void createCollectionPoint()}>+ Nuevo punto</button></div><div className="table-wrap"><table><thead><tr><th>Punto</th><th>Estado</th><th>Métodos</th><th>Recaudadores</th><th>Acciones</th></tr></thead><tbody>{collectionData.points?.map((point:any)=><tr key={point.id}><td><strong>{point.name}</strong><small>{point.code}<br/>{point.serviceArea??"Sin zona"}</small></td><td><span className={`membership-badge ${String(point.status).toLowerCase()}`}>{point.status}</span></td><td>{[point.cashEnabled&&"Efectivo",point.deunaEnabled&&"De Una",point.bankTransferEnabled&&"Transferencia"].filter(Boolean).join(", ")||"Sin métodos"}</td><td>{point.collectors?.map((collector:any)=><span key={collector.id}>{collector.name}<br/></span>)||"Sin asignar"}</td><td><div className="row-actions"><button className="link" disabled={busy} onClick={()=>void editCollectionPoint(point)}>Configurar</button><button className="link" disabled={busy} onClick={()=>void assignCollector(point)}>Asignar</button></div></td></tr>)}</tbody></table></div></section><section className="card"><h2>Cierres pendientes de conciliación</h2><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Punto</th><th>Recaudador</th><th>Total</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{closures.map(item=><tr key={item.id}><td>{date(item.periodEnd)}</td><td>{item.point}</td><td>{item.collector}</td><td>{money(item.netAmount)}</td><td>{item.status}</td><td>{item.status==="PENDING_SETTLEMENT"?<button className="link" disabled={busy} onClick={()=>void settleClosure(item)}>Conciliar</button>:"Verificado"}</td></tr>)}</tbody></table></div>{!closures.length&&<p className="empty">No existen cierres registrados.</p>}</section></>}
    {tab==="settings"&&settings&&<section className="card"><h2>Parámetros operativos</h2><p className="note">El enforcement permanece independiente para poder probar cálculos y pagos sin bloquear conductores.</p><div className="settings-grid">{setting("driverMembershipsEnabled","Módulo de membresías","checkbox")}{setting("membershipEnforcementEnabled","Aplicar bloqueo por vigencia","checkbox")}{setting("membershipUsageBillingEnabled","Contabilizar viajes adicionales","checkbox")}{setting("membershipSuspensionSchedulerEnabled","Scheduler de suspensión","checkbox")}{setting("membershipExpiryNoticeDays","Avisar antes de vencer (días)")}{setting("membershipGraceDays","Gracia general (días)")}{setting("membershipGraceAllowsTrips","Permitir viajes durante gracia","checkbox")}{setting("membershipSuspensionLocalTime","Hora local de suspensión","text")}{setting("membershipTimezone","Zona horaria","text")}{setting("newDriverGraceEnabled","Gracia inicial al aprobar","checkbox")}{setting("newDriverGraceDurationHours","Gracia inicial (horas)")}{setting("newDriverGraceAllowsTrips","Permitir viajes en gracia inicial","checkbox")}{setting("membershipExtraTripSharePercent","Porcentaje sobre adicional del pasajero")}{setting("membershipQrDurationHours","Vigencia QR (horas)")}{setting("navigationPickupProvider","Navegación a recogida","text")}{setting("navigationDestinationProvider","Navegación a destino","text")}{setting("textSearchMonthlyBudgetUsd","Presupuesto Text Search USD")}{setting("textSearchHardLimitEnabled","Detener Text Search en el límite","checkbox")}{setting("advertisingRotationSeconds","Rotación de publicidad (segundos)")}{setting("advertisingMaxActivePerZone","Campañas activas máximas por zona")}</div><button className="primary" disabled={busy||!can("settings:manage")} onClick={()=>void saveSettings()}>Guardar parámetros</button>{usage&&<div className="usage-summary"><h3>Consumo del período {usage.period}</h3><p>Text Search Pro: <strong>{usage.textSearch.used}</strong> · costo estimado {money(usage.textSearch.estimatedCost)}</p><p>Navigation SDK: <strong>{usage.navigation.used}</strong> solicitudes registradas</p></div>}</section>}
    {tab==="import"&&<section className="card"><h2>Importar conductores</h2><p>Solo carga información estructurada. Cada conductor debe establecer su contraseña, subir su foto y documentos y pasar por aprobación.</p><div className="import-actions"><button className="secondary" onClick={downloadTemplate}>Descargar plantilla</button><label className="primary file-button">Seleccionar CSV<input type="file" accept=".csv,text/csv" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void validateCsv(file);}}/></label></div>{importPreview&&<><div className="membership-stats compact"><Card label="Filas" value={importPreview.totalRows}/><Card label="Válidas" value={importPreview.validRows} tone="positive"/><Card label="Rechazadas" value={importPreview.rejectedRows} tone="danger"/></div><div className="table-wrap"><table><thead><tr><th>Fila</th><th>Conductor</th><th>Correo</th><th>Cooperativa</th><th>Resultado</th></tr></thead><tbody>{importPreview.items.map((item:any)=><tr key={item.rowNumber}><td>{item.rowNumber}</td><td>{item.firstNames} {item.lastNames}</td><td>{item.email}</td><td>{item.cooperativeCode}</td><td>{item.errors.length?item.errors.join(", "):"Válida"}</td></tr>)}</tbody></table></div><button className="primary" disabled={busy||importPreview.validRows===0} onClick={()=>void confirmImport()}>Confirmar {importPreview.validRows} cuentas</button></>}</section>}
  </div>;
}
