// Generated by scripts/generate-mototaxi-icon.mjs; edit packages/brand/mototaxi-icon.json.
export function MototaxiIcon({size=24,className=''}:{size?:number;className?:string}) {
  return <svg className={className} width={size} height={size} viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" focusable="false">
    <path d="M3 9 Q4 5 9 5 L18 5 Q20 5 21 8 L22 9 Z"/>
<path d="M4 10 L4 23 L5 23 M4 17 L12 17 M12 10 L12 20 L15 24 L20 24 L23 17 L27 17 L26 21 M20 11 L22 16 M27 17 L25 11"/>
<path d="M15 24 L11 24 M24 20 L26 24 M2 23 L5 23"/>
    <circle cx="8" cy="25" r="3.5"/>
<circle cx="26" cy="25" r="3.5"/>
  </svg>;
}
