import {useEffect,useMemo,useState} from 'react';
import {apiFetch} from './api';
import {ConsoleIcon,DataTable,ErrorState,LoadingState} from './console-ui';
import {ecuDate,navigateConsole,routeQuery} from './console-model';

type Props={token:string;permissions:string[]};
const patternLabels:Record<string,string>={FREQUENT_TRIP:'Viaje habitual',RETURN_HOME:'Regreso habitual',FAVORITE_DESTINATION:'Destino frecuente / favorito',REACTIVATION:'Usuario inactivo'};
const reasonLabels:Record<string,string>={ELIGIBLE:'Elegible',SMART_MODE_OFF:'SMART está apagado',TEST_USER_NOT_ALLOWED:'No pertenece a usuarios de prueba',PATTERN_TYPE_DISABLED:'Tipo desactivado',INSUFFICIENT_TRIPS:'Viajes insuficientes',INSUFFICIENT_MATCHES:'Coincidencias insuficientes',CONFIDENCE_TOO_LOW:'Confianza insuficiente',INVALID_FCM_TOKEN:'Sin token FCM válido',NOTIFICATIONS_DISABLED:'Permisos de notificación desactivados',ACTIVE_TRIP_EXISTS:'Tiene un viaje activo',RECENT_EQUIVALENT_TRIP:'Ya solicitó este trayecto recientemente',WEEKDAY_DISABLED:'Día no habilitado',OUTSIDE_ALLOWED_TIME:'Fuera del horario permitido',DAILY_LIMIT_REACHED:'Límite diario alcanzado',MINIMUM_INTERVAL_NOT_REACHED:'Intervalo mínimo no cumplido',OUTSIDE_PATTERN_WINDOW:'Fuera de la ventana habitual'};
const emptyConfig={mode:'OFF',frequentTripEnabled:true,returnTripEnabled:true,favoriteDestinationEnabled:true,reactivationEnabled:true,minimumTrips:5,minimumMatches:3,minimumConfidence:70,analysisWindowDays:30,scheduleToleranceMinutes:25,notificationLeadMinutes:15,maxPerUserPerDay:1,minimumIntervalMinutes:720,allowedStartTime:'06:00',allowedEndTime:'21:00',enabledWeekDays:[1,2,3,4,5,6,7],inactiveUserDays:21,schedulerIntervalMinutes:15};
const modes=['OFF','TEST','ON'] as const;
const tabs=[['summary','Resumen'],['smart','Inteligentes'],['campaigns','Campañas / Eventos'],['tests','Pruebas']] as const;
const smartTypes=[['frequentTripEnabled','Viaje habitual','Recuerda recorridos de ida'],['returnTripEnabled','Regreso habitual','Sugiere el regreso frecuente'],['favoriteDestinationEnabled','Destino frecuente / favorito','Usa destinos guardados y frecuentes'],['reactivationEnabled','Usuario inactivo','Invita a volver sin insistencia']] as const;
const smartParameters=[['minimumTrips','Viajes mínimos'],['minimumMatches','Coincidencias mínimas'],['minimumConfidence','Confianza mínima (%)'],['analysisWindowDays','Días analizados'],['scheduleToleranceMinutes','Margen horario (min)'],['notificationLeadMinutes','Anticipación (min)'],['maxPerUserPerDay','Máximo diario'],['minimumIntervalMinutes','Intervalo mínimo (min)'],['inactiveUserDays','Usuario inactivo (días)'],['schedulerIntervalMinutes','Frecuencia del análisis (min)']] as const;
function percent(value:unknown){return `${Number(value??0).toFixed(1)}%`;}
function ecuDateTimeLocal(date:Date){return new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Guayaquil',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(date).replace(' ','T');}
function Badge({value}:{value:string}){return <span className={`smart-badge ${value.toLowerCase()}`}>{value.replaceAll('_',' ')}</span>;}

export function NotificationsAdmin({token,permissions}:Props){
  const can=(permission:string)=>permissions.includes(permission),initial=routeQuery().get('sub')||'summary';
  const [tab,setTab]=useState(initial),[summary,setSummary]=useState<any>(),[config,setConfig]=useState<any>(emptyConfig),[patterns,setPatterns]=useState<any[]>([]),[campaigns,setCampaigns]=useState<any[]>([]),[testers,setTesters]=useState<any[]>([]),[selectedPattern,setSelectedPattern]=useState<any>(),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [userQuery,setUserQuery]=useState(''),[userMatches,setUserMatches]=useState<any[]>([]),[testForm,setTestForm]=useState({userId:'',type:'TEST_PUSH',title:'Prueba Costa-Go',message:'Esta notificación confirma el flujo real de Costa-Go.',deepLink:''});
  const [campaignDraft,setCampaignDraft]=useState<any>({name:'',campaignType:'EVENT',title:'',body:'',deepLink:'',action:'OPEN_NOTIFICATIONS',metadata:{},segment:{zones:[],roles:['PASSENGER'],platforms:[],userIds:[],userEmails:[]}}),[showCampaign,setShowCampaign]=useState(false),[scheduleCampaign,setScheduleCampaign]=useState<any>(),[previewCampaign,setPreviewCampaign]=useState<any>(),[scheduleAt,setScheduleAt]=useState('');
  async function load(){setLoading(true);try{const tasks=[apiFetch<any>('/v1/admin/notifications/summary',token),apiFetch<any>('/v1/admin/notifications/smart/config',token),apiFetch<any>('/v1/admin/notifications/smart/patterns?limit=100',token)];if(can('notification_campaigns:view'))tasks.push(apiFetch<any[]>('/v1/admin/notifications/campaigns',token));if(can('notifications:test'))tasks.push(apiFetch<any[]>('/v1/admin/notifications/test-users',token));const values=await Promise.all(tasks);setSummary(values[0]);setConfig(values[1]);setPatterns(values[2]?.items??[]);let index=3;if(can('notification_campaigns:view'))setCampaigns(values[index++]??[]);if(can('notifications:test'))setTesters(values[index]??[]);setError('');}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo cargar el módulo.');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[token]);
  useEffect(()=>{if(userQuery.trim().length<2){setUserMatches([]);return;}const timer=setTimeout(()=>void apiFetch<any[]>('/v1/admin/notifications/test-users/search?q='+encodeURIComponent(userQuery.trim()),token).then(setUserMatches).catch(()=>setUserMatches([])),300);return()=>clearTimeout(timer);},[userQuery,token]);
  function changeTab(next:string){setTab(next);navigateConsole('notifications',{sub:next});}
  async function run(action:()=>Promise<any>,success:string){setBusy(true);setNotice('');try{await action();setNotice(success);await load();}catch(reason){setNotice(reason instanceof Error?reason.message:'No se pudo completar la acción.');}finally{setBusy(false);}}
  async function saveConfig(){await run(()=>apiFetch('/v1/admin/notifications/smart/config',token,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(config)}),'Parámetros guardados y auditados.');}
  async function analyze(){await run(()=>apiFetch('/v1/admin/notifications/smart/analyze',token,{method:'POST',headers:{'content-type':'application/json'},body:'{}'}),'Análisis actualizado. SMART permanece sujeto al modo seleccionado.');}
  async function selectPattern(item:any){try{setSelectedPattern(await apiFetch('/v1/admin/notifications/smart/patterns/'+item.id,token));}catch(reason){setNotice(reason instanceof Error?reason.message:'No se pudo abrir el patrón.');}}
  async function addTester(userId:string){await run(()=>apiFetch('/v1/admin/notifications/test-users',token,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId})}),'Usuario agregado a pruebas.');setUserQuery('');setUserMatches([]);}
  async function removeTester(userId:string){await run(()=>apiFetch('/v1/admin/notifications/test-users/'+userId,token,{method:'DELETE'}),'Usuario retirado de pruebas.');}
  async function sendTest(){await run(()=>apiFetch('/v1/admin/notifications/test-send',token,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(testForm)}),'Prueba enviada por el flujo real de FCM.');}
  async function createCampaign(){await run(()=>apiFetch('/v1/admin/notifications/campaigns',token,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(campaignDraft)}),'Campaña guardada como borrador. Revisa la audiencia antes de programarla.');setShowCampaign(false);}
  async function prepareCampaignSchedule(item:any){try{const estimate=await apiFetch<any>(`/v1/admin/notifications/campaigns/${item.id}/estimate`,token,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});setScheduleCampaign({...item,estimate});setScheduleAt(ecuDateTimeLocal(new Date(Date.now()+5*60000)));}catch(reason){setNotice(reason instanceof Error?reason.message:'No se pudo calcular la audiencia.');}}
  async function confirmCampaignSchedule(){if(!scheduleCampaign||!scheduleAt)return;await run(()=>apiFetch(`/v1/admin/notifications/campaigns/${scheduleCampaign.id}/schedule`,token,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({scheduledAt:new Date(`${scheduleAt}:00-05:00`).toISOString()})}),'Campaña programada. La audiencia se revalidará justo antes del envío.');setScheduleCampaign(undefined);}
  async function testCampaign(id:string){const tester=testers.find(item=>item.enabled&&item.platform);if(!tester){setNotice('Agrega un cliente de prueba con token válido antes de probar una campaña.');return;}await run(()=>apiFetch(`/v1/admin/notifications/campaigns/${id}/test`,token,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId:tester.id})}),`Prueba enviada a ${tester.name}.`);}
  async function openCampaignPreview(item:any){setBusy(true);setNotice('');try{const [detail,estimate]=await Promise.all([apiFetch<any>(`/v1/admin/notifications/campaigns/${item.id}`,token),apiFetch<any>(`/v1/admin/notifications/campaigns/${item.id}/estimate`,token,{method:'POST',headers:{'content-type':'application/json'},body:'{}'})]);setPreviewCampaign({...detail,estimate});}catch(reason){setNotice(reason instanceof Error?reason.message:'No se pudo abrir la vista previa.');}finally{setBusy(false);}}
  async function campaignAction(id:string,action:'cancel'){await apiFetch<any>(`/v1/admin/notifications/campaigns/${id}/${action}`,token,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});setNotice('Campaña cancelada.');await load();}
  const sent=Number(summary?.sentToday??0),opened=Number(summary?.openedToday??0),openRate=sent?opened/sent*100:0;
  const metricItems=[['Usuarios analizados',summary?.usersAnalyzed??0,'users'],['Patrones detectados',summary?.patternsDetected??0,'chart'],['Elegibles hoy',summary?.eligible??0,'check'],['Enviadas hoy',sent,'mail'],['Abiertas hoy',opened,'bell'],['Viajes generados',summary?.tripsGenerated??0,'trips'],['Conversión',percent(summary?.conversion),'chart']];
  if(loading)return <LoadingState label="Cargando Notificaciones Inteligentes…"/>;
  if(error)return <ErrorState message={error} onRetry={()=>void load()}/>;
  return <div className="smart-notifications">
    <section className="smart-hero"><div><span className="eyebrow">MOTOR DE RECOMENDACIONES Y CAMPAÑAS</span><h2>Notificaciones Inteligentes</h2><p>Evolución del centro actual: mismo FCM, misma campana y control administrativo.</p></div><div className="smart-engine-state"><small>Estado del motor</small><Badge value={config.mode}/>{can('notification_campaigns:manage')&&<button className="primary" onClick={()=>{setShowCampaign(true);changeTab('campaigns');}}>+ Nueva campaña</button>}</div></section>
    {notice&&<div className="smart-notice" role="status">{notice}</div>}
    <div className="smart-metrics">{metricItems.map(([label,value,icon])=><article key={String(label)}><span><ConsoleIcon name={String(icon)}/></span><div><small>{label}</small><strong>{value}</strong><em>{label==='Abiertas hoy'?`${openRate.toFixed(1)}% de apertura`:'Datos reales registrados'}</em></div></article>)}</div>
    <nav className="smart-tabs" aria-label="Secciones de notificaciones">{tabs.filter(([id])=>id!=='campaigns'||can('notification_campaigns:view')).filter(([id])=>id!=='tests'||can('notifications:test')).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>changeTab(id)}>{label}</button>)}</nav>
    {tab==='summary'&&<><section className="smart-summary-grid"><article className="card smart-chart"><div className="smart-section-heading"><div><span className="eyebrow">ÚLTIMOS 30 DÍAS</span><h3>Evolución del motor</h3></div><button className="secondary" onClick={()=>void load()}>Actualizar</button></div><Trend rows={summary?.trend??[]}/></article><article className="card smart-status-card"><span className="eyebrow">CONTROL SEGURO</span><h3>Estado actual: {config.mode}</h3><p>{config.mode==='OFF'?'Los patrones se analizan, pero no se envían recomendaciones SMART.':config.mode==='TEST'?'Solo los usuarios incluidos en Pruebas pueden recibir recomendaciones SMART.':'Solo usuarios elegibles reciben recomendaciones dentro de los límites configurados.'}</p><ul><li>Notificaciones críticas sin límites SMART</li><li>Campana y centro móvil existentes</li><li>Idempotencia por usuario y ventana</li><li>Cero campañas automáticas</li></ul><button className="secondary" onClick={()=>changeTab('smart')}>Revisar configuración</button></article></section><section className="card"><div className="smart-section-heading"><div><span className="eyebrow">PATRONES RECIENTES</span><h3>Usuarios elegibles y comportamiento detectado</h3></div><button className="secondary" onClick={()=>changeTab('smart')}>Ver todos</button></div><PatternTable items={patterns.slice(0,8)} onSelect={selectPattern}/></section></>}
    {tab==='smart'&&<div className="smart-workspace"><main><section className="card"><div className="smart-section-heading"><div><span className="eyebrow">MODO DEL MOTOR</span><h3>OFF, TEST u ON</h3></div>{can('notifications:manage')&&<button className="primary" disabled={busy} onClick={()=>void saveConfig()}>Guardar parámetros</button>}</div><div className="smart-mode-selector">{modes.map(mode=><button key={mode} className={config.mode===mode?'active '+mode.toLowerCase():''} onClick={()=>setConfig({...config,mode})} disabled={!can('notifications:manage')}><strong>{mode}</strong><small>{mode==='OFF'?'Analiza sin enviar':mode==='TEST'?'Solo whitelist':'Elegibles reales'}</small></button>)}</div><div className="smart-type-grid">{smartTypes.map(([key,title,help])=><label key={key}><span><strong>{title}</strong><small>{help}</small></span><input type="checkbox" checked={Boolean(config[key])} disabled={!can('notifications:manage')} onChange={e=>setConfig({...config,[key]:e.target.checked})}/></label>)}</div><div className="smart-parameter-grid">{smartParameters.map(([key,label])=><label key={key}>{label}<input type="number" value={config[key]} disabled={!can('notifications:manage')} onChange={e=>setConfig({...config,[key]:Number(e.target.value)})}/></label>)}<label>Horario desde<input type="time" value={config.allowedStartTime} disabled={!can('notifications:manage')} onChange={e=>setConfig({...config,allowedStartTime:e.target.value})}/></label><label>Horario hasta<input type="time" value={config.allowedEndTime} disabled={!can('notifications:manage')} onChange={e=>setConfig({...config,allowedEndTime:e.target.value})}/></label></div>{can('notifications:manage')&&<button className="secondary" disabled={busy} onClick={()=>void analyze()}><ConsoleIcon name="refresh"/> Analizar patrones ahora</button>}</section><section className="card"><div className="smart-section-heading"><div><span className="eyebrow">ELEGIBILIDAD EXPLICABLE</span><h3>Patrones detectados</h3></div><span>{patterns.length} patrones</span></div><PatternTable items={patterns} onSelect={selectPattern}/></section></main><aside>{selectedPattern?<PatternDetail item={selectedPattern} canTest={can('notifications:test')} busy={busy} onTest={()=>void run(()=>apiFetch(`/v1/admin/notifications/smart/patterns/${selectedPattern.id}/test-send`,token,{method:'POST'}),'Prueba SMART enviada al tester.')}/>:<section className="card smart-preview-empty"><ConsoleIcon name="chart" size={38}/><h3>Vista previa del patrón</h3><p>Selecciona un patrón para conocer sus coincidencias, confianza y motivos de elegibilidad.</p></section>}</aside></div>}
    {tab==='campaigns'&&<><section className="card"><div className="smart-section-heading"><div><span className="eyebrow">CONTROL ADMINISTRATIVO</span><h3>Campañas y eventos</h3><p>Los comercios no envían push directamente. Costa-Go crea, prueba, programa y audita.</p></div>{can('notification_campaigns:manage')&&<button className="primary" onClick={()=>setShowCampaign(true)}>+ Nueva campaña</button>}</div><DataTable headers={['Nombre','Tipo','Segmento','Programación','Destinatarios','Estado','Apertura','Acciones']} rows={campaigns.map(item=>[<strong>{item.name}</strong>,item.type,<small>{(item.segment?.zones??[]).join(', ')||'Todas las zonas'} · {(item.segment?.roles??[]).join(', ')||'Todos los roles'}</small>,item.scheduledAt?ecuDate(item.scheduledAt):'Sin programar',item.recipients??0,<Badge value={item.status}/>,item.sent?percent(Number(item.opened??0)/Number(item.sent)*100):'—',<div><button className="link" disabled={busy} onClick={()=>void openCampaignPreview(item)}>Vista previa</button>{can('notifications:test')&&<button className="link" onClick={()=>void testCampaign(item.id)}>Probar</button>}{can('notification_campaigns:manage')&&item.status==='DRAFT'&&<button className="link" onClick={()=>void prepareCampaignSchedule(item)}>Programar</button>}{can('notification_campaigns:manage')&&['DRAFT','SCHEDULED'].includes(item.status)&&<button className="link danger" onClick={()=>void campaignAction(item.id,'cancel')}>Cancelar</button>}</div>])}/></section></>}
    {tab==='tests'&&<div className="smart-tests-grid"><section className="card"><span className="eyebrow">WHITELIST TEST</span><h3>Clientes de prueba</h3><p>En modo TEST, nadie fuera de esta lista recibe SMART.</p><label className="smart-user-search"><ConsoleIcon name="search"/><input value={userQuery} onChange={e=>setUserQuery(e.target.value)} placeholder="Buscar usuario existente…"/></label>{userMatches.length>0&&<div className="smart-search-results">{userMatches.map(user=><button key={user.id} disabled={!user.validToken||busy} onClick={()=>void addTester(user.id)}><span><strong>{user.name}</strong><small>{user.email} · {user.platform??'Sin dispositivo'}</small></span><em>{user.validToken?'Agregar':'Sin token'}</em></button>)}</div>}<div className="smart-testers">{testers.map(user=><article key={user.id}><span className="smart-avatar">{user.name?.slice(0,1)}</span><div><strong>{user.name}</strong><small>{user.email}<br/>{user.platform??'Sin plataforma'} · última actividad {ecuDate(user.lastActivity)}</small></div><button className="link danger" disabled={busy} onClick={()=>void removeTester(user.id)}>Eliminar</button></article>)}</div></section><section className="card"><span className="eyebrow">FCM REAL</span><h3>Enviar prueba de notificación</h3><p>Valida foreground, background, app cerrada, sonido, vibración, icono, campana, contador y deep-link.</p><label>Usuario tester<select value={testForm.userId} onChange={e=>setTestForm({...testForm,userId:e.target.value})}><option value="">Selecciona…</option>{testers.filter(t=>t.enabled).map(t=><option key={t.id} value={t.id}>{t.name} · {t.platform??'sin plataforma'}</option>)}</select></label><label>Tipo<select value={testForm.type} onChange={e=>setTestForm({...testForm,type:e.target.value})}><option value="TEST_PUSH">Prueba general</option><option value="SMART_FREQUENT_TRIP">Viaje habitual</option><option value="SMART_RETURN_HOME">Regreso habitual</option><option value="CAMPAIGN">Campaña</option></select></label><label>Título<input value={testForm.title} maxLength={120} onChange={e=>setTestForm({...testForm,title:e.target.value})}/></label><label>Mensaje<textarea value={testForm.message} maxLength={500} onChange={e=>setTestForm({...testForm,message:e.target.value})}/></label><label>Deep-link<input value={testForm.deepLink} placeholder="costa-go://trip/prepare" onChange={e=>setTestForm({...testForm,deepLink:e.target.value})}/></label><button className="primary" disabled={busy||!testForm.userId||!testForm.title||!testForm.message} onClick={()=>void sendTest()}><ConsoleIcon name="mail"/> Enviar ahora</button><small>Se enviará por NotificationService → FCM → dispositivo y quedará en el centro actual.</small></section></div>}
    {showCampaign&&<div className="smart-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowCampaign(false);}}><form className="smart-modal" onSubmit={e=>{e.preventDefault();void createCampaign();}}>
      <div className="smart-section-heading"><div><span className="eyebrow">NUEVO BORRADOR</span><h3>Crear campaña / evento</h3></div><button type="button" className="smart-close" onClick={()=>setShowCampaign(false)}>×</button></div>
      <div className="smart-form-grid">
        <label>Nombre interno<input required minLength={3} value={campaignDraft.name} onChange={e=>setCampaignDraft({...campaignDraft,name:e.target.value})}/></label>
        <label>Tipo<select value={campaignDraft.campaignType} onChange={e=>setCampaignDraft({...campaignDraft,campaignType:e.target.value})}><option value="EVENT">Evento</option><option value="CAMPAIGN">Campaña</option><option value="PROMOTIONAL">Promoción aprobada</option></select></label>
        <label className="wide">Título<input required maxLength={120} value={campaignDraft.title} onChange={e=>setCampaignDraft({...campaignDraft,title:e.target.value})}/></label>
        <label className="wide">Mensaje<textarea required maxLength={500} value={campaignDraft.body} onChange={e=>setCampaignDraft({...campaignDraft,body:e.target.value})}/></label>
        <label>Roles<select multiple value={campaignDraft.segment.roles} onChange={e=>setCampaignDraft({...campaignDraft,segment:{...campaignDraft.segment,roles:[...e.target.selectedOptions].map(o=>o.value)}})}><option value="PASSENGER">Pasajeros</option><option value="DRIVER">Conductores</option></select></label>
        <label>Plataformas<select multiple value={campaignDraft.segment.platforms} onChange={e=>setCampaignDraft({...campaignDraft,segment:{...campaignDraft.segment,platforms:[...e.target.selectedOptions].map(o=>o.value)}})}><option value="ANDROID">Android</option><option value="IOS">iOS</option></select></label>
        <label>Zonas (separadas por coma)<input value={(campaignDraft.segment.zones??[]).join(', ')} placeholder="Atacames, Tonsupa" onChange={e=>setCampaignDraft({...campaignDraft,segment:{...campaignDraft.segment,zones:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)}})}/></label>
        <label>Actividad reciente (días)<input type="number" min="1" max="365" value={campaignDraft.segment.activeWithinDays??''} onChange={e=>setCampaignDraft({...campaignDraft,segment:{...campaignDraft.segment,activeWithinDays:e.target.value?Number(e.target.value):undefined}})}/></label>
        <label className="wide">Correos de usuarios específicos<textarea value={(campaignDraft.segment.userEmails??[]).join(', ')} placeholder="usuario@correo.com, otro@correo.com · vacío = usar todo el segmento" onChange={e=>setCampaignDraft({...campaignDraft,segment:{...campaignDraft.segment,userEmails:e.target.value.split(/[;,\n]/).map(v=>v.trim().toLowerCase()).filter(Boolean)}})}/><small>El sistema resuelve internamente cada correo; no necesitas conocer UUID.</small></label>
        <label className="wide">Deep-link opcional<input value={campaignDraft.deepLink} onChange={e=>setCampaignDraft({...campaignDraft,deepLink:e.target.value})}/></label>
      </div>
      <div className="smart-modal-actions"><button type="button" className="secondary" onClick={()=>setShowCampaign(false)}>Cancelar</button><button className="primary" disabled={busy}>Guardar borrador</button></div>
    </form></div>}
    {previewCampaign&&<div className="smart-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setPreviewCampaign(undefined);}}><section className="smart-modal smart-campaign-preview">
      <div className="smart-section-heading"><div><span className="eyebrow">VISTA PREVIA DE CAMPAÑA</span><h3>{previewCampaign.name}</h3></div><button type="button" className="smart-close" onClick={()=>setPreviewCampaign(undefined)}>×</button></div>
      <div className="smart-preview-push"><img src="/costa-go-emblem.png"/><div><strong>{previewCampaign.title}</strong><p>{previewCampaign.body}</p>{previewCampaign.deepLink&&<a href={previewCampaign.deepLink} target="_blank" rel="noreferrer">Abrir enlace configurado</a>}</div></div>
      <div className="smart-audience-preview"><span><small>Encontrados</small><strong>{previewCampaign.estimate.usersFound}</strong></span><span><small>Elegibles ahora</small><strong>{previewCampaign.estimate.total}</strong></span><span><small>Android</small><strong>{previewCampaign.estimate.android}</strong></span><span><small>iOS</small><strong>{previewCampaign.estimate.ios}</strong></span><span><small>Sin token válido</small><strong>{previewCampaign.estimate.withoutValidToken}</strong></span><span><small>Estado</small><strong>{previewCampaign.status}</strong></span></div>
      <div className="smart-audience-list"><div className="smart-audience-list-head"><strong>Audiencia por correo</strong><small>Token actual y resultado del envío</small></div>{previewCampaign.estimate.users.map((user:any)=>{const recipient=(previewCampaign.recipients??[]).find((item:any)=>item.email?.toLowerCase()===user.email?.toLowerCase());return <article key={user.id}><div><strong>{user.name}</strong><small>{user.email}</small></div><span>{user.platform??'Sin dispositivo'}</span><Badge value={recipient?.status??user.reason}/>{recipient?.errorMessage&&<small title={recipient.errorMessage}>{recipient.errorCode??recipient.errorMessage}</small>}</article>;})}</div>
      <div className="smart-modal-actions"><button type="button" className="primary" onClick={()=>setPreviewCampaign(undefined)}>Cerrar</button></div>
    </section></div>}
    {scheduleCampaign&&<div className="smart-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setScheduleCampaign(undefined);}}><form className="smart-modal smart-schedule-modal" onSubmit={e=>{e.preventDefault();void confirmCampaignSchedule();}}>
      <div className="smart-section-heading"><div><span className="eyebrow">VISTA PREVIA OBLIGATORIA</span><h3>Programar {scheduleCampaign.name}</h3></div><button type="button" className="smart-close" onClick={()=>setScheduleCampaign(undefined)}>×</button></div>
      <div className="smart-audience-preview"><span><small>Usuarios encontrados</small><strong>{scheduleCampaign.estimate.usersFound}</strong></span><span><small>Total elegible</small><strong>{scheduleCampaign.estimate.total}</strong></span><span><small>Android</small><strong>{scheduleCampaign.estimate.android}</strong></span><span><small>iOS</small><strong>{scheduleCampaign.estimate.ios}</strong></span><span><small>Sin token válido</small><strong>{scheduleCampaign.estimate.withoutValidToken}</strong></span><span><small>Excluidos</small><strong>{scheduleCampaign.estimate.excluded}</strong></span></div>
      <p>La audiencia y los límites se validarán nuevamente justo antes del envío.</p>
      <label>Fecha y hora de Ecuador<input required type="datetime-local" value={scheduleAt} min={ecuDateTimeLocal(new Date(Date.now()+120000))} onChange={e=>setScheduleAt(e.target.value)}/></label>
      <div className="smart-modal-actions"><button type="button" className="secondary" onClick={()=>setScheduleCampaign(undefined)}>Cancelar</button><button className="primary" disabled={busy||!scheduleAt}>Confirmar programación</button></div>
    </form></div>}
  </div>;
}

function PatternTable({items,onSelect}:{items:any[];onSelect:(item:any)=>void}){return <DataTable headers={['Usuario','Patrón principal','Confianza','Horario','Coincidencias','Acciones']} rows={items.map(item=>[<strong>{item.user}</strong>,<span>{patternLabels[item.type]??item.type}<small>{item.origin||'—'} → {item.destination||'—'}</small></span>,<span className="smart-confidence"><strong>{percent(item.confidence)}</strong><i style={{width:`${Math.min(100,Number(item.confidence))}%`}}/></span>,item.averageTime?.slice(0,5)||'—',`${item.matches} de ${item.tripsAnalyzed}`,<button className="link" onClick={()=>onSelect(item)}>Analizar</button>])}/>;}
function PatternDetail({item,canTest,busy,onTest}:{item:any;canTest:boolean;busy:boolean;onTest:()=>void}){return <section className="card smart-pattern-detail"><div className="smart-section-heading"><div><span className="eyebrow">VISTA PREVIA DE PATRÓN</span><h3>{item.user}</h3></div><span className="smart-confidence-label">{percent(item.confidence)} confianza</span></div><h4>{item.origin||'Origen'} → {item.destination||'Destino'}</h4><div className="smart-detail-metrics"><span><small>Días</small><strong>{(item.weekDays??[]).join(', ')||'—'}</strong></span><span><small>Hora promedio</small><strong>{item.averageTime?.slice(0,5)||'—'}</strong></span><span><small>Coincidencias</small><strong>{item.matches}</strong></span></div><div className={`smart-eligibility ${item.eligible?'eligible':'blocked'}`}><strong>{item.eligible?'Elegible':'No elegible'}</strong>{(item.reasons??[]).map((reason:string)=><span key={reason}>{reasonLabels[reason]??reason}</span>)}</div><div className="smart-preview-push"><img src="/costa-go-emblem.png"/><div><strong>Vista previa</strong><p>{item.type==='RETURN_HOME'?'¿Listo para regresar a casa?':'¿Listo para tu viaje habitual?'}</p><small>Tu destino habitual está preparado.</small></div></div>{canTest&&<button className="primary" disabled={busy||!item.tester} onClick={onTest}>Enviar prueba</button>}{canTest&&!item.tester&&<small>Agrega este usuario a Pruebas antes de enviar.</small>}</section>;}
function Trend({rows}:{rows:any[]}){const width=760,height=220,max=Math.max(1,...rows.flatMap(r=>[Number(r.sent),Number(r.opened),Number(r.trips)]));const line=(key:string)=>rows.map((row,index)=>`${index?'L':'M'} ${Math.round(index*Math.max(1,width/(rows.length-1)))} ${height-20-Math.round(Number(row[key])/max*(height-45))}`).join(' ');return <div className="smart-trend"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Enviadas, abiertas y viajes generados en 30 días"><path d={line('sent')} className="sent"/><path d={line('opened')} className="opened"/><path d={line('trips')} className="trips"/></svg><div><span className="sent">Enviadas</span><span className="opened">Abiertas</span><span className="trips">Viajes generados</span></div></div>;}
