import {useEffect,useState,type FormEvent} from 'react';
import {apiFetch} from './api';
import {ConsoleModal,ManagedTable} from './console-ui';
import {ecuDate} from './console-model';
type Program={id?:string;version?:number;code:string;name:string;description:string;audience:string;startsAt:string;endsAt:string;qualifyingEvent:string;requiredTrips:number;mustBeApproved:boolean;mustBeActive:boolean;referrerBenefitCode:string;referredBenefitCode:string|null;maxRewardsPerReferrer:number|null;maxGlobalRewards:number|null;zoneIds:string[];status:string;shareMessage:string;condition?:string;metrics?:Record<string,number>};
const events:Record<string,string>={REGISTRATION_COMPLETED:'Cuenta confirmada (entrega sin exigir viajes)',PASSENGER_FIRST_COMPLETED_TRIP:'Primer viaje completado como pasajero',DRIVER_APPROVED:'Aprobación del conductor',DRIVER_FIRST_COMPLETED_TRIP:'Primer viaje completado como conductor',DRIVER_APPROVED_AND_FIRST_COMPLETED_TRIP:'Conductor aprobado y primer viaje completado',X_COMPLETED_TRIPS:'Completar una cantidad de viajes',FIRST_COMPLETED_TRIP:'Primer viaje completado (según rol del invitado)',DRIVER_APPROVED_AND_X_COMPLETED_TRIPS:'Conductor aprobado y cantidad de viajes'};
const statuses:Record<string,string>={DRAFT:'Borrador',ACTIVE:'Activo',PAUSED:'Pausado',FINISHED:'Finalizado',PENDING:'Pendiente de condición',QUALIFIED:'Calificado, pendiente de premio',REWARDED:'Recompensa entregada',REJECTED:'No calificó en plazo'};
const root='/v1/admin/referral-programs';
const local=(v:string)=>v?new Date(Date.parse(v)-5*3600000).toISOString().slice(0,16):'';
const iso=(v:string)=>v?new Date(v+'-05:00').toISOString():'';
const initial=():Program=>({code:'',name:'',description:'',audience:'DRIVER',startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+30*86400000).toISOString(),qualifyingEvent:'DRIVER_APPROVED_AND_FIRST_COMPLETED_TRIP',requiredTrips:1,mustBeApproved:true,mustBeActive:true,referrerBenefitCode:'',referredBenefitCode:null,maxRewardsPerReferrer:null,maxGlobalRewards:null,zoneIds:[],status:'DRAFT',shareMessage:'Te invito a usar Costa-Go. Regístrate y utiliza mi código: {code}. {url}'});
export function ReferralPrograms({token,permissions}:{token:string;permissions:string[]}){
 const [rows,setRows]=useState<Program[]>([]),[benefits,setBenefits]=useState<any[]>([]),[zones,setZones]=useState<any[]>([]),[form,setForm]=useState<Program|null>(null),[detail,setDetail]=useState<any>(null),[revision,setRevision]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [testEmail,setTestEmail]=useState(''),[testTrip,setTestTrip]=useState(''),[excluded,setExcluded]=useState(true);
 const can=permissions.includes('benefits:manage');
 useEffect(()=>{const c=new AbortController();Promise.all([apiFetch<{items:Program[]}>(root,token,{signal:c.signal}),apiFetch<{items:any[];zones:any[]}>('/v1/admin/benefits',token,{signal:c.signal})]).then(([p,b])=>{setRows(p.items);setBenefits(b.items);setZones(b.zones);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[token,revision]);
 const run=async(fn:()=>Promise<void>)=>{setError('');setBusy(true);try{await fn();setRevision(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const set=(key:keyof Program,value:unknown)=>setForm(p=>p?{...p,[key]:value}:p);
 const save=(e:FormEvent)=>{e.preventDefault();if(!form)return;void run(async()=>{const {id,version,condition,metrics,...data}=form;await apiFetch(id?`${root}/${id}`:root,token,{method:id?'PUT':'POST',body:JSON.stringify({...data,...(id?{version}:{})})});setForm(null);});};
 return <section className="costa-campaigns"><div className="campaign-intro"><div><small>BENEFICIOS Y RECOMPENSAS</small><h2>Programas de referidos</h2><p>Premia condiciones verificadas por Costa-Go. Los montos y días vienen de las definiciones de beneficios.</p></div>{can&&<button onClick={()=>setForm(initial())}>Crear programa</button>}</div>{error&&<p className="error" role="alert">{error}</p>}
 <div className="campaign-notice"><div><strong>Relación fija y entrega automática</strong><p>El invitado tiene hasta 7 días desde su registro para ingresar un código, antes de iniciar un viaje o recibir un beneficio. La cuenta debe estar confirmada. Una cuenta solo tiene un referente.</p><p>Pausar o finalizar impide nuevas referencias; las ya registradas conservan la oportunidad de calificar hasta la fecha de fin. Cada invitado conserva una copia de las reglas con las que entró. Las ediciones solo aplican a futuras referencias.</p></div></div>
 <ManagedTable><thead><tr>{['Programa','Condición','Vigencia','Registros / códigos usados','Pendientes / calificados','Premiados / conversión','Estado','Acciones'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><strong>{p.name}</strong><br/>{p.code}<br/>{p.audience}</td><td>{p.condition}</td><td>{ecuDate(p.startsAt)}<br/>{ecuDate(p.endsAt)}</td><td>{p.metrics?.registered??0} / {p.metrics?.codesUsed??0}<br/>{p.metrics?.linksUsed??0} por enlace · {p.metrics?.manualCodesUsed??0} manuales</td><td>{p.metrics?.pending??0} / {p.metrics?.qualified??0}</td><td>{p.metrics?.rewarded??0} referidos · {p.metrics?.grants??0} beneficios / {p.metrics?.registered?Math.round(100*(p.metrics.qualified??0)/p.metrics.registered):0}%{Boolean(p.metrics?.blocked)&&<p>{p.metrics?.blocked} con motivo pendiente</p>}</td><td>{statuses[p.status]}</td><td>{can&&<button className="secondary" onClick={()=>setForm(p)}>Editar / estado</button>}<button className="secondary" onClick={()=>void run(async()=>setDetail(await apiFetch(`${root}/${p.id}/referrals`,token)))}>Referidos y auditoría</button></td></tr>)}</tbody></ManagedTable>
 {can&&<details className="campaign-section"><summary>Cuentas y viajes de prueba</summary><p>Marca antes de completar el viaje. No revierte premios ya entregados. Las exclusiones se auditan y no bloquean el resto de la app.</p><div className="campaign-fields"><label>Email de cuenta de pruebas<input type="email" value={testEmail} onChange={e=>{setTestEmail(e.target.value);setTestTrip('');}}/></label><label>O ID de viaje de pruebas<input value={testTrip} onChange={e=>{setTestTrip(e.target.value);setTestEmail('');}}/></label><label className="check"><input type="checkbox" checked={excluded} onChange={e=>setExcluded(e.target.checked)}/>Excluir de las recompensas por referidos</label><button disabled={busy||(!testEmail&&!testTrip)} onClick={()=>void run(async()=>{await apiFetch('/v1/admin/referral-exclusions',token,{method:'POST',body:JSON.stringify({...(testEmail?{userEmail:testEmail}:{tripId:testTrip}),excluded})});setTestEmail('');setTestTrip('');})}>Guardar exclusión</button></div></details>}
 {detail&&<ConsoleModal title="Referidos y auditoría" onClose={()=>setDetail(null)} className="campaign-modal"><ManagedTable><thead><tr>{['Referente','Invitado','Estado','Fecha','Motivo / referencia real'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{detail.items.map((r:any)=><tr key={r.id}><td>{r.referrer}</td><td>{r.referred}</td><td>{statuses[r.status]}</td><td>{ecuDate(r.created_at)}</td><td>{r.progress?.condition}<br/>{r.progress?.completedTrips} completados / {r.progress?.requiredTrips} requeridos · {r.progress?.remainingTrips} pendientes<br/>{r.last_error??r.qualifying_reference_id??'Pendiente'}</td></tr>)}</tbody></ManagedTable><p>Últimos 200 referidos. Calificado sin entrega significa que un límite, cuenta o beneficio requiere revisión; el sistema reintenta automáticamente.</p>{detail.history.map((h:any,i:number)=><p key={i}>{ecuDate(h.created_at)} · {h.action}<br/>{JSON.stringify(h.next_value)}</p>)}</ConsoleModal>}
 {form&&<ConsoleModal title={form.id?'Editar programa':'Crear programa'} onClose={()=>{if(!busy)setForm(null);}} className="campaign-modal"><form onSubmit={save} className="campaign-form">{error&&<p className="error" role="alert">{error}</p>}<section className="campaign-section"><h3>Identidad, audiencia y vigencia</h3><div className="campaign-fields"><label>Nombre<input required maxLength={120} value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Código del programa<input required disabled={!!form.id} pattern="[A-Z][A-Z0-9_]{2,79}" value={form.code} onChange={e=>set('code',e.target.value)}/><small>Es distinto del código personal de cada usuario.</small></label><label className="wide">Descripción pública<textarea required maxLength={1000} value={form.description} onChange={e=>set('description',e.target.value)}/></label><label>Audiencia<select value={form.audience} onChange={e=>{set('audience',e.target.value);if(e.target.value!=='DRIVER')set('mustBeApproved',false);}}><option value="DRIVER">Conductores</option><option value="PASSENGER">Pasajeros</option><option value="BOTH">Ambos</option></select></label><label>Estado<select value={form.status} onChange={e=>set('status',e.target.value)}>{['DRAFT','ACTIVE','PAUSED','FINISHED'].map(s=><option key={s} value={s}>{statuses[s]}</option>)}</select></label><label>Inicio (Ecuador)<input type="datetime-local" required value={local(form.startsAt)} onChange={e=>set('startsAt',iso(e.target.value))}/></label><label>Fin para registrarse y calificar (Ecuador)<input type="datetime-local" required value={local(form.endsAt)} onChange={e=>set('endsAt',iso(e.target.value))}/></label></div></section>
 <section className="campaign-section"><h3>Condición y recompensas</h3><p>Recomendado: primer viaje completado para pasajeros; aprobación y primer viaje para conductores. Viajes cancelados, incompletos o marcados como prueba no cuentan.</p><div className="campaign-fields"><label>Evento calificante<select value={form.qualifyingEvent} onChange={e=>{set('qualifyingEvent',e.target.value);set('requiredTrips',1);if(e.target.value.startsWith('DRIVER_APPROVED'))set('mustBeApproved',true);}}>{Object.entries(events).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{['X_COMPLETED_TRIPS','DRIVER_APPROVED_AND_X_COMPLETED_TRIPS'].includes(form.qualifyingEvent)&&<label>Viajes requeridos<input type="number" min={1} max={100} required value={form.requiredTrips} onChange={e=>set('requiredTrips',Number(e.target.value))}/></label>}
 <label className="check"><input type="checkbox" checked={form.mustBeActive} onChange={e=>set('mustBeActive',e.target.checked)}/>Exigir cuenta activa para cumplir la condición<small>La entrega del beneficio siempre respeta los controles de cuenta del motor de beneficios.</small></label>
 {form.audience==='DRIVER'&&<label className="check"><input type="checkbox" checked={form.mustBeApproved||form.qualifyingEvent.startsWith('DRIVER_APPROVED')} disabled={form.qualifyingEvent.startsWith('DRIVER_APPROVED')} onChange={e=>set('mustBeApproved',e.target.checked)}/>Exigir aprobación del conductor<small>Se combina con la cantidad de viajes. Los eventos de aprobación siempre la requieren.</small></label>}
 {(['referrerBenefitCode','referredBenefitCode'] as const).map((key,i)=><label key={key}>{i?'Beneficio del invitado (opcional)':'Beneficio del referente'}<select required={!i} value={form[key]??''} onChange={e=>set(key,e.target.value||null)}><option value="">{i?'Sin beneficio adicional':'Seleccionar beneficio'}</option>{benefits.filter(b=>!b.requiresActivation&&(i||!b.oneTime)&&(b.audience==='BOTH'||b.audience===form.audience)&&['COURTESY_DAYS','PROMOTIONAL_BALANCE'].includes(b.benefitType)).map(b=><option key={b.code} value={b.code}>{b.name} · {b.value} {b.benefitType==='COURTESY_DAYS'?'días':'USD promocionales'} · {b.status}</option>)}</select><small>Debe ser automático y cubrir toda la vigencia del programa. Sus valores quedan protegidos al registrar el primer referido; para cambiarlos, crea otro beneficio.</small></label>)}
 <label>Máximo de premios por referente<input type="number" min={1} value={form.maxRewardsPerReferrer??''} onChange={e=>set('maxRewardsPerReferrer',e.target.value?Number(e.target.value):null)}/><small>Vacío: sin límite específico. También aplican los límites del beneficio.</small></label><label>Máximo global de referidos premiados<input type="number" min={1} value={form.maxGlobalRewards??''} onChange={e=>set('maxGlobalRewards',e.target.value?Number(e.target.value):null)}/><small>Cada referido cuenta una vez, aunque reciban beneficio ambos participantes.</small></label></div></section>
 <section className="campaign-section"><h3>Zonas y mensaje compartido</h3><p>Sin zonas seleccionadas: global. El servidor comprueba el área al registrar la referencia.</p><div className="campaign-fields">{zones.map(z=><label className="check" key={z.id}><input type="checkbox" disabled={!z.enabled} checked={form.zoneIds.includes(z.id)} onChange={e=>set('zoneIds',e.target.checked?[...form.zoneIds,z.id]:form.zoneIds.filter(x=>x!==z.id))}/>{z.name}</label>)}<label className="wide">Mensaje de invitación<textarea required maxLength={600} value={form.shareMessage} onChange={e=>set('shareMessage',e.target.value)}/><small>Incluye {'{url}'} para el enlace; {'{code}'} se reemplaza por el código personal.</small></label></div></section><p>Saldo promocional: se acredita separado del dinero real; su gasto en viajes todavía no está habilitado.</p><div className="campaign-toolbar"><button type="button" className="secondary" disabled={busy} onClick={()=>setForm(null)}>Cancelar</button><button disabled={busy}>Guardar programa</button></div></form></ConsoleModal>}
 </section>;
}
