import { useEffect, useMemo, useState } from "react";
import { apiFetch, apiUrl } from "./api.js";
import "./support-admin.css";

const statusLabels: Record<string,string> = { NUEVO:"Nuevo",ASIGNADO:"Asignado",EN_REVISION:"En revisión",ESPERANDO_USUARIO:"Esperando usuario",RESUELTO:"Resuelto",CERRADO:"Cerrado" };
const categoryLabels: Record<string,string> = { CONTACT:"Contacto",TRIP:"Problema con viaje",LOST_ITEM:"Objeto olvidado",PAYMENT:"Pago",SAFETY:"Seguridad",APP:"Aplicación",OTHER:"Otro" };
const statuses=Object.keys(statusLabels);
type FaqDraft={id?:string;category:string;question:string;answer:string;audiences:string[];sortOrder:number;active:boolean};
const emptyFaq:FaqDraft={category:"Viajes",question:"",answer:"",audiences:["PASSENGER","DRIVER"],sortOrder:100,active:true};

export function SupportAdmin({token}:{token:string}){
  const [items,setItems]=useState<any[]>([]);const [faqs,setFaqs]=useState<any[]>([]);const [selected,setSelected]=useState<any>();
  const [query,setQuery]=useState("");const [status,setStatus]=useState("");const [priority,setPriority]=useState("");const [error,setError]=useState("");const [success,setSuccess]=useState("");const [busy,setBusy]=useState(false);
  const [update,setUpdate]=useState({status:"NUEVO",assignToSelf:false,response:"",internalNote:"",resolutionNote:""});
  const [faq,setFaq]=useState<FaqDraft>(emptyFaq);
  async function load(){try{setError("");const [cases,nextFaqs]=await Promise.all([apiFetch<any[]>("/v1/admin/incidents",token),apiFetch<any[]>("/v1/admin/faqs",token)]);setItems(cases);setFaqs(nextFaqs);}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo cargar soporte.");}}
  useEffect(()=>{void load();},[token]);
  const visible=useMemo(()=>items.filter(item=>(!status||item.status===status)&&(!priority||item.priority===priority)&&(!query||`${item.subject} ${item.reporter} ${item.category}`.toLowerCase().includes(query.toLowerCase()))),[items,status,priority,query]);
  async function open(item:any){try{setError("");const detail=await apiFetch<any>(`/v1/admin/incidents/${item.id}`,token);setSelected(detail);setUpdate({status:detail.status,assignToSelf:false,response:"",internalNote:"",resolutionNote:detail.resolutionNote??""});}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo abrir el caso.");}}
  async function saveCase(){if(!selected)return;setBusy(true);setError("");setSuccess("");try{await apiFetch(`/v1/admin/incidents/${selected.id}`,token,{method:"PATCH",body:JSON.stringify(update)});setSuccess("Caso actualizado correctamente.");await load();await open(selected);}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo guardar.");}finally{setBusy(false);}}
  async function openAttachment(file:any){try{const response=await fetch(apiUrl(`/v1/admin/incidents/${selected.id}/attachments/${file.id}`),{headers:{authorization:`Bearer ${token}`}});if(!response.ok)throw new Error("No se pudo abrir el archivo.");const url=URL.createObjectURL(await response.blob());window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60_000);}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo abrir el archivo.");}}
  function editFaq(item:any){setFaq({...item,audiences:Array.from(item.audiences??[])});document.getElementById("faq-editor")?.scrollIntoView({behavior:"smooth"});}
  async function saveFaq(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{const path=faq.id?`/v1/admin/faqs/${faq.id}`:"/v1/admin/faqs";await apiFetch(path,token,{method:faq.id?"PATCH":"POST",body:JSON.stringify(faq)});setFaq(emptyFaq);setSuccess("Pregunta frecuente guardada.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo guardar la pregunta.");}finally{setBusy(false);}}
  return <div className="support-admin">
    <section className="support-summary"><article><strong>{items.filter(i=>!["RESUELTO","CERRADO"].includes(i.status)).length}</strong><span>Casos abiertos</span></article><article><strong>{items.filter(i=>i.priority==="CRITICA"&&!['RESUELTO','CERRADO'].includes(i.status)).length}</strong><span>Prioridad crítica</span></article><article><strong>{items.filter(i=>i.status==="ESPERANDO_USUARIO").length}</strong><span>Esperando usuario</span></article><article><strong>{faqs.filter(i=>i.active).length}</strong><span>Preguntas activas</span></article></section>
    {error&&<div className="alert error">{error}</div>}{success&&<div className="alert success">{success}</div>}
    <section className="card support-workspace"><div className="support-list"><div className="support-heading"><div><span>SOLICITUDES REALES</span><h2>Soporte e incidentes</h2></div><button className="secondary" onClick={()=>void load()}>Actualizar</button></div><div className="support-filters"><input placeholder="Buscar persona, asunto o categoría" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option>{statuses.map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Todas las prioridades</option>{["BAJA","MEDIA","ALTA","CRITICA"].map(value=><option key={value}>{value}</option>)}</select></div><div className="case-list">{visible.length?visible.map(item=><button key={item.id} className={selected?.id===item.id?"selected":""} onClick={()=>void open(item)}><div><strong>{item.subject}</strong><small>{item.reporter} · {categoryLabels[item.category]??item.category}</small></div><span className={`case-priority ${item.priority?.toLowerCase()}`}>{item.priority}</span><small>{statusLabels[item.status]??item.status}</small></button>):<p className="support-empty">No hay casos para estos filtros.</p>}</div></div>
      <div className="case-detail">{!selected?<div className="support-empty detail-empty"><span>◎</span><strong>Selecciona un caso</strong><p>Aquí aparecerán el viaje, usuario, mensajes, adjuntos y acciones.</p></div>:<><div className="case-detail-head"><div><span>{categoryLabels[selected.category]??selected.category} · {selected.priority}</span><h2>{selected.subject}</h2><p>{selected.reporter} ({selected.reporterRole}) · {selected.reporterEmail} · {selected.reporterPhone}</p></div><span className="badge">{statusLabels[selected.status]??selected.status}</span></div>{selected.tripId&&<div className="trip-context"><strong>Viaje relacionado</strong><span>{selected.originReference??"Origen"} → {selected.destinationReference??"Destino"}</span><small>{selected.tripDate?new Date(selected.tripDate).toLocaleString():selected.tripId} · {selected.cooperative??"Sin cooperativa"}</small></div>}<div className="case-timeline">{selected.messages?.map((message:any)=><article className={message.visibility==="INTERNAL"?"internal":""} key={message.id}><div><strong>{message.author}</strong><span>{message.visibility==="INTERNAL"?"Nota interna":"Visible al usuario"}</span></div><p>{message.body}</p><small>{new Date(message.createdAt).toLocaleString()}</small></article>)}</div>{selected.attachments?.length>0&&<div className="attachment-row">{selected.attachments.map((file:any)=><button className="secondary" key={file.id} onClick={()=>void openAttachment(file)}>Abrir {file.fileName}</button>)}</div>}<div className="case-editor"><label>Estado<select value={update.status} onChange={e=>setUpdate({...update,status:e.target.value})}>{statuses.map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select></label><label className="check"><input type="checkbox" checked={update.assignToSelf} onChange={e=>setUpdate({...update,assignToSelf:e.target.checked})}/>Asignarme este caso</label><label>Respuesta visible<textarea rows={3} value={update.response} onChange={e=>setUpdate({...update,response:e.target.value})} placeholder="Respuesta que recibirá el usuario"/></label><label>Nota interna<textarea rows={2} value={update.internalNote} onChange={e=>setUpdate({...update,internalNote:e.target.value})} placeholder="Solo la verá el equipo"/></label>{["RESUELTO","CERRADO"].includes(update.status)&&<label>Resolución<textarea rows={2} value={update.resolutionNote} onChange={e=>setUpdate({...update,resolutionNote:e.target.value})}/></label>}<button className="primary" disabled={busy} onClick={()=>void saveCase()}>{busy?"Guardando…":"Guardar actualización"}</button></div></>}</div>
    </section>
    <section className="card faq-admin"><div className="support-heading"><div><span>BASE DE CONOCIMIENTO</span><h2>Preguntas frecuentes</h2></div><small>Se publican sin actualizar la APK</small></div><div className="faq-layout"><div className="faq-list">{faqs.map(item=><button key={item.id} onClick={()=>editFaq(item)}><strong>{item.question}</strong><small>{item.category} · {item.active?"Activa":"Inactiva"} · {item.audiences.join(" / ")}</small></button>)}</div><form id="faq-editor" onSubmit={saveFaq}><label>Categoría<input required value={faq.category} onChange={e=>setFaq({...faq,category:e.target.value})}/></label><label>Pregunta<input required minLength={5} value={faq.question} onChange={e=>setFaq({...faq,question:e.target.value})}/></label><label>Respuesta<textarea required minLength={10} rows={5} value={faq.answer} onChange={e=>setFaq({...faq,answer:e.target.value})}/></label><div className="faq-inline"><label>Orden<input type="number" min="0" value={faq.sortOrder} onChange={e=>setFaq({...faq,sortOrder:Number(e.target.value)})}/></label><label className="check"><input type="checkbox" checked={faq.active} onChange={e=>setFaq({...faq,active:e.target.checked})}/>Activa</label></div><div className="faq-inline"><label className="check"><input type="checkbox" checked={faq.audiences.includes("PASSENGER")} onChange={e=>setFaq({...faq,audiences:e.target.checked?[...new Set([...faq.audiences,"PASSENGER"])]:faq.audiences.filter(v=>v!=="PASSENGER")})}/>Pasajeros</label><label className="check"><input type="checkbox" checked={faq.audiences.includes("DRIVER")} onChange={e=>setFaq({...faq,audiences:e.target.checked?[...new Set([...faq.audiences,"DRIVER"])]:faq.audiences.filter(v=>v!=="DRIVER")})}/>Conductores</label></div><div className="faq-actions"><button type="button" className="secondary" onClick={()=>setFaq(emptyFaq)}>Nueva</button><button className="primary" disabled={busy||faq.audiences.length===0}>{faq.id?"Actualizar":"Crear pregunta"}</button></div></form></div></section>
  </div>;
}
