// Generated by scripts/generate-mototaxi-icon.mjs; edit packages/brand/mototaxi-icon.json.
import 'package:flutter/material.dart';
class MototaxiIcon extends StatelessWidget {
  const MototaxiIcon({super.key,this.size,this.color,this.semanticLabel});
  final double? size; final Color? color; final String? semanticLabel;
  @override Widget build(BuildContext context) {
    final theme=IconTheme.of(context); final dimension=size??theme.size??24;
    return Semantics(label:semanticLabel,excludeSemantics:true,child:SizedBox.square(dimension:dimension,
      child:CustomPaint(painter:_MototaxiPainter(color??theme.color??Theme.of(context).colorScheme.primary))));
  }
}
class _MototaxiPainter extends CustomPainter {
  const _MototaxiPainter(this.color); final Color color;
  @override void paint(Canvas canvas,Size size) {
    canvas.scale(size.width/32,size.height/32);
    final paint=Paint()..color=color..style=PaintingStyle.stroke..strokeWidth=1.9..strokeCap=StrokeCap.round..strokeJoin=StrokeJoin.round;
    canvas.drawPath(Path()..moveTo(3,9)..quadraticBezierTo(4,5,9,5)..lineTo(18,5)..quadraticBezierTo(20,5,21,8)..lineTo(22,9)..close(), paint);
canvas.drawPath(Path()..moveTo(4,10)..lineTo(4,23)..lineTo(5,23)..moveTo(4,17)..lineTo(12,17)..moveTo(12,10)..lineTo(12,20)..lineTo(15,24)..lineTo(20,24)..lineTo(23,17)..lineTo(27,17)..lineTo(26,21)..moveTo(20,11)..lineTo(22,16)..moveTo(27,17)..lineTo(25,11), paint);
canvas.drawPath(Path()..moveTo(15,24)..lineTo(11,24)..moveTo(24,20)..lineTo(26,24)..moveTo(2,23)..lineTo(5,23), paint);
    canvas.drawCircle(const Offset(8,25),3.5,paint);
canvas.drawCircle(const Offset(26,25),3.5,paint);
  }
  @override bool shouldRepaint(_MototaxiPainter old)=>old.color!=color;
}
