import type {FastifyInstance} from 'fastify';
import {createHash} from 'node:crypto';
import {z} from 'zod';
import {database} from './database.js';
import {notificationService,type NotificationCommand} from './notification-service.js';
import {requirePermission} from './admin.js';
import {notificationPreferenceAllows,updateSmartSaturation} from './notification-preferences.js';
import {notificationSystemHealth,notificationUserDiagnostic} from './notification-reliability.js';

const modes=['OFF','TEST','ON'] as const;
const patternTypes=['FREQUENT_TRIP','RETURN_HOME','FAVORITE_DESTINATION','REACTIVATION'] as const;
const campaignTypes=['CAMPAIGN','EVENT','PROMOTIONAL','APP_UPDATE'] as const;
const appUpdateAudienceModes=['TESTERS','OUTDATED','MANUAL'] as const;
const configSchema=z.object({
  mode:z.enum(modes),frequentTripEnabled:z.boolean(),returnTripEnabled:z.boolean(),favoriteDestinationEnabled:z.boolean(),reactivationEnabled:z.boolean(),
  minimumTrips:z.number().int().min(2).max(100),minimumMatches:z.number().int().min(2).max(100),minimumConfidence:z.number().min(0).max(100),
  analysisWindowDays:z.number().int().min(7).max(365),scheduleToleranceMinutes:z.number().int().min(5).max(180),notificationLeadMinutes:z.number().int().min(1).max(180),
  maxPerUserPerDay:z.number().int().min(0).max(20),minimumIntervalMinutes:z.number().int().min(1).max(10080),
  maxPerUserPerWeek:z.number().int().min(0).max(50),ignoredToReduceFrequency:z.number().int().min(1).max(20),ignoredToPause:z.number().int().min(2).max(50),autoPauseDays:z.number().int().min(1).max(90),reducedFrequencyMultiplier:z.number().int().min(1).max(10),
  allowedStartTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),allowedEndTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),
  enabledWeekDays:z.array(z.number().int().min(1).max(7)).min(1).max(7),inactiveUserDays:z.number().int().min(7).max(365),schedulerIntervalMinutes:z.number().int().min(1).max(1440)
}).refine(v=>v.allowedStartTime<v.allowedEndTime,{message:'INVALID_ALLOWED_TIME'});
const segmentSchema=z.object({zones:z.array(z.string().min(1).max(100)).max(50).default([]),roles:z.array(z.enum(['PASSENGER','DRIVER'])).max(2).default([]),platforms:z.array(z.enum(['ANDROID','IOS'])).max(2).default([]),activeWithinDays:z.number().int().min(1).max(365).optional(),userIds:z.array(z.string().uuid()).max(500).default([]),userEmails:z.array(z.string().trim().email().transform(value=>value.toLowerCase())).max(500).default([])});
const appUpdateMetadataSchema=z.object({publishedVersion:z.string().trim().regex(/^\d+(?:\.\d+){1,3}(?:[-+][0-9A-Za-z.-]+)?$/).max(50),publishedBuild:z.number().int().min(1),targetPlatform:z.enum(['ANDROID','IOS']),audienceMode:z.enum(appUpdateAudienceModes),storeUrl:z.string().url().max(500),updateAction:z.enum(['OPEN_STORE','UPDATE_NOW']).default('OPEN_STORE')});
const reminderConfigSchema=z.object({passengerScheduledReminderMinutes:z.array(z.number().int().min(1).max(1440)).max(10),passengerScheduledMaxReminders:z.number().int().min(0).max(10),allowedStartTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),allowedEndTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),driverMembershipReminderDays:z.array(z.number().int().min(1).max(90)).max(10),driverMembershipMaxReminders:z.number().int().min(0).max(10),driverDocumentReminderDays:z.array(z.number().int().min(1).max(365)).max(10)}).refine(value=>value.allowedStartTime<value.allowedEndTime,{message:'INVALID_ALLOWED_TIME'});
const campaignSchema=z.object({name:z.string().trim().min(3).max(120),campaignType:z.enum(campaignTypes),title:z.string().trim().min(1).max(120),body:z.string().trim().min(1).max(500),deepLink:z.string().trim().max(500).optional().or(z.literal('')),action:z.string().trim().max(80).optional().or(z.literal('')),metadata:z.record(z.string(),z.unknown()).default({}),segment:segmentSchema.default({zones:[],roles:[],platforms:[],userIds:[],userEmails:[]})}).superRefine((value,context)=>{if(value.campaignType!=='APP_UPDATE')return;const parsed=appUpdateMetadataSchema.safeParse(value.metadata);if(!parsed.success)for(const issue of parsed.error.issues)context.addIssue({...issue,path:['metadata',...issue.path]});if(parsed.success&&value.deepLink!==parsed.data.storeUrl)context.addIssue({code:'custom',path:['deepLink'],message:'APP_UPDATE_STORE_URL_MISMATCH'});if(parsed.success&&value.action!==parsed.data.updateAction)context.addIssue({code:'custom',path:['action'],message:'APP_UPDATE_ACTION_MISMATCH'});if(parsed.success&&value.segment.platforms.length>0&&!value.segment.platforms.includes(parsed.data.targetPlatform))context.addIssue({code:'custom',path:['segment','platforms'],message:'APP_UPDATE_PLATFORM_MISMATCH'});if(parsed.success&&parsed.data.audienceMode==='MANUAL'&&value.segment.userIds.length+value.segment.userEmails.length===0)context.addIssue({code:'custom',path:['segment','userEmails'],message:'APP_UPDATE_MANUAL_AUDIENCE_REQUIRED'});});
function storedJson(value:unknown){if(typeof value!=='string')return value;try{return JSON.parse(value);}catch{return value;}}
const testSendSchema=z.object({userId:z.string().uuid(),type:z.string().trim().min(2).max(80).default('TEST_PUSH'),title:z.string().trim().min(1).max(120),message:z.string().trim().min(1).max(500),action:z.string().trim().max(80).optional(),deepLink:z.string().trim().max(500).optional(),destination:z.object({reference:z.string().trim().min(1).max(200),latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180)}).optional()});

type Config=z.infer<typeof configSchema> & {lastSchedulerRunAt?:string;updatedAt?:string};
type PatternType=typeof patternTypes[number];
export function smartModeReasons(mode:'OFF'|'TEST'|'ON',tester:boolean):string[]{
  if(mode==='OFF')return ['SMART_MODE_OFF'];
  if(mode==='TEST'&&!tester)return ['TEST_USER_NOT_ALLOWED'];
  return [];
}
function number(value:unknown){return Number(value??0);}
function time(value:unknown){return String(value??'').slice(0,5);}
function configFrom(row:any):Config{return {mode:row.mode,frequentTripEnabled:Boolean(row.frequentTripEnabled),returnTripEnabled:Boolean(row.returnTripEnabled),favoriteDestinationEnabled:Boolean(row.favoriteDestinationEnabled),reactivationEnabled:Boolean(row.reactivationEnabled),minimumTrips:number(row.minimumTrips),minimumMatches:number(row.minimumMatches),minimumConfidence:number(row.minimumConfidence),analysisWindowDays:number(row.analysisWindowDays),scheduleToleranceMinutes:number(row.scheduleToleranceMinutes),notificationLeadMinutes:number(row.notificationLeadMinutes),maxPerUserPerDay:number(row.maxPerUserPerDay),maxPerUserPerWeek:number(row.maxPerUserPerWeek),ignoredToReduceFrequency:number(row.ignoredToReduceFrequency),ignoredToPause:number(row.ignoredToPause),autoPauseDays:number(row.autoPauseDays),reducedFrequencyMultiplier:number(row.reducedFrequencyMultiplier),minimumIntervalMinutes:number(row.minimumIntervalMinutes),allowedStartTime:time(row.allowedStartTime),allowedEndTime:time(row.allowedEndTime),enabledWeekDays:(row.enabledWeekDays??[]).map(Number),inactiveUserDays:number(row.inactiveUserDays),schedulerIntervalMinutes:number(row.schedulerIntervalMinutes),lastSchedulerRunAt:row.lastSchedulerRunAt?new Date(row.lastSchedulerRunAt).toISOString():undefined,updatedAt:row.updatedAt?new Date(row.updatedAt).toISOString():undefined};}
async function smartConfig():Promise<Config>{
  const [row]=await database()`select mode,frequent_trip_enabled as "frequentTripEnabled",return_trip_enabled as "returnTripEnabled",favorite_destination_enabled as "favoriteDestinationEnabled",reactivation_enabled as "reactivationEnabled",minimum_trips as "minimumTrips",minimum_matches as "minimumMatches",minimum_confidence::float8 as "minimumConfidence",analysis_window_days as "analysisWindowDays",schedule_tolerance_minutes as "scheduleToleranceMinutes",notification_lead_minutes as "notificationLeadMinutes",max_per_user_per_day as "maxPerUserPerDay",max_per_user_per_week as "maxPerUserPerWeek",ignored_to_reduce_frequency as "ignoredToReduceFrequency",ignored_to_pause as "ignoredToPause",auto_pause_days as "autoPauseDays",reduced_frequency_multiplier as "reducedFrequencyMultiplier",minimum_interval_minutes as "minimumIntervalMinutes",allowed_start_time::text as "allowedStartTime",allowed_end_time::text as "allowedEndTime",enabled_week_days as "enabledWeekDays",inactive_user_days as "inactiveUserDays",scheduler_interval_minutes as "schedulerIntervalMinutes",last_scheduler_run_at as "lastSchedulerRunAt",updated_at as "updatedAt" from smart_notification_config where id=1`;
  return configFrom(row);
}
function normalized(value:unknown){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();}
export function compareAppVersions(left:unknown,right:unknown):number{const parts=(value:unknown)=>(String(value??'').split(/[+-]/,1).at(0)??'').split('.').map(item=>Number.parseInt(item,10)||0);const a=parts(left),b=parts(right);for(let index=0;index<Math.max(a.length,b.length);index++){const difference=(a[index]??0)-(b[index]??0);if(difference)return difference>0?1:-1;}return 0;}
function appUpdateDisposition(row:any,target:z.infer<typeof appUpdateMetadataSchema>){if(row.appBuild!=null)return number(row.appBuild)>=target.publishedBuild?'UPDATED':'OUTDATED';if(row.appVersion)return compareAppVersions(row.appVersion,target.publishedVersion)>=0?'UPDATED':'OUTDATED';return 'UNKNOWN';}
function patternKey(type:PatternType,userId:string,origin:string,destination:string){return createHash('sha256').update(`${type}|${userId}|${normalized(origin)}|${normalized(destination)}`).digest('hex');}
function ecuParts(date:Date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Guayaquil',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);const get=(name:string)=>parts.find(p=>p.type===name)?.value??'';const week:{[key:string]:number}={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7};return {weekDay:week[get('weekday')]??1,minutes:Number(get('hour'))*60+Number(get('minute'))};}
function averageTime(values:number[]){const average=Math.round(values.reduce((sum,value)=>sum+value,0)/Math.max(values.length,1));return `${String(Math.floor(average/60)%24).padStart(2,'0')}:${String(average%60).padStart(2,'0')}`;}

export async function analyzeSmartPatterns(userId?:string):Promise<{usersAnalyzed:number;patternsDetected:number}>{
  const config=await smartConfig();
  const rows=await database()`select t.id::text,t.passenger_id::text as "userId",t.origin_reference as "originReference",t.destination_reference as "destinationReference",t.requested_at as "requestedAt",t.completed_at as "completedAt",ST_Y(t.origin::geometry)::float8 as "originLat",ST_X(t.origin::geometry)::float8 as "originLng",ST_Y(t.destination::geometry)::float8 as "destinationLat",ST_X(t.destination::geometry)::float8 as "destinationLng",favorite.id::text as "favoriteId",favorite.label as "favoriteLabel"
    from trips t join users u on u.id=t.passenger_id
    left join lateral(select f.id,f.label from favorite_places f where f.user_id=t.passenger_id and t.destination is not null and ST_DWithin(f.location,t.destination,150) order by ST_Distance(f.location,t.destination) limit 1) favorite on true
    where t.status='COMPLETED' and t.completed_at>=now()-(${config.analysisWindowDays}*interval '1 day') and t.origin is not null and t.destination is not null and u.status='ACTIVE' and u.deleted_at is null
      and (${userId??null}::uuid is null or t.passenger_id=${userId??null}::uuid)
      and exists(select 1 from device_tokens d where d.user_id=u.id and d.enabled and d.invalidated_at is null and d.last_seen_at>now()-interval '90 days')
    order by t.passenger_id,t.completed_at desc limit 10000`;
  const byUser=new Map<string,any[]>();for(const row of rows){const list=byUser.get(String(row.userId))??[];list.push(row);byUser.set(String(row.userId),list);}
  let detected=0;
  for(const [candidateId,trips] of byUser){
    await database()`update smart_notification_patterns set is_active=false,last_evaluated_at=now(),updated_at=now() where user_id=${candidateId}`;
    const groups=new Map<string,any[]>();for(const trip of trips){const key=`${normalized(trip.originReference)}|${normalized(trip.destinationReference)}`;const list=groups.get(key)??[];list.push(trip);groups.set(key,list);}
    for(const group of groups.values()){
      if(group.length<config.minimumMatches)continue;
      const origin=String(group[0].originReference??'Origen habitual'),destination=String(group[0].destinationReference??'Destino habitual');
      const times=group.map(item=>ecuParts(new Date(item.requestedAt)).minutes),weekDays=[...new Set(group.map(item=>ecuParts(new Date(item.requestedAt)).weekDay))].sort();
      const confidence=Math.min(100,Math.round(group.length/Math.max(trips.length,config.minimumTrips)*10000)/100);
      const variants:Array<{type:PatternType;favoriteId?:string}>=[{type:'FREQUENT_TRIP'}];
      if(group[0].favoriteId)variants.push({type:'FAVORITE_DESTINATION',favoriteId:String(group[0].favoriteId)});
      if(/casa|hogar|home/.test(normalized(group[0].favoriteLabel??destination)))variants.push({type:'RETURN_HOME',favoriteId:group[0].favoriteId?String(group[0].favoriteId):undefined});
      for(const variant of variants){
        const key=patternKey(variant.type,candidateId,origin,destination);
        await database()`insert into smart_notification_patterns(user_id,pattern_key,pattern_type,origin_reference,destination_reference,origin_lat,origin_lng,destination_lat,destination_lng,favorite_destination_id,week_days,average_time,time_tolerance_minutes,matches_count,trips_analyzed,confidence_score,is_active)
          values (${candidateId},${key},${variant.type},${origin},${destination},${number(group[0].originLat)},${number(group[0].originLng)},${number(group[0].destinationLat)},${number(group[0].destinationLng)},${variant.favoriteId??null},${weekDays},${averageTime(times)}::time,${config.scheduleToleranceMinutes},${group.length},${trips.length},${confidence},true)
          on conflict(user_id,pattern_key) do update set week_days=excluded.week_days,average_time=excluded.average_time,time_tolerance_minutes=excluded.time_tolerance_minutes,matches_count=excluded.matches_count,trips_analyzed=excluded.trips_analyzed,confidence_score=excluded.confidence_score,last_detected_at=now(),last_evaluated_at=now(),is_active=true,updated_at=now()`;
        detected++;
      }
    }
  }
  if(config.reactivationEnabled){
    const inactive=await database()`select u.id::text as "userId",max(t.completed_at) as "lastTripAt",count(t.id)::int as trips from users u join trips t on t.passenger_id=u.id and t.status='COMPLETED' where u.status='ACTIVE' and u.deleted_at is null and (${userId??null}::uuid is null or u.id=${userId??null}::uuid) group by u.id having max(t.completed_at)<now()-(${config.inactiveUserDays}*interval '1 day') limit 1000`;
    for(const row of inactive){const key=patternKey('REACTIVATION',String(row.userId),'','');await database()`insert into smart_notification_patterns(user_id,pattern_key,pattern_type,matches_count,trips_analyzed,confidence_score,last_detected_at,is_active) values (${row.userId},${key},'REACTIVATION',${number(row.trips)},${number(row.trips)},100,${row.lastTripAt},true) on conflict(user_id,pattern_key) do update set matches_count=excluded.matches_count,trips_analyzed=excluded.trips_analyzed,confidence_score=100,last_evaluated_at=now(),is_active=true,updated_at=now()`;detected++;}
  }
  return {usersAnalyzed:byUser.size,patternsDetected:detected};
}

async function eligibility(patternId:string,providedConfig?:Config,mutateSaturation=false):Promise<any>{
  const config=providedConfig??await smartConfig();
  const [row]=await database()`select p.id::text,p.user_id::text as "userId",p.pattern_type as type,p.origin_reference as origin,p.destination_reference as destination,p.destination_lat as "destinationLat",p.destination_lng as "destinationLng",p.week_days as "weekDays",p.average_time::text as "averageTime",p.matches_count as matches,p.trips_analyzed as "tripsAnalyzed",p.confidence_score::float8 as confidence,u.full_name as user,
    exists(select 1 from notification_test_users x where x.user_id=p.user_id and x.enabled) as tester,
    exists(select 1 from device_tokens d where d.user_id=p.user_id and d.invalidated_at is null) as "hasToken",
    exists(select 1 from device_tokens d where d.user_id=p.user_id and d.enabled and d.invalidated_at is null and d.last_seen_at>now()-interval '90 days') as "validToken",
    exists(select 1 from trips active where (active.passenger_id=p.user_id or active.driver_id=p.user_id) and active.status in ('SEARCHING','ASSIGNED','DRIVER_EN_ROUTE','DRIVER_ARRIVED','IN_PROGRESS')) as "activeTrip",
    (select count(*)::int from user_notifications n where n.user_id=p.user_id and n.category='SMART' and n.created_at>=date_trunc('day',now() at time zone 'America/Guayaquil') at time zone 'America/Guayaquil') as "sentToday",
    (select count(*)::int from user_notifications n where n.user_id=p.user_id and n.category='SMART' and n.created_at>=now()-interval '7 days') as "sentThisWeek",
    (select max(created_at) from user_notifications n where n.user_id=p.user_id and n.category='SMART' and n.status='SENT') as "lastSmartAt",
    exists(select 1 from trips recent where recent.passenger_id=p.user_id and recent.requested_at>now()-(${config.minimumIntervalMinutes}*interval '1 minute') and recent.status not in ('CANCELLED','NO_DRIVER') and recent.destination is not null and p.destination_lat is not null and ST_DWithin(recent.destination,ST_SetSRID(ST_MakePoint(p.destination_lng,p.destination_lat),4326)::geography,150)) as "recentEquivalentTrip"
    from smart_notification_patterns p join users u on u.id=p.user_id where p.id=${patternId} and p.is_active`;
  if(!row)return {eligible:false,score:0,reasons:['PATTERN_NOT_FOUND']};
  const reasons:string[]=[];const parts=ecuParts(new Date());
  const saturation=mutateSaturation?await updateSmartSaturation(String(row.userId),config):await (async()=>{const [preference]=await database()`select state,ignored_streak as ignored from user_notification_preferences where user_id=${row.userId} and context='PASSENGER' and preference_key='PASSENGER_SMART_RECOMMENDATIONS'`;return {state:String(preference?.state??'ENABLED'),reduced:number(preference?.ignored)>=config.ignoredToReduceFrequency};})();
  if(saturation.state==='USER_DISABLED')reasons.push('USER_DISABLED');
  if(saturation.state==='AUTO_PAUSED')reasons.push('AUTO_PAUSED');
  reasons.push(...smartModeReasons(config.mode,Boolean(row.tester)));
  const enabled=row.type==='FREQUENT_TRIP'?config.frequentTripEnabled:row.type==='RETURN_HOME'?config.returnTripEnabled:row.type==='FAVORITE_DESTINATION'?config.favoriteDestinationEnabled:config.reactivationEnabled;
  if(!enabled)reasons.push('PATTERN_TYPE_DISABLED');
  if(number(row.tripsAnalyzed)<config.minimumTrips)reasons.push('INSUFFICIENT_TRIPS');
  if(number(row.matches)<config.minimumMatches)reasons.push('INSUFFICIENT_MATCHES');
  if(number(row.confidence)<config.minimumConfidence)reasons.push('CONFIDENCE_TOO_LOW');
  if(row.hasToken&&!row.validToken)reasons.push('NOTIFICATIONS_DISABLED');else if(!row.validToken)reasons.push('INVALID_FCM_TOKEN');
  if(row.activeTrip)reasons.push('ACTIVE_TRIP_EXISTS');
  if(row.recentEquivalentTrip)reasons.push('RECENT_EQUIVALENT_TRIP');
  if(!config.enabledWeekDays.includes(parts.weekDay))reasons.push('WEEKDAY_DISABLED');
  const nowTime=`${String(Math.floor(parts.minutes/60)).padStart(2,'0')}:${String(parts.minutes%60).padStart(2,'0')}`;if(nowTime<config.allowedStartTime||nowTime>config.allowedEndTime)reasons.push('OUTSIDE_ALLOWED_TIME');
  if(number(row.sentToday)>=config.maxPerUserPerDay)reasons.push('DAILY_LIMIT_REACHED');
  if(number(row.sentThisWeek)>=config.maxPerUserPerWeek)reasons.push('WEEKLY_LIMIT_REACHED');
  const effectiveInterval=config.minimumIntervalMinutes*(saturation.reduced?config.reducedFrequencyMultiplier:1);
  if(row.lastSmartAt&&Date.now()-new Date(row.lastSmartAt).getTime()<effectiveInterval*60000)reasons.push(saturation.reduced?'REDUCED_FREQUENCY_INTERVAL':'MINIMUM_INTERVAL_NOT_REACHED');
  const averageMinutes=String(row.averageTime??'').split(':').slice(0,2).reduce((v,p,i)=>v+Number(p)*(i?1:60),0);const targetMinutes=averageMinutes-config.notificationLeadMinutes;
  if(row.type!=='REACTIVATION'&&Math.abs(parts.minutes-targetMinutes)>config.scheduleToleranceMinutes)reasons.push('OUTSIDE_PATTERN_WINDOW');
  return {...row,eligible:reasons.length===0,score:number(row.confidence),reasons:reasons.length?reasons:['ELIGIBLE'],suggestedSendAt:row.averageTime};
}

function smartCommand(item:any,date=new Date()):NotificationCommand{
  const title=item.type==='RETURN_HOME'?'¿Listo para regresar a casa? 🛺':item.type==='REACTIVATION'?'Costa-Go está listo cuando tú lo estés':`¿Listo para ir a ${item.destination??'tu destino habitual'}? 🛺`;
  const body=item.type==='REACTIVATION'?'Vuelve a moverte por la costa cuando lo necesites.':`Tu destino habitual está preparado. Revísalo antes de solicitar.`;
  const day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Guayaquil'}).format(date);
  const preparesTrip=item.type!=='REACTIVATION'&&item.destinationLat!=null&&item.destinationLng!=null;
  return {userId:String(item.userId),type:`SMART_${item.type}`,category:'SMART',priority:'SMART',title,body,referenceId:String(item.id),deepLink:preparesTrip?'costa-go://trip/prepare':'costa-go://notifications',action:preparesTrip?'PREPARE_TRIP':'OPEN_NOTIFICATIONS',metadata:{patternId:item.id,...(preparesTrip?{originReference:item.origin??'',destinationReference:item.destination??'',destinationLatitude:item.destinationLat,destinationLongitude:item.destinationLng}:{})},persistInCenter:true,sendPush:true,idempotencyKey:`SMART:${item.type}:${item.userId}:${item.id}:${day}:${item.averageTime??'reactivation'}`};
}

function scheduleLimitReasons(date:Date,config:Config):string[]{
  const parts=ecuParts(date),nowTime=`${String(Math.floor(parts.minutes/60)).padStart(2,'0')}:${String(parts.minutes%60).padStart(2,'0')}`;
  const reasons:string[]=[];
  if(!config.enabledWeekDays.includes(parts.weekDay))reasons.push('WEEKDAY_DISABLED');
  if(nowTime<config.allowedStartTime||nowTime>config.allowedEndTime)reasons.push('OUTSIDE_ALLOWED_TIME');
  return reasons;
}

async function candidatesForSegment(segment:z.infer<typeof segmentSchema>){
  return database()`select distinct u.id::text,u.full_name as name,u.email,u.role::text as role,d.platform,d.last_seen_at as "lastSeenAt",d.app_version as "appVersion",d.app_build as "appBuild",area.name as zone,
    exists(select 1 from notification_test_users x where x.user_id=u.id and x.enabled) as tester
    from users u join device_tokens d on d.user_id=u.id and d.enabled and d.invalidated_at is null and d.last_seen_at>now()-interval '90 days'
    left join lateral(select t.service_area_id,t.requested_at from trips t where t.passenger_id=u.id or t.driver_id=u.id order by t.requested_at desc limit 1) recent on true left join service_areas area on area.id=recent.service_area_id
    where u.status='ACTIVE' and u.deleted_at is null
      and (${segment.userIds.length+segment.userEmails.length}=0 or u.id=any(${segment.userIds}::uuid[]) or lower(u.email)=any(${segment.userEmails}::text[]))
      and (${segment.platforms.length}=0 or d.platform=any(${segment.platforms}::text[]))
      and (${segment.roles.length}=0 or u.role::text=any(${segment.roles}::text[]) or exists(select 1 from mobile_account_roles r where r.user_id=u.id and r.role=any(${segment.roles}::text[])))
      and (${segment.zones.length}=0 or area.name=any(${segment.zones}::text[]) or recent.service_area_id::text=any(${segment.zones}::text[]))
      and (${segment.activeWithinDays??null}::int is null or coalesce(recent.requested_at,u.updated_at,u.created_at)>=now()-(coalesce(${segment.activeWithinDays??null},365)*interval '1 day')) order by u.full_name limit 10000`;
}

async function candidatesForCampaign(campaign:any,segment:z.infer<typeof segmentSchema>){
  const rows=await candidatesForSegment(segment);
  if(campaign.campaignType==='PROMOTIONAL'){
    const allowed=[] as any[];
    for(const row of rows)if(await notificationPreferenceAllows(String(row.id),'PROMOTIONAL_NOTIFICATIONS'))allowed.push(row);
    return allowed;
  }
  if(campaign.campaignType!=='APP_UPDATE')return rows;
  const target=appUpdateMetadataSchema.parse(storedJson(campaign.metadata??{}));
  return rows.filter((row:any)=>row.platform===target.targetPlatform)
    .filter((row:any)=>target.audienceMode!=='TESTERS'||row.tester)
    .filter((row:any)=>target.audienceMode!=='OUTDATED'||appUpdateDisposition(row,target)==='OUTDATED');
}

async function estimateSegment(segment:z.infer<typeof segmentSchema>,promotional=false){
  const rows=await database()`select distinct u.id::text,u.full_name as name,u.email,d.platform,d.last_seen_at as "lastSeenAt",d.enabled,d.invalidated_at as "invalidatedAt",
    (d.token is not null and d.enabled and d.invalidated_at is null and d.last_seen_at>now()-interval '90 days') as "validToken"
    from users u
    left join lateral(select token,platform,last_seen_at,enabled,invalidated_at from device_tokens where user_id=u.id order by (enabled and invalidated_at is null and last_seen_at>now()-interval '90 days') desc,last_seen_at desc limit 1)d on true
    left join lateral(select t.service_area_id,t.requested_at from trips t where t.passenger_id=u.id or t.driver_id=u.id order by t.requested_at desc limit 1) recent on true
    left join service_areas area on area.id=recent.service_area_id
    where u.status='ACTIVE' and u.deleted_at is null
      and (${segment.userIds.length+segment.userEmails.length}=0 or u.id=any(${segment.userIds}::uuid[]) or lower(u.email)=any(${segment.userEmails}::text[]))
      and (${segment.platforms.length}=0 or d.platform=any(${segment.platforms}::text[]))
      and (${segment.roles.length}=0 or u.role::text=any(${segment.roles}::text[]) or exists(select 1 from mobile_account_roles r where r.user_id=u.id and r.role=any(${segment.roles}::text[])))
      and (${segment.zones.length}=0 or area.name=any(${segment.zones}::text[]) or recent.service_area_id::text=any(${segment.zones}::text[]))
      and (${segment.activeWithinDays??null}::int is null or coalesce(recent.requested_at,u.updated_at,u.created_at)>=now()-(coalesce(${segment.activeWithinDays??null},365)*interval '1 day'))
    order by u.id::text`;
  const preferences=promotional?new Map((await database()`select user_id::text as id,enabled,state from user_notification_preferences where context='COMMON' and preference_key='PROMOTIONAL_NOTIFICATIONS'`).map((row:any)=>[String(row.id),row])):new Map();
  const users=rows.map((row:any)=>{const preference:any=preferences.get(String(row.id));const preferenceAllowed=!preference||(preference.enabled&&preference.state==='ENABLED');return {...row,preferenceAllowed,reason:!preferenceAllowed?'PREFERENCE_DISABLED':row.validToken?'ELIGIBLE':!row.lastSeenAt?'NO_TOKEN':!row.enabled?'TOKEN_DISABLED':row.invalidatedAt?'TOKEN_INVALIDATED':'TOKEN_STALE'};});
  const valid=users.filter((row:any)=>row.validToken&&row.preferenceAllowed);
  return {usersFound:rows.length,total:valid.length,android:valid.filter((row:any)=>row.platform==='ANDROID').length,ios:valid.filter((row:any)=>row.platform==='IOS').length,withoutValidToken:users.filter((row:any)=>!row.validToken).length,preferenceDisabled:users.filter((row:any)=>!row.preferenceAllowed).length,excluded:rows.length-valid.length,users};
}

async function estimateAppUpdate(segment:z.infer<typeof segmentSchema>,rawMetadata:unknown){
  const target=appUpdateMetadataSchema.parse(storedJson(rawMetadata??{}));
  const rows=await database()`select distinct u.id::text,u.full_name as name,u.email,d.platform,d.last_seen_at as "lastSeenAt",d.enabled,d.invalidated_at as "invalidatedAt",d.app_version as "appVersion",d.app_build as "appBuild",
    exists(select 1 from notification_test_users x where x.user_id=u.id and x.enabled) as tester,
    (d.token is not null and d.enabled and d.invalidated_at is null and d.last_seen_at>now()-interval '90 days') as "validToken"
    from users u
    left join lateral(select token,platform,last_seen_at,enabled,invalidated_at,app_version,app_build from device_tokens where user_id=u.id order by (enabled and invalidated_at is null and last_seen_at>now()-interval '90 days') desc,last_seen_at desc limit 1)d on true
    left join lateral(select t.service_area_id,t.requested_at from trips t where t.passenger_id=u.id or t.driver_id=u.id order by t.requested_at desc limit 1) recent on true
    left join service_areas area on area.id=recent.service_area_id
    where u.status='ACTIVE' and u.deleted_at is null
      and (${target.audienceMode!=='TESTERS'} or exists(select 1 from notification_test_users x where x.user_id=u.id and x.enabled))
      and (${target.audienceMode!=='MANUAL'} or u.id=any(${segment.userIds}::uuid[]) or lower(u.email)=any(${segment.userEmails}::text[]))
      and (d.platform=${target.targetPlatform} or d.platform is null)
      and (${segment.roles.length}=0 or u.role::text=any(${segment.roles}::text[]) or exists(select 1 from mobile_account_roles r where r.user_id=u.id and r.role=any(${segment.roles}::text[])))
      and (${segment.zones.length}=0 or area.name=any(${segment.zones}::text[]) or recent.service_area_id::text=any(${segment.zones}::text[]))
      and (${segment.activeWithinDays??null}::int is null or coalesce(recent.requested_at,u.updated_at,u.created_at)>=now()-(coalesce(${segment.activeWithinDays??null},365)*interval '1 day'))
    order by u.id::text`;
  const users=rows.map((row:any)=>{const versionStatus=appUpdateDisposition(row,target);const versionEligible=target.audienceMode!=='OUTDATED'||versionStatus==='OUTDATED';const reason=!row.validToken?(!row.lastSeenAt?'NO_TOKEN':!row.enabled?'TOKEN_DISABLED':row.invalidatedAt?'TOKEN_INVALIDATED':'TOKEN_STALE'):target.audienceMode==='OUTDATED'&&versionStatus==='UNKNOWN'?'VERSION_UNKNOWN':!versionEligible?'ALREADY_UPDATED':'ELIGIBLE';return {...row,versionStatus,reason,eligible:Boolean(row.validToken&&versionEligible)};});
  const eligible=users.filter((row:any)=>row.eligible);
  return {testersFound:users.filter((row:any)=>row.tester).length,usersFound:users.length,alreadyUpdated:users.filter((row:any)=>row.versionStatus==='UPDATED').length,outdated:users.filter((row:any)=>row.versionStatus==='OUTDATED').length,withoutVersion:users.filter((row:any)=>row.versionStatus==='UNKNOWN').length,withoutValidToken:users.filter((row:any)=>!row.validToken).length,total:eligible.length,android:eligible.filter((row:any)=>row.platform==='ANDROID').length,ios:eligible.filter((row:any)=>row.platform==='IOS').length,excluded:users.length-eligible.length,users};
}

async function nonCriticalLimitReasons(userId:string,config:Config):Promise<string[]>{
  const parts=ecuParts(new Date());
  const nowTime=`${String(Math.floor(parts.minutes/60)).padStart(2,'0')}:${String(parts.minutes%60).padStart(2,'0')}`;
  const [usage]=await database()`select
    count(*) filter(where status='SENT' and created_at>=date_trunc('day',now() at time zone 'America/Guayaquil') at time zone 'America/Guayaquil')::int as today,
    max(created_at) filter(where status='SENT') as "lastSentAt"
    from user_notifications where user_id=${userId} and category in ('SMART','CAMPAIGN','PROMOTIONAL')`;
  const reasons:string[]=[];
  if(!config.enabledWeekDays.includes(parts.weekDay))reasons.push('WEEKDAY_DISABLED');
  if(nowTime<config.allowedStartTime||nowTime>config.allowedEndTime)reasons.push('OUTSIDE_ALLOWED_TIME');
  if(number(usage?.today)>=config.maxPerUserPerDay)reasons.push('DAILY_LIMIT_REACHED');
  if(usage?.lastSentAt&&Date.now()-new Date(usage.lastSentAt).getTime()<config.minimumIntervalMinutes*60000)reasons.push('MINIMUM_INTERVAL_NOT_REACHED');
  return reasons;
}

export async function smartNotificationSchedulerTick():Promise<void>{
  if(!process.env.DATABASE_URL)return;
  await processScheduledCampaigns();
  const due=await database().begin(async tx=>{const [row]=await tx`select scheduler_interval_minutes as minutes,last_scheduler_run_at as "lastRun",mode from smart_notification_config where id=1 for update`;if(row?.lastRun&&Date.now()-new Date(row.lastRun).getTime()<number(row.minutes)*60000)return false;await tx`update smart_notification_config set last_scheduler_run_at=now() where id=1`;return true;});
  if(!due)return;await analyzeSmartPatterns();const config=await smartConfig();if(config.mode==='OFF')return;
  const patterns=await database()`select id::text from smart_notification_patterns where is_active order by confidence_score desc,last_evaluated_at desc limit 500`;
  for(const pattern of patterns){const evaluated=await eligibility(String(pattern.id),config,true);if(evaluated.eligible)await notificationService.send(smartCommand(evaluated));}
}

async function processScheduledCampaigns(){
  const campaigns=await database().begin(async tx=>{const rows=await tx`select id::text from notification_campaigns where status='SCHEDULED' and scheduled_at<=now() order by scheduled_at limit 5 for update skip locked`;for(const row of rows)await tx`update notification_campaigns set status='PROCESSING',started_at=now(),updated_at=now() where id=${row.id}`;return rows;});
  const config=await smartConfig();
  for(const item of campaigns){
    try{
      const [campaign]=await database()`select *,campaign_type as "campaignType" from notification_campaigns where id=${item.id}`;
      if(!campaign)throw new Error('CAMPAIGN_NOT_FOUND');
      const segment=segmentSchema.parse(storedJson(campaign.segment??{})),users=await candidatesForCampaign(campaign,segment);
      for(const user of users){
        const [recipient]=await database()`insert into notification_campaign_recipients(campaign_id,user_id,status,scheduled_at) values (${item.id},${user.id},'QUEUED',${campaign.scheduled_at}) on conflict(campaign_id,user_id) do nothing returning id::text`;
        if(!recipient)continue;
        const limits=await nonCriticalLimitReasons(String(user.id),config);
        if(limits.length){
          await database()`update notification_campaign_recipients set status='SKIPPED',error_code='NON_CRITICAL_LIMIT',error_message=${limits.join(',')} where id=${recipient.id}`;
          continue;
        }
        const category=campaign.campaignType==='PROMOTIONAL'?'PROMOTIONAL':'CAMPAIGN';
        const result=await notificationService.send({userId:String(user.id),type:String(campaign.campaignType),category,priority:category==='PROMOTIONAL'?'PROMOTIONAL':'CAMPAIGN',title:String(campaign.title),body:String(campaign.body),referenceId:String(item.id),deepLink:campaign.deep_link??undefined,action:campaign.action??undefined,metadata:{campaignId:item.id,...(campaign.metadata??{})},persistInCenter:true,sendPush:true,idempotencyKey:`CAMPAIGN:${item.id}:${user.id}`});
        await database()`update notification_campaign_recipients set notification_id=${result.notificationId||null},status=${result.pushSent?'SENT':result.status},sent_at=case when ${result.pushSent} then now() else null end,error_code=${result.errorCode??null},error_message=${result.errorMessage??null} where id=${recipient.id}`;
      }
      await database()`update notification_campaigns set status=case when exists(select 1 from notification_campaign_recipients where campaign_id=${item.id} and status='QUEUED') then 'PROCESSING' else 'SENT' end,completed_at=case when exists(select 1 from notification_campaign_recipients where campaign_id=${item.id} and status='QUEUED') then null else now() end,updated_at=now() where id=${item.id}`;
    }catch(error){
      await database()`update notification_campaigns set status='FAILED',completed_at=now(),updated_at=now() where id=${item.id}`;
      console.error('notification_campaign_failed',{campaignId:item.id,error:error instanceof Error?error.message:String(error)});
    }
  }
}

function guard(error:unknown,reply:any){const message=error instanceof Error?error.message:'ERROR';if(message==='FORBIDDEN')return reply.code(403).send({error:message});if(message==='UNAUTHORIZED')return reply.code(401).send({error:message});if(error instanceof z.ZodError)return reply.code(400).send({error:'INVALID_DATA',issues:error.issues});throw error;}
export async function registerSmartNotificationRoutes(app:FastifyInstance){
  app.get('/v1/admin/notifications/health',async(request,reply)=>{try{requirePermission(request,'notifications:view');return notificationSystemHealth();}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/delivery-config',async(request,reply)=>{try{requirePermission(request,'notifications:view');const [row]=await database()`select max_attempts as "maxAttempts",base_backoff_seconds as "baseBackoffSeconds",batch_size as "batchSize",circuit_failure_threshold as "circuitFailureThreshold",circuit_window_minutes as "circuitWindowMinutes",circuit_cooldown_minutes as "circuitCooldownMinutes",attribution_window_hours as "attributionWindowHours",analytics_retention_days as "analyticsRetentionDays",delivery_retention_days as "deliveryRetentionDays",updated_at as "updatedAt" from notification_delivery_config where id=1`;return row;}catch(error){return guard(error,reply);}});
  app.put('/v1/admin/notifications/delivery-config',async(request,reply)=>{try{const actor=requirePermission(request,'notifications:manage');const body=z.object({maxAttempts:z.number().int().min(1).max(12),baseBackoffSeconds:z.number().int().min(5).max(3600),batchSize:z.number().int().min(1).max(500),circuitFailureThreshold:z.number().int().min(2).max(1000),circuitWindowMinutes:z.number().int().min(1).max(120),circuitCooldownMinutes:z.number().int().min(1).max(1440),attributionWindowHours:z.number().int().min(1).max(720),analyticsRetentionDays:z.number().int().min(30).max(1095),deliveryRetentionDays:z.number().int().min(30).max(365)}).parse(request.body);const [previous]=await database()`select to_jsonb(notification_delivery_config) value from notification_delivery_config where id=1`;const [row]=await database()`update notification_delivery_config set max_attempts=${body.maxAttempts},base_backoff_seconds=${body.baseBackoffSeconds},batch_size=${body.batchSize},circuit_failure_threshold=${body.circuitFailureThreshold},circuit_window_minutes=${body.circuitWindowMinutes},circuit_cooldown_minutes=${body.circuitCooldownMinutes},attribution_window_hours=${body.attributionWindowHours},analytics_retention_days=${body.analyticsRetentionDays},delivery_retention_days=${body.deliveryRetentionDays},updated_by=${actor.id!},updated_at=now() where id=1 returning updated_at as "updatedAt"`;await database()`insert into audit_log(actor_id,action,entity_type,entity_id,previous_value,next_value,reason) values(${actor.id!},'NOTIFICATION_DELIVERY_CONFIG_UPDATED','NOTIFICATION_CONFIG','1',${JSON.stringify(previous?.value??{})}::jsonb,${JSON.stringify(body)}::jsonb,'Parámetros de entrega, atribución y retención actualizados')`;return {...body,...row};}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/diagnostics',async(request,reply)=>{try{requirePermission(request,'notifications:view');const q=z.string().trim().min(2).max(120).parse((request.query as any).q);return notificationUserDiagnostic(q);}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/conversion-funnel',async(request,reply)=>{try{requirePermission(request,'notifications:view');const rows=await database()`select n.notification_type as type,count(distinct n.id) filter(where n.status='SENT')::int sent,count(distinct e.notification_id) filter(where e.event='OPENED')::int opened,count(distinct a.notification_id) filter(where a.prepared_at is not null)::int prepared,count(distinct a.notification_id) filter(where a.requested_at is not null and a.requested_at<=a.attribution_expires_at)::int requested,count(distinct a.notification_id) filter(where a.completed_at is not null and a.completed_at<=a.attribution_expires_at)::int completed from user_notifications n left join notification_analytics_events e on e.notification_id=n.id left join notification_trip_attributions a on a.notification_id=n.id where n.created_at>=now()-interval '30 days' group by n.notification_type order by sent desc`;return {items:rows.map((row:any)=>({...row,openRate:number(row.sent)?Math.round(number(row.opened)/number(row.sent)*10000)/100:0,requestRate:number(row.sent)?Math.round(number(row.requested)/number(row.sent)*10000)/100:0,completionRate:number(row.requested)?Math.round(number(row.completed)/number(row.requested)*10000)/100:0}))};}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/simulate',async(request,reply)=>{try{requirePermission(request,'notifications:test');const body=z.object({campaignType:z.enum(campaignTypes),segment:segmentSchema,metadata:z.record(z.string(),z.unknown()).default({})}).parse(request.body);const result=body.campaignType==='APP_UPDATE'?await estimateAppUpdate(body.segment,body.metadata):await estimateSegment(body.segment,body.campaignType==='PROMOTIONAL');return {...result,simulation:true,sideEffects:{notifications:0,pushes:0,metrics:0,limitsConsumed:0}};}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/summary',async(request,reply)=>{try{requirePermission(request,'notifications:view');const [summary]=await database()`select (select count(distinct passenger_id)::int from trips where requested_at>=now()-interval '30 days') as "usersAnalyzed",(select count(*)::int from smart_notification_patterns where is_active) as "patternsDetected",(select count(*)::int from smart_notification_patterns where is_active and confidence_score>=(select minimum_confidence from smart_notification_config where id=1)) as "eligible",(select count(*)::int from user_notifications where category in ('SMART','CAMPAIGN','PROMOTIONAL') and created_at>=current_date and status='SENT') as "sentToday",(select count(*)::int from notification_analytics_events e join user_notifications n on n.id=e.notification_id where n.category in ('SMART','CAMPAIGN','PROMOTIONAL') and e.event='OPENED' and e.occurred_at>=current_date) as "openedToday",(select count(*)::int from notification_analytics_events e join user_notifications n on n.id=e.notification_id where n.category in ('SMART','CAMPAIGN','PROMOTIONAL') and e.event='TRIP_REQUESTED' and e.occurred_at>=current_date) as "tripsGenerated"`;const trend=await database()`select day::date::text,coalesce(sent,0)::int sent,coalesce(opened,0)::int opened,coalesce(trips,0)::int trips from generate_series(current_date-29,current_date,'1 day') day left join lateral(select count(*) filter(where e.event='SENT') sent,count(*) filter(where e.event='OPENED') opened,count(*) filter(where e.event='TRIP_REQUESTED') trips from notification_analytics_events e join user_notifications n on n.id=e.notification_id where n.category in ('SMART','CAMPAIGN','PROMOTIONAL') and e.occurred_at>=day and e.occurred_at<day+interval '1 day') metrics on true order by day`;const values=summary??{};return {...values,conversion:number(values.sentToday)?Math.round(number(values.tripsGenerated)/number(values.sentToday)*10000)/100:0,trend};}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/smart/config',async(request,reply)=>{try{requirePermission(request,'notifications:view');return smartConfig();}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/reminder-config',async(request,reply)=>{try{requirePermission(request,'notifications:view');const [row]=await database()`select passenger_scheduled_reminder_minutes as "passengerScheduledReminderMinutes",passenger_scheduled_max_reminders as "passengerScheduledMaxReminders",reminder_allowed_start_time::text as "allowedStartTime",reminder_allowed_end_time::text as "allowedEndTime",driver_membership_reminder_days as "driverMembershipReminderDays",driver_membership_max_reminders as "driverMembershipMaxReminders",driver_document_reminder_days as "driverDocumentReminderDays" from operational_settings where id=1`;return {...row,allowedStartTime:time(row?.allowedStartTime),allowedEndTime:time(row?.allowedEndTime)};}catch(error){return guard(error,reply);}});
  app.put('/v1/admin/notifications/reminder-config',async(request,reply)=>{try{const actor=requirePermission(request,'notifications:manage');const value=reminderConfigSchema.parse(request.body);await database()`update operational_settings set passenger_scheduled_reminder_minutes=${value.passengerScheduledReminderMinutes},passenger_scheduled_max_reminders=${value.passengerScheduledMaxReminders},reminder_allowed_start_time=${value.allowedStartTime}::time,reminder_allowed_end_time=${value.allowedEndTime}::time,driver_membership_reminder_days=${value.driverMembershipReminderDays},driver_membership_max_reminders=${value.driverMembershipMaxReminders},driver_document_reminder_days=${value.driverDocumentReminderDays},updated_by=${actor.id!},updated_at=now() where id=1`;await database()`insert into audit_log(actor_id,action,entity_type,entity_id,next_value,reason) values(${actor.id!},'NOTIFICATION_REMINDER_CONFIG_UPDATED','OPERATIONAL_SETTINGS','1',${JSON.stringify(value)}::jsonb,'Parámetros de recordatorios actualizados')`;return value;}catch(error){return guard(error,reply);}});
  app.put('/v1/admin/notifications/smart/config',async(request,reply)=>{try{const actor=requirePermission(request,'notifications:manage');const value=configSchema.parse(request.body);const [previous]=await database()`select to_jsonb(smart_notification_config) value from smart_notification_config where id=1`;const [row]=await database()`update smart_notification_config set mode=${value.mode},frequent_trip_enabled=${value.frequentTripEnabled},return_trip_enabled=${value.returnTripEnabled},favorite_destination_enabled=${value.favoriteDestinationEnabled},reactivation_enabled=${value.reactivationEnabled},minimum_trips=${value.minimumTrips},minimum_matches=${value.minimumMatches},minimum_confidence=${value.minimumConfidence},analysis_window_days=${value.analysisWindowDays},schedule_tolerance_minutes=${value.scheduleToleranceMinutes},notification_lead_minutes=${value.notificationLeadMinutes},max_per_user_per_day=${value.maxPerUserPerDay},max_per_user_per_week=${value.maxPerUserPerWeek},ignored_to_reduce_frequency=${value.ignoredToReduceFrequency},ignored_to_pause=${value.ignoredToPause},auto_pause_days=${value.autoPauseDays},reduced_frequency_multiplier=${value.reducedFrequencyMultiplier},minimum_interval_minutes=${value.minimumIntervalMinutes},allowed_start_time=${value.allowedStartTime}::time,allowed_end_time=${value.allowedEndTime}::time,enabled_week_days=${value.enabledWeekDays},inactive_user_days=${value.inactiveUserDays},scheduler_interval_minutes=${value.schedulerIntervalMinutes},updated_by=${actor.id!},updated_at=now() where id=1 returning updated_at as "updatedAt"`;if(!row)throw new Error('SMART_CONFIG_NOT_FOUND');await database()`insert into audit_log(actor_id,action,entity_type,entity_id,previous_value,next_value,reason) values (${actor.id!},'SMART_NOTIFICATION_CONFIG_UPDATED','SMART_NOTIFICATION_CONFIG','1',${JSON.stringify(previous?.value??{})}::jsonb,${JSON.stringify(value)}::jsonb,'Configuración modificada desde Notificaciones Inteligentes')`;return {...value,updatedAt:row.updatedAt};}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/app-versions',async(request,reply)=>{try{requirePermission(request,'notifications:view');return database()`select platform,latest_version as "latestVersion",latest_build as "latestBuild",minimum_supported_version as "minimumSupportedVersion",minimum_supported_build as "minimumSupportedBuild",update_policy as "updatePolicy",required_update_enabled as "requiredUpdateEnabled",message,store_url as "storeUrl",updated_at as "updatedAt" from app_version_config order by platform`;}catch(error){return guard(error,reply);}});
  app.put('/v1/admin/notifications/app-versions/:platform',async(request,reply)=>{try{const actor=requirePermission(request,'notifications:manage');const platform=z.enum(['ANDROID','IOS']).parse((request.params as any).platform);const version=z.string().trim().regex(/^\d+(?:\.\d+){1,3}(?:[-+][0-9A-Za-z.-]+)?$/).max(50).nullable();const body=z.object({latestVersion:version,latestBuild:z.number().int().min(1).nullable(),minimumSupportedVersion:version,minimumSupportedBuild:z.number().int().min(1).nullable(),updatePolicy:z.enum(['RECOMMENDED','REQUIRED']).default('RECOMMENDED'),requiredUpdateEnabled:z.literal(false).default(false),message:z.string().trim().min(1).max(500),storeUrl:z.string().url().max(500).nullable()}).parse(request.body);const [row]=await database()`update app_version_config set latest_version=${body.latestVersion},latest_build=${body.latestBuild},minimum_supported_version=${body.minimumSupportedVersion},minimum_supported_build=${body.minimumSupportedBuild},update_policy=${body.updatePolicy},required_update_enabled=false,message=${body.message},store_url=${body.storeUrl},updated_by=${actor.id!},updated_at=now() where platform=${platform} returning platform,latest_version as "latestVersion",latest_build as "latestBuild",minimum_supported_version as "minimumSupportedVersion",minimum_supported_build as "minimumSupportedBuild",update_policy as "updatePolicy",required_update_enabled as "requiredUpdateEnabled",message,store_url as "storeUrl",updated_at as "updatedAt"`;return row;}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/smart/analyze',async(request,reply)=>{try{requirePermission(request,'notifications:manage');const parsed=z.object({userId:z.string().uuid().optional()}).parse(request.body??{});return analyzeSmartPatterns(parsed.userId);}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/smart/patterns',async(request,reply)=>{try{requirePermission(request,'notifications:view');const query=z.object({limit:z.coerce.number().int().min(1).max(200).default(50),type:z.enum(patternTypes).optional(),q:z.string().trim().max(100).default('')}).parse(request.query);const search=`%${query.q.replace(/[\\%_]/g,'\\$&')}%`;const rows=await database()`select p.id::text,p.pattern_type as type,p.origin_reference as origin,p.destination_reference as destination,p.week_days as "weekDays",p.average_time::text as "averageTime",p.matches_count as matches,p.trips_analyzed as "tripsAnalyzed",p.confidence_score::float8 as confidence,p.last_evaluated_at as "lastEvaluatedAt",u.full_name as user,u.id::text as "userId" from smart_notification_patterns p join users u on u.id=p.user_id where p.is_active and (${query.type??null}::text is null or p.pattern_type=${query.type??null}) and (${query.q}='' or u.full_name ilike ${search} or p.origin_reference ilike ${search} or p.destination_reference ilike ${search}) order by p.confidence_score desc,p.last_evaluated_at desc limit ${query.limit}`;return {items:rows};}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/smart/patterns/:id',async(request,reply)=>{try{requirePermission(request,'notifications:view');const id=z.string().uuid().parse((request.params as any).id);const evaluated=await eligibility(id);if(evaluated.reasons?.includes('PATTERN_NOT_FOUND'))return reply.code(404).send({error:'PATTERN_NOT_FOUND'});return evaluated;}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/smart/patterns/:id/simulate',async(request,reply)=>{try{requirePermission(request,'notifications:test');const id=z.string().uuid().parse((request.params as any).id);return eligibility(id);}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/smart/patterns/:id/test-send',async(request,reply)=>{try{requirePermission(request,'notifications:test');const id=z.string().uuid().parse((request.params as any).id);const evaluated=await eligibility(id,{...(await smartConfig()),mode:'TEST'});if(!evaluated.tester)return reply.code(403).send({error:'TEST_USER_NOT_ALLOWED'});return notificationService.send({...smartCommand(evaluated),idempotencyKey:`TEST:SMART:${id}:${Date.now()}`});}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/test-users',async(request,reply)=>{try{requirePermission(request,'notifications:test');const query=z.object({q:z.string().trim().max(100).default('')}).parse(request.query);const search=`%${query.q.replace(/[\\%_]/g,'\\$&')}%`;return database()`select u.id::text,u.full_name as name,u.email,t.enabled,d.platform,d.last_seen_at as "lastActivity",(select max(n.push_sent_at) from user_notifications n where n.user_id=u.id) as "lastPush" from notification_test_users t join users u on u.id=t.user_id left join lateral(select platform,last_seen_at from device_tokens where user_id=u.id and enabled and invalidated_at is null order by last_seen_at desc limit 1)d on true where ${query.q}='' or u.full_name ilike ${search} or u.email ilike ${search} order by u.full_name`;}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/test-users/search',async(request,reply)=>{try{requirePermission(request,'notifications:test');const q=z.string().trim().min(2).max(100).parse((request.query as any).q);const search=`%${q.replace(/[\\%_]/g,'\\$&')}%`;return database()`select u.id::text,u.full_name as name,u.email,d.platform,d.last_seen_at as "lastActivity",(d.token is not null) as "validToken" from users u left join lateral(select token,platform,last_seen_at from device_tokens where user_id=u.id and enabled and invalidated_at is null order by last_seen_at desc limit 1)d on true where u.status='ACTIVE' and u.deleted_at is null and (u.full_name ilike ${search} or u.email ilike ${search} or u.phone_e164 ilike ${search}) order by u.full_name limit 20`;}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/test-users',async(request,reply)=>{try{const actor=requirePermission(request,'notifications:test');const body=z.object({userId:z.string().uuid()}).parse(request.body);const [row]=await database()`insert into notification_test_users(user_id,enabled,created_by) values (${body.userId},true,${actor.id!}) on conflict(user_id) do update set enabled=true,updated_at=now() returning id::text`;return reply.code(201).send(row);}catch(error){return guard(error,reply);}});
  app.delete('/v1/admin/notifications/test-users/:userId',async(request,reply)=>{try{requirePermission(request,'notifications:test');const userId=z.string().uuid().parse((request.params as any).userId);await database()`update notification_test_users set enabled=false,updated_at=now() where user_id=${userId}`;return {disabled:true};}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/test-send',async(request,reply)=>{try{const actor=requirePermission(request,'notifications:test');const body=testSendSchema.parse(request.body);const [tester]=await database()`select 1 from notification_test_users where user_id=${body.userId} and enabled`;if(!tester)return reply.code(403).send({error:'TEST_USER_NOT_ALLOWED'});const result=await notificationService.send({userId:body.userId,type:body.type,category:body.type.startsWith('SMART_')?'SMART':'OPERATIONAL',priority:body.type.startsWith('SMART_')?'SMART':'OPERATIONAL',title:body.title,body:body.message,deepLink:body.deepLink,action:body.action,metadata:body.destination?{destinationReference:body.destination.reference,destinationLatitude:body.destination.latitude,destinationLongitude:body.destination.longitude}:undefined,persistInCenter:true,sendPush:true,idempotencyKey:`MANUAL_TEST:${body.userId}:${Date.now()}`});await database()`insert into audit_log(actor_id,action,entity_type,entity_id,next_value,reason) values(${actor.id!},'NOTIFICATION_TEST_SENT','USER',${body.userId},${JSON.stringify({type:body.type,notificationId:result.notificationId})}::jsonb,'Prueba enviada desde el centro de notificaciones')`;return result;}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/campaigns',async(request,reply)=>{try{requirePermission(request,'notification_campaigns:view');const rows=await database()`select c.id::text,c.name,c.campaign_type as type,c.title,c.segment,c.status,c.scheduled_at as "scheduledAt",c.created_at as "createdAt",count(distinct r.id)::int recipients,count(distinct r.id) filter(where r.status in ('SENT','OPENED'))::int sent,count(distinct r.id) filter(where r.status='OPENED')::int opened,count(distinct e.notification_id) filter(where e.event='APP_UPDATED')::int updated from notification_campaigns c left join notification_campaign_recipients r on r.campaign_id=c.id left join notification_analytics_events e on e.notification_id=r.notification_id group by c.id order by c.created_at desc limit 200`;return rows.map(row=>({...row,segment:storedJson(row.segment)}));}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/campaigns',async(request,reply)=>{try{const actor=requirePermission(request,'notification_campaigns:manage');const body=campaignSchema.parse(request.body);const [row]=await database()`insert into notification_campaigns(name,campaign_type,title,body,deep_link,action,metadata,segment,created_by,updated_by) values (${body.name},${body.campaignType},${body.title},${body.body},${body.deepLink||null},${body.action||null},${JSON.stringify(body.metadata)}::jsonb,${JSON.stringify(body.segment)}::jsonb,${actor.id!},${actor.id!}) returning id::text,status`;if(!row)throw new Error('CAMPAIGN_NOT_CREATED');await database()`insert into audit_log(actor_id,action,entity_type,entity_id,next_value,reason) values(${actor.id!},'NOTIFICATION_CAMPAIGN_CREATED','NOTIFICATION_CAMPAIGN',${row.id},${JSON.stringify(body)}::jsonb,'Campaña creada en borrador')`;return reply.code(201).send(row);}catch(error){return guard(error,reply);}});
  app.get('/v1/admin/notifications/campaigns/:id',async(request,reply)=>{try{requirePermission(request,'notification_campaigns:view');const id=z.string().uuid().parse((request.params as any).id);const [row]=await database()`select id::text,name,campaign_type as "campaignType",title,body,deep_link as "deepLink",action,metadata,segment,status,scheduled_at as "scheduledAt",created_at as "createdAt",updated_at as "updatedAt" from notification_campaigns where id=${id}`;if(!row)return reply.code(404).send({error:'CAMPAIGN_NOT_FOUND'});const recipients=await database()`select u.full_name as name,u.email,r.status,r.error_code as "errorCode",r.error_message as "errorMessage",r.sent_at as "sentAt",exists(select 1 from notification_analytics_events e where e.notification_id=r.notification_id and e.event='STORE_OPENED') as "storeOpened",exists(select 1 from notification_analytics_events e where e.notification_id=r.notification_id and e.event='APP_UPDATED') as updated from notification_campaign_recipients r join users u on u.id=r.user_id where r.campaign_id=${id} order by u.email`;return {...row,metadata:storedJson(row.metadata),segment:storedJson(row.segment),recipients,updateMetrics:{notified:recipients.filter((item:any)=>['SENT','OPENED'].includes(item.status)).length,storeOpened:recipients.filter((item:any)=>item.storeOpened).length,updated:recipients.filter((item:any)=>item.updated).length,pending:recipients.filter((item:any)=>['SENT','OPENED'].includes(item.status)&&!item.updated).length}};}catch(error){return guard(error,reply);}});
  app.put('/v1/admin/notifications/campaigns/:id',async(request,reply)=>{try{const actor=requirePermission(request,'notification_campaigns:manage');const id=z.string().uuid().parse((request.params as any).id),body=campaignSchema.parse(request.body);const [before]=await database()`select to_jsonb(notification_campaigns) value from notification_campaigns where id=${id}`;const [row]=await database()`update notification_campaigns set name=${body.name},campaign_type=${body.campaignType},title=${body.title},body=${body.body},deep_link=${body.deepLink||null},action=${body.action||null},metadata=${JSON.stringify(body.metadata)}::jsonb,segment=${JSON.stringify(body.segment)}::jsonb,updated_by=${actor.id!},updated_at=now() where id=${id} and status='DRAFT' returning id::text,status`;if(row)await database()`insert into audit_log(actor_id,action,entity_type,entity_id,previous_value,next_value,reason) values(${actor.id!},'NOTIFICATION_CAMPAIGN_UPDATED','NOTIFICATION_CAMPAIGN',${id},${JSON.stringify(before?.value??{})}::jsonb,${JSON.stringify(body)}::jsonb,'Campaña en borrador modificada')`;return row??reply.code(409).send({error:'CAMPAIGN_NOT_EDITABLE'});}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/campaigns/:id/estimate',async(request,reply)=>{try{requirePermission(request,'notification_campaigns:view');const id=z.string().uuid().parse((request.params as any).id);const [campaign]=await database()`select campaign_type as "campaignType",segment,metadata from notification_campaigns where id=${id}`;if(!campaign)return reply.code(404).send({error:'CAMPAIGN_NOT_FOUND'});const segment=segmentSchema.parse(storedJson(campaign.segment));return campaign.campaignType==='APP_UPDATE'?estimateAppUpdate(segment,campaign.metadata):estimateSegment(segment,campaign.campaignType==='PROMOTIONAL');}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/campaigns/:id/test',async(request,reply)=>{try{const actor=requirePermission(request,'notifications:test');const id=z.string().uuid().parse((request.params as any).id),body=z.object({userId:z.string().uuid()}).parse(request.body);const [campaign]=await database()`select campaign_type as type,title,body,deep_link as "deepLink",action,metadata from notification_campaigns where id=${id}`;const [tester]=await database()`select 1 from notification_test_users where user_id=${body.userId} and enabled`;if(!campaign||!tester)return reply.code(403).send({error:'TEST_USER_NOT_ALLOWED'});const result=await notificationService.send({userId:body.userId,type:String(campaign.type),category:campaign.type==='PROMOTIONAL'?'PROMOTIONAL':'CAMPAIGN',priority:campaign.type==='PROMOTIONAL'?'PROMOTIONAL':'CAMPAIGN',title:String(campaign.title),body:String(campaign.body),deepLink:campaign.deepLink,action:campaign.action,metadata:{campaignId:id,...(campaign.metadata??{})},persistInCenter:true,sendPush:true,idempotencyKey:`CAMPAIGN_TEST:${id}:${body.userId}:${Date.now()}`});await database()`insert into audit_log(actor_id,action,entity_type,entity_id,next_value,reason) values(${actor.id!},'NOTIFICATION_CAMPAIGN_TEST_SENT','NOTIFICATION_CAMPAIGN',${id},${JSON.stringify({userId:body.userId,notificationId:result.notificationId})}::jsonb,'Prueba de campaña enviada')`;return result;}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/campaigns/:id/schedule',async(request,reply)=>{try{const actor=requirePermission(request,'notification_campaigns:manage');const id=z.string().uuid().parse((request.params as any).id),body=z.object({scheduledAt:z.string().datetime({offset:true})}).parse(request.body);const scheduled=new Date(body.scheduledAt);if(scheduled.getTime()<Date.now()+60000)return reply.code(400).send({error:'SCHEDULE_TOO_SOON'});const scheduleReasons=scheduleLimitReasons(scheduled,await smartConfig());if(scheduleReasons.length)return reply.code(400).send({error:'CAMPAIGN_OUTSIDE_ALLOWED_WINDOW',reasons:scheduleReasons});const [row]=await database()`update notification_campaigns set status='SCHEDULED',scheduled_at=${scheduled},updated_by=${actor.id!},updated_at=now() where id=${id} and status='DRAFT' returning id::text,status,scheduled_at as "scheduledAt"`;if(row)await database()`insert into audit_log(actor_id,action,entity_type,entity_id,next_value,reason) values(${actor.id!},'NOTIFICATION_CAMPAIGN_SCHEDULED','NOTIFICATION_CAMPAIGN',${id},${JSON.stringify({scheduledAt:scheduled.toISOString()})}::jsonb,'Campaña programada')`;return row??reply.code(409).send({error:'CAMPAIGN_NOT_SCHEDULABLE'});}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/campaigns/:id/remind-pending',async(request,reply)=>{try{const actor=requirePermission(request,'notification_campaigns:manage');const id=z.string().uuid().parse((request.params as any).id);const [campaign]=await database()`select * from notification_campaigns where id=${id} and campaign_type='APP_UPDATE' and status='SENT'`;if(!campaign)return reply.code(409).send({error:'APP_UPDATE_CAMPAIGN_NOT_SENT'});const target=appUpdateMetadataSchema.parse(storedJson(campaign.metadata));const devices=await database()`select distinct on(r.user_id) r.user_id::text as id,d.app_version as "appVersion",d.app_build as "appBuild",d.platform from notification_campaign_recipients r left join device_tokens d on d.user_id=r.user_id and d.enabled and d.invalidated_at is null where r.campaign_id=${id} and r.status in('SENT','OPENED') order by r.user_id,d.last_seen_at desc nulls last`;const pending=devices.filter((row:any)=>row.platform===target.targetPlatform&&appUpdateDisposition(row,target)!=='UPDATED').map((row:any)=>String(row.id));const segment={zones:[],roles:[],platforms:[target.targetPlatform],userIds:pending,userEmails:[]};const [created]=await database()`insert into notification_campaigns(name,campaign_type,title,body,deep_link,action,metadata,segment,created_by,updated_by) values(${`Recordatorio · ${campaign.name}`},'APP_UPDATE',${campaign.title},${campaign.body},${campaign.deep_link},${campaign.action},${JSON.stringify({...target,audienceMode:'MANUAL'})}::jsonb,${JSON.stringify(segment)}::jsonb,${actor.id!},${actor.id!}) returning id::text,status`;if(!created)throw new Error('CAMPAIGN_NOT_CREATED');await database()`insert into audit_log(actor_id,action,entity_type,entity_id,next_value,reason) values(${actor.id!},'APP_UPDATE_PENDING_REMINDER_CREATED','NOTIFICATION_CAMPAIGN',${created.id},${JSON.stringify({sourceCampaignId:id,pendingUsers:pending.length})}::jsonb,'Audiencia pendiente recalculada con la versión instalada actual')`;return reply.code(201).send({...created,pendingUsers:pending.length});}catch(error){return guard(error,reply);}});
  app.post('/v1/admin/notifications/campaigns/:id/cancel',async(request,reply)=>{try{const actor=requirePermission(request,'notification_campaigns:manage');const id=z.string().uuid().parse((request.params as any).id);const [row]=await database()`update notification_campaigns set status='CANCELLED',cancelled_at=now(),updated_by=${actor.id!},updated_at=now() where id=${id} and status in ('DRAFT','SCHEDULED') returning id::text,status`;if(row)await database()`insert into audit_log(actor_id,action,entity_type,entity_id,next_value,reason) values(${actor.id!},'NOTIFICATION_CAMPAIGN_CANCELLED','NOTIFICATION_CAMPAIGN',${id},${JSON.stringify({status:'CANCELLED'})}::jsonb,'Campaña cancelada')`;return row??reply.code(409).send({error:'CAMPAIGN_NOT_CANCELLABLE'});}catch(error){return guard(error,reply);}});
}
